### ISSUE TITLE
Support for React 0.14 beta

### ISSUE THREAD

**Issue by bradbirnbaum** [negomi/react-burger-menu#10]
Do you have plans to add support for React 0.14?

**Comment by negomi** [comment]
Hi @bradbirnbaum, yes, I'm in the process of upgrading to the new version. Should be able to release soon :)

**Comment by MMRandy** [comment]
:+1:

**Comment by negomi** [comment]
Fixed in https://github.com/negomi/react-burger-menu/releases/tag/v1.2.0
