### ISSUE TITLE
Fixed header while menu open?

### ISSUE THREAD

**Issue by robrobkay51** [negomi/react-burger-menu#100]
I have implemented the burger-menu along with a fixed header bar which runs across the top of my application.

The header remains fixed on scroll when the menu is closed however when the menu is open, the header bar is no longer fixed and scrolls down the page. 

I would like the header bar to also remain fixed when the menu is open - is there any way I can achieve this? 

Any help much appreciated! :)

**Comment by ixley** [comment]
@robrobkay51 can you check and see if the `overflow: hidden;` styles get added to and removed from the `html` and `body` tags? We are experiencing similar conflicts so I'm curious whether this is a related issue. 

See #103

**Comment by negomi** [comment]
Hi @robrobkay51, are you able to put an example of this bug into a small repo so I can look into it? Thanks.

**Comment by robrobkay51** [comment]
Hi @negomi, problem can be found in the repo link below (which is based on dave zuko redux boilerplate)

[](https://github.com/robrobkay51/slide-app 
)

instructions for usage: 

npm install
npm start 

then go to localhost:3000 

You should be able to see the problem when minimizing the window and scrolling down the page.

**Comment by negomi** [comment]
Ah, so in this case, you will actually want to put your header *outside* the `page-wrap` element:

```javascript
<div id="outer-container">
  <Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } noOverlay />
  <header className="header-bar"></header>
  <main id="page-wrap">
    // Other stuff
  </main>
</div
```

I know the docs don't tell you this, but they are misleading, and should really say 'the rest of the content on your page **except** fixed elements'. I will update them asap.

Thanks for raising this - I hadn't run into this use case yet :)

**Comment by Axelest** [comment]
Hey negomi, how do you actually stop the window from scrolling when the menu is active?
