### ISSUE TITLE
Problem with Firefox IOS

### ISSUE THREAD

**Issue by ceasbz** [negomi/react-burger-menu#102]
I am testing in your website example (http://negomi.github.io/react-burger-menu/) and have a problem with Firefox IOS, look:

![img_4141](https://cloud.githubusercontent.com/assets/7065285/18673754/522b1614-7f23-11e6-8d24-8fd4e3598310.PNG)

Informations:
- Browser: Firefox 5.2 
- Hardware: IPhone 5s (IOS 10)

The Menu `transiction` doesn't work. Do you have any idea when going to support that?

**Comment by negomi** [comment]
Hi @ceasbz,

This project has never really focused on extensive browser support, but I am happy to accept PRs, or will look into this when I get some time.

Thanks for raising the issue.

**Comment by ceasbz** [comment]
@negomi Currently, what are the supporting browsers? Do you have any idea?

**Comment by negomi** [comment]
https://github.com/negomi/react-burger-menu#browser-support

But that only covers web - no guarantees about the mobile versions.

**Comment by ranjithnori** [comment]
@ceasbz Did you find a workaround for this issue ?

**Comment by ceasbz** [comment]
Hey @negomi, sorry for delay.

Thanks for the answer. :)

**Comment by ceasbz** [comment]
@ranjithnori No, but when I got time, want to solve that.

Do you have any solution?

**Comment by horaceleung** [comment]
If anyone have a quick workaround for this, would be much appreciated!

**Comment by ranjithnori** [comment]
@horaceleung 
https://github.com/ranjithnori/react-burger-menu/commit/800f696fea73b60bca5d3a3e0a7cd4d50c91ee7d

With this commit, the issues we faced with some older Firefox versions are resolved. Please see if it works for you.

**Comment by horaceleung** [comment]
hey @ranjithnori 
thanks a lot for the help. I've tried using your commit and deployed it, but it still hasn't fixed the issue unfortunately :(

**Comment by Alorse** [comment]
Has anyone found any solutions to this bug?

**Comment by matejstrasek** [comment]
I would also need a solution for this. :P

**Comment by jontelm** [comment]
I think problem is that we need to add some -Moz css to get this to work. The best option is maybe to move the css to a separate css file instead of inline, because we can easily solve this issue then with https://github.com/postcss/autoprefixer so we don't get this kind of problems later on.

**Comment by matejstrasek** [comment]
With this it works for me now: https://github.com/negomi/react-burger-menu/commit/19caff4bc5d3b795a16ba08a2eccef9eabba67e4

**Comment by horaceleung** [comment]
@matejstrasek Did you try the fix on FF on iOS? I tried it but still doesn't seem to resolve the issue there.

**Comment by matejstrasek** [comment]
@horaceleung yes, for me it works on iOS with FF.

**Comment by negomi** [comment]
Fixed by https://github.com/negomi/react-burger-menu/pull/132
