### ISSUE TITLE
'overflow-x: hidden;' does not get removed from html or body tags

### ISSUE THREAD

**Issue by ixley** [negomi/react-burger-menu#103]
After getting triggered for the first time, the inline styles for `overflow-x: hidden;` that get added to the `html` and `body` tags do not get removed on close. I'm not sure why they don't get removed (it looks like they're supposed to?), but I noticed it because it causes conflicts for us.

**Comment by negomi** [comment]
Hi @ixley, I see this too - it's a bug. Will fix asap.

Thanks for reporting!

**Comment by ConneXNL** [comment]
Also came across this issue.
Any ETA @negomi  ?

**Comment by negomi** [comment]
Fixed in v1.10.6
