### ISSUE TITLE
Custom Icon placed anywhere to toggle menu

### ISSUE THREAD

**Issue by jsingh27** [negomi/react-burger-menu#104]
Hi,

Please add a option so that I can add any icon from material-ui/or any other library anywhere to toggle the menu.

For example: I want to place an custom an icon in <Header> component to toggle the menu.

Thanks :)

**Comment by negomi** [comment]
Hi @jsingh27, you should be able to achieve this already with a combination of https://github.com/negomi/react-burger-menu#open-state and https://github.com/negomi/react-burger-menu#custom-icons.

Pass `customBurgerIcon={ false }` to avoid rendering the default burger icon. Then attach an event to the icon you want to open the menu. In its handler, you'll need to trigger a re-render (exactly what this looks like will depend on how you're managing state) that causes the menu to render with `isOpen={ true }`.

Hope that helps - please let me know if it doesn't make sense :)

**Comment by jsingh27** [comment]
Thanks :')
