### ISSUE TITLE
I am following the demo,  but I do not see the burger menu,  functionality exists

### ISSUE THREAD

**Issue by dfunaki** [negomi/react-burger-menu#106]
I am trying to use this, but I cannot see the burger menu, but if I mouse hover over and click, the menu appears.  Also, specifying 
`
<Menu left> .... </Menu>
`
  if I click on the right side of the browser, it pops up...

Can anyone help me out?

**Comment by negomi** [comment]
Hi @dfunaki, so you're able to click on the element to open the menu, but just can't see burger icon?

My first guess would be that it's a styling issue. Have you given the bars a background color?

There are a few other things it could be, but it's hard to say without seeing your code. If you can put some code recreating the issue in a small repo, I'm happy to take a look.

**Comment by dfunaki** [comment]
`import React from 'react'
import {slide as Menu} from 'react-burger-menu';

var GlobalNav = React.createClass({

  render() {
    return(
      <div style={{height: '100%'}}>
       <Menu>
          <a id="home" className="menu-item" href="/">Home</a>
          <a id="about" className="menu-item" href="/about">About</a>
          <a id="contact" className="menu-item" href="/contact">Contact</a>
        </Menu>
      </div>
    );
  },

})

export default GlobalNav;
`

I don't have any CSS on the page,  it's pretty bare bones at the moment

-Thank you

**Comment by negomi** [comment]
Ah yep, you won't see anything if you haven't added styles yet.

Try adding the demo ones:
```javascript
var styles = {
  bmBurgerButton: {
    position: 'fixed',
    width: '36px',
    height: '30px',
    left: '36px',
    top: '36px'
  },
  bmBurgerBars: {
    background: '#373a47'
  },
  bmCrossButton: {
    height: '24px',
    width: '24px'
  },
  bmCross: {
    background: '#bdc3c7'
  },
  bmMenu: {
    background: '#373a47',
    padding: '2.5em 1.5em 0',
    fontSize: '1.15em'
  },
  bmMorphShape: {
    fill: '#373a47'
  },
  bmItemList: {
    color: '#b8b7ad',
    padding: '0.8em'
  },
  bmOverlay: {
    background: 'rgba(0, 0, 0, 0.3)'
  }
}
```

Then add them to your menu like this:
```javascript
<Menu styles={ styles } />
```

**Comment by dfunaki** [comment]
Ok,  I'll try removing all my styles and try that again

**Comment by dfunaki** [comment]
Would you know why click on the right side of the browser also triggers the menu?

**Comment by negomi** [comment]
I'd guess it's because the button is spanning the whole width of the viewport because you haven't set a width for it yet. This should also be solved by adding the demo styles.

They're a good starting point to see how everything should work, and then you can tweak things to get it looking how you want.

**Comment by dfunaki** [comment]
Ok  great,  thank you

**Comment by varunvenky99** [comment]
I had the same problem.Thank you so much :)
