### ISSUE TITLE
Problem with Firefox, React-Router, React-MDL

### ISSUE THREAD

**Issue by kakariko-village** [negomi/react-burger-menu#107]
Hi, thanks you for your awesome React Burger Menu, I really like it. However, today when i test my project in Firefox, it display blank page and got this error on console: "TypeError: CSS2Properties doesn't have an indexed property setter for '0'". I tried to apply Radium follow your guide: https://github.com/negomi/react-burger-menu/wiki/FAQ#why-doesnt-the-link-component-from-react-router-work

It only works if there's no element contain <RadiumLink className="menu-item"> but i want to put those menu-item inside <List> component of React-MDL and when i did that, the page back to blank.

My Project uses: ReactJS, React-Router, React-MDL. You can check my code with more details here: https://docs.google.com/document/d/1z9txInFy_HWE6IMHKEWiqJRr3HZHCSWMTgx5v2ZWcI8/edit?usp=sharing

One more thing, when i use "Push" animation, i cannot scroll my main content but i can scroll it with "slide".

**Comment by zenners** [comment]
Hey have you tried some of the solutions at #44?

Personally trying them myself. Haven't gotten it to work yet. Let me know how it goes for you

**Comment by kakariko-village** [comment]
Thank @zenners, I have tried Radium but it does not work. You can read my google doc for more details

**Comment by wlingke** [comment]
@kakariko-village try my solution on #44

**Comment by negomi** [comment]
Hi @kakariko-village, you would need to wrap all custom elements in Radium for this to work (including the `<List>` component of React-MDL). @wlingke's solution will also work.

Sorry the docs on this were incomplete - both solutions are now in the FAQs: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-use-custom-components-inside-my-menu-but-this-breaks-firefox

**Comment by a-pandey** [comment]
Page blinks like normal website do in firefox. 

This video will explain.
https://youtu.be/FFq9u7QlXYk
