### ISSUE TITLE
Modify Push effect

### ISSUE THREAD

**Issue by kakariko-village** [negomi/react-burger-menu#108]
Hi, i want to change the padding right of the page-wrap when menu was toggled with 'push'. I can do that by changing the push.js like this:

```
  pageWrap: function pageWrap(isOpen, width, right) {
    return {
      paddingRight: isOpen ? 0 : width+'px',
      transform: isOpen ? '' : right ? 'translate3d(-' + width + 'px, 0, 0)' : 'translate3d(' + width + 'px, 0, 0)',
      transition: 'all 0.5s'
    };
  },

```

Are there any other ways to adding more CSS to page wrap when menu was toggled without changing library file like that?

**Comment by negomi** [comment]
Hi @kakariko-village,

The menu doesn't provide a specific way to style the page-wrap element, as it's outside the menu itself.

One way you could do this is [detect the menu state change](https://github.com/negomi/react-burger-menu#state-change) and then toggle a class on your page-wrap element in the callback function.
