### ISSUE TITLE
Nav bar?

### ISSUE THREAD

**Issue by MMRandy** [negomi/react-burger-menu#11]
This is nice!  I'd like to use this as the main nav for a hybrid app that must fit both phone and tablet form factors.  On the tablet tho, I'd like to have a NavBar on the slide element that is always visible even when the menu is retracted.  Any suggestions for best way to handle?

Thanks again, this looks nice :)

**Comment by MMRandy** [comment]
This might be a feature request :)

**Comment by negomi** [comment]
Hey @MMRandy! I'm not entirely sure what you're getting at - do you mean you want something on the sidebar that doesn't get retracted with it?

**Comment by MMRandy** [comment]
Almost.  For out tablet design, we like to have a NavBar (sidebar) accessible at all times, even after the retraction of the drawer menu.  But when the drawer opens, the NavBar should move outwards with it.  Upon retraction, the drawer menu completely retracts, but only up to the point of the NavBar.  Then on mobile, the NavBar is not present at all due to screen real estate obviously.  Ideally, this would be a property that you set, allowing you turn turn it on or off.  The NarBar itself would be styled with whatever.

I sort of played around with this and was able to somwhat mock this up by playing arounf with the menuWrap settings and doing something like the following:

```
        menuWrap: function menuWrap(isOpen) {
            return (0, _reactKitAppendVendorPrefix2['default'])({
                position: 'fixed',
                zIndex: 2,
                width: 350,
                height: '100%',
                transform: isOpen ? 'translate3d(0, 0, 0)' : 'translate3d(-300px, 0, 0)',
                transition: isOpen ? 'transform 0.4s 0s' : 'transform 0.4s'
            });
        },
```

Changed the width to 350 from 300, then retracted the translate to only 300px. I'm sure this is not ideal, but it at least demonstrates the concept.

Thanks again for sharing your component!

**Comment by negomi** [comment]
Ahh, I think I understand. I've made a demo on this branch: https://github.com/negomi/react-burger-menu/tree/navbar-extension

It should be pretty simple to fork and extend from this point. Let me know if that's not what you mean :)

**Comment by MMRandy** [comment]
Yes!  That is exactly what I was talking about :)  Thanks much for your time as I'm sure you're busy.  I think this is a valuable addition to your component.  Thanks again :)

**Comment by negomi** [comment]
Excellent! Glad I could help. I'm going to close this issue for now but I might consider adding it to a future release :)
