### ISSUE TITLE
Including inputs in menu.

### ISSUE THREAD

**Issue by mikemerritt** [negomi/react-burger-menu#110]
I have a search form that I have to include in the burger menu. The problem is that it automatically closes on keypress. Is there a setting for this or an easy way to override this behavior?

I've tracked this down to isOpen={false} Is there any easy way to close by default ONLY when navigating to another page?

**Comment by negomi** [comment]
Hi @mikemerritt,

If you're hardcoding the `false` in `isOpen={false}`, and a keypress in your search form is causing a re-render, then the menu will close on each keypress.

The way to get around this would be to pass a variable to `isOpen` instead, and only set it to false when you actually want the menu to close (e.g. on click of a navigation link). Something like this:

```javascript
export default React.createClass({
  navigateToPage(e) {
    e.preventDefault()
    
    // Close the menu
    this.setState({
      menuOpen: false
    })

    // Navigation code goes here
    // ...
  }

  render() {
    return (
      <Menu isOpen={this.state.menuOpen}>
        <input type='text' />
        <a onClick={this.navigateToPage} href='/a-page'>A page</a>
      </Menu>
    );
  }
});
```
