### ISSUE TITLE
Disable hover effect on .bm-menu-button.

### ISSUE THREAD

**Issue by anarchyrucks** [negomi/react-burger-menu#113]
Hi, I can't seem to be able to disable the burger menu hover effect.

**Comment by 2easy** [comment]
Hi, had the same problem. You can bypass this by setting styles for bmBurgerBars like this (if you're setting them by javascript - similarly in css):

```
var styles = {
  bmBurgerBars: {
    opacity: '1 !important'
  }
}
```

**Comment by anarchyrucks** [comment]
thanks!
