### ISSUE TITLE
Elastic Menu Cutoff when <Menu right />

### ISSUE THREAD

**Issue by radiovisual** [negomi/react-burger-menu#115]
The `<Menu right />` option on the `Elastic` setting seems to be forcing the menu items to be cutoff.

Here is a screenshot of your [Demo App](http://negomi.github.io/react-burger-menu/) in Chrome `Version 54.0.2840.98 (64-bit)` (MacOS Sierra 10.12):

![image](https://cloud.githubusercontent.com/assets/5614571/20838440/86b8c834-b8a0-11e6-9ce7-83caa6f33cd0.png)

and here it is again in Firefox `Version 50.0` (MacOS Sierra 10.12):

![image](https://cloud.githubusercontent.com/assets/5614571/20838591/30c90528-b8a1-11e6-8d16-669fb975172e.png)

It works as expected when the menu item opens up on the left side of the screen.

**Comment by negomi** [comment]
Fixed in v1.10.10 - thanks for the report :)
