### ISSUE TITLE
React 0.13.3 not supported

### ISSUE THREAD

**Issue by razagill** [negomi/react-burger-menu#12]
Hi,
I'm using ```react@0.13.3``` and upon installing I'm getting the following error:
```
Peer react-burger-menu@1.2.0 wants react@0.14.0-rc1
```
Is react@0.13.3 not supported and you plan to only support ```react@0.14.*``` and forward versions?

**Comment by negomi** [comment]
Hey @razagill, React 0.14 introduced some breaking changes so it's not backwards compatible.

To use react-burger-menu with React 0.13.3, just install the previous version:

```
npm install react-burger-menu@1.1.6 --save
```

I'll update the docs with this info, thanks for pointing it out!

**Comment by razagill** [comment]
@negomi Cool, that works.
