### ISSUE TITLE
RTL Styling Support

### ISSUE THREAD

**Issue by kikoanis** [negomi/react-burger-menu#120]
Is there any chance that you can extract all styling in a separate file so that we can apply RTL conversion on it. 

BTW, thank you for putting this together. It's been awesome for me so far.

**Comment by negomi** [comment]
Hi @kikoanis, glad you like the component :)

Which styling do you mean? The content styling is up to you anyway, and the animation styling has right and left versions, but the animations are independent of content direction, so RTL content would work with either.

**Comment by kikoanis** [comment]
Not sure if the animation staring from right is what I am looking for. 
As you may know, the RTL UI has two aspects: 
1.  RTL CSS which is achieved through converting CSS to be RTL compliance (everything has to flow from right to left). This can be done using an RTL tool which is not complicated if you have the CSS available to you not embedded in a script.
2. Direction by changing the direction of html elements from LTR (default) to RTL. This is usually done on the main HTML element
                   ```<HTML dir='rtl'>```

and this is where this component fails. once we change the direction from LTR to RTL, the interface gets sort of corrupted.  

To explain the matter more. I will try to put together an example that you can play with to see the real issue. May be after the holidays.

Happy holidays

**Comment by negomi** [comment]
Ooh I see! I actually haven't worked on RTL layouts at all, so I was under the impression it was just adapting CSS so that RTL text would flow correctly.

I would love to look into the best way of supporting what you're talking about.

The problem with pulling the component styles out into stylesheets is that a lot of the styles are composed/dynamically generated/configurable through props, so all this functionality would be unavailable. I will mark it as an enhancement though :)

**Comment by kikoanis** [comment]
I can confirm that the right property works fine with RTL. The only issue is that you cannot use the menu with out it in RTL mode. That is if you decided to get the menu appears from left in RTL direction mode.
Of course, you need some tweaking to the some of the menu properties specially the cross button that closes the the menu. Other than that it works fine.

Closing the issue....

**Comment by kikoanis** [comment]
@ImanMh yes it works fine out of the box
