### ISSUE TITLE
Radium version is not up to date

### ISSUE THREAD

**Issue by matankastel** [negomi/react-burger-menu#121]
By using Radium v0.18.0 there is a problem, a newer version (v0.18.1)

Need to change line on package JSON file:

Radium v0.18.0  ---> Radium v0.18.1
 "radium": "^0.18.0" ---> "radium": "^0.18.1"

Changes based on Radium git:

This is due to changes in ES2015 , 
_"This project is deprecated for users of Babel v6.13+. It will still be maintained for users of earlier Babel versions. "_
See https://www.npmjs.com/package/babel-preset-es2015-loose

Fix needed: 
See https://github.com/FormidableLabs/radium/blob/master/.babelrc
{
  .....
  "presets": [
    **["es2015", { "loose": true }],**
    "stage-1",
    "react"
  ]
}

**Comment by negomi** [comment]
Fixed in v1.10.11
