### ISSUE TITLE
Custom className

### ISSUE THREAD

**Issue by wlingke** [negomi/react-burger-menu#124]
It would be nice if we could do something like:

```
<Menu className="blah">
    {stuff}
</Menu>
```

and render:

```
<div class="bm-menu-wrap blah" ....>
```

This is useful for those of us who prefer css modules over radium and don't want to modify the global classes you offer (for ex. if I am creating two types of menus).

**Comment by wlingke** [comment]
Obviously current workaround is just <div className="blah"><Menu /></div>, but should be really easy to accept a classname :)

**Comment by jontelm** [comment]
#102 This is maybe related to having a separated css file.

**Comment by negomi** [comment]
Added in v1.10.11
