### ISSUE TITLE
add push-shrink effect 

### ISSUE THREAD

**Issue by radziksh** [negomi/react-burger-menu#125]
I want to modify push effect in such way that right side of the container did not go off the screen. But problem in strange shaking (Chrome) of the container's right side during the animation. So I just set transition to `0s` My code:

     pageWrap: function pageWrap(isOpen, width, right) {
         return {
             transform: isOpen ? '' : right ? 'translate3d(-' + width + 'px, 0, 0)' : 'translate3d(' + width + 'px, 0, 0)',
             width: isOpen ? '100%' : 'calc(100% - ' + width + 'px)',
             transition: 'all 0s'
        };
    },

I'm not an expert in css animations, maybe I missed something? Why I have this shaking?

**ps:**

my particular case seems to be quite common, it may be worth adding this animation?

**Comment by negomi** [comment]
Hi @radziksh,

A few people have expressed interest in a responsive menu, or one that doesn't fully disappear off the edge off the screen (see https://github.com/negomi/react-burger-menu/issues/39 too).

I would like to add this as an enhancement, but just need to figure out the most flexible way to do it.

I haven't merged this yet, but https://github.com/negomi/react-burger-menu/pull/122 looks like it might do what you need?

**Comment by jquintozamora** [comment]
Hi @negomi , 
First of all, thank you very much for sharing this component. It saved my day.
I used it as a Panel (to show and hide configurations properties). I need to do some adjustments like this:

```js
pageWrap: (isOpen, width, right) => {
        return {
            '-webkit-transition': 'width 0.5s',
            transition: 'width 0.5s',
            width: isOpen ? '100%' : 'calc(100% - ' + width + 'px)'
        };
    },
```

And imported the menu like that (typescript): 
```js
import * as Menu from "react-burger-menu/lib/menuFactory.js";
```

Regarding React Responsive Menu, I did something few months ago, just in case it helps you:
https://github.com/jquintozamora/react-responsive-menu-component

Regards!

**Comment by juliolugo96** [comment]
@negomi Hi!, Your sidebar is awesome! What a wonderful component you've done!

May I ask if it's possible to add this functionality (push-shrink) to your sidebar soon? I think it'd be amazing to have this.

Thank you!
