### ISSUE TITLE
React v0.14 support

### ISSUE THREAD

**Issue by amitrai99** [negomi/react-burger-menu#127]
The dependency for this component seems to be `"react": "^15.4.1",`. Is there a version that I can use with react 0.14?

I know that the documentation states that I can use this in both the versions of react but was not sure if having two versions of react in the same codebase causes issues.

**Comment by negomi** [comment]
Hi @amitrai99,

That's the version listed in `devDependencies`, but the range in `peerDependencies` is `">=0.14.0 <16.0.0"`, which means you should be fine to use this if you're using React 0.14.

Let me know if anything's not working as expected :)
