### ISSUE TITLE
imports issue in webpack

### ISSUE THREAD

**Issue by razagill** [negomi/react-burger-menu#13]
When using webpack the component gives the following error:
```
WARNING in ./~/react-burger-menu/lib/menuFactory.js
Module not found: Error: Cannot resolve module 'imports' in /project/node_modules/react-burger-menu/lib
 @ ./~/react-burger-menu/lib/menuFactory.js 24:9-87
```
I think it's because of the `snap.svg` workaround. I think it's because webpack couldn't find that loader in my project so I just had to add `imports-loader` in my devDependencies and it worked. Not sure if anyone else came across something similar.

**Comment by negomi** [comment]
Ah interesting, maybe imports-loader needs to be in your devDependencies rather than the component's. I'll look into it and update the docs in the next release. Thanks again!

**Comment by razagill** [comment]
Yup, apparently webpack needs to have it in the project to process that kind of imports.
No problem, thanks for the awesome component :)

**Comment by negomi** [comment]
Fixed here: https://github.com/negomi/react-burger-menu/commit/bd07561efe993a5dcd1afe19b60f730856168882
