### ISSUE TITLE
adding ally roles for Menu

### ISSUE THREAD

**Issue by hariKarthic** [negomi/react-burger-menu#130]
It would be great if we can throw in some `role`  attributes to the menu . Will score better on **accessibility**

Excellent widget otherwise

**Comment by negomi** [comment]
Good idea, thanks @hariKarthic!

**Comment by Bintehassan** [comment]
Is there anyway to manage focus on the hamburger menu button?

**Comment by LorhanSohaky** [comment]
Any news?

**Comment by LorhanSohaky** [comment]
Reopen

**Comment by sjarva** [comment]
I'm working on a PR to fix this and #404
Will hopefully submit it during October (and Hacktoberfest 🎉) 😄

**Comment by negomi** [comment]
Fixed in `2.9.0`
