### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 740): SyntaxError: TransformError:

### ISSUE THREAD

**Issue by ShailajaV** [negomi/react-burger-menu#134]
After installing 'react-burger-menu' getting the following error.

transformed 692/706 (98%)(node:16260) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 740): SyntaxError: TransformError: path\node_modules\radium\lib\index.js: Unknown plugin "add-module-exports" specified in "path\\node_modules\\radium\\.babelrc" at 0, attempted to resolve relative to path\\node_modules\\radium"

**Comment by negomi** [comment]
Hi @ShailajaV, I would need a bit more information to tell what's wrong:
* Are you running react-burger-menu locally or including it in a project?
* What version are you using?
* Where are you seeing this error, and is there any other output?

**Comment by negomi** [comment]
Going to close for now as no response - this also looks like an error due to Radium, which was removed in v2.0.0. Feel free to file another issue if you're still having problems :)
