### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined at _inherits (style.js:25)

### ISSUE THREAD

**Issue by shirlyf** [negomi/react-burger-menu#141]
Hello there Negomi,

Recently I have added react-burger-menu to my project, at first locally, it worked perfectly and after we merge my code with the master repo, this error showed up and tests were failing,
when trying to resolve this it got worse =/

it seems the issue occurs in Radium.
Do you have any idea what is the cause of this?
(react  15.1.0, react-router: 2.4.1)

Thanks in advance,
 -Shirly

**Comment by ahoym** [comment]
@shirlyf, I tracked the issue down here: https://github.com/negomi/react-burger-menu/issues/139

Issue on radium here: https://github.com/FormidableLabs/radium/issues/885

**Comment by ansmonjol** [comment]
+1

**Comment by negomi** [comment]
I believe this should be fixed in v1.12.0 - please let me know if the issue still exists!
