### ISSUE TITLE
When I write 'npm install' and then 'npm start' after cloning the project, it gives an error and doesn't start localhost

### ISSUE THREAD

**Issue by burakuluu** [negomi/react-burger-menu#143]
I cloned the project on my local and tried to start the project on my localhost but I faced an error which said;

```
npm ERR! Failed at the react-burger-menu@1.10.14 start script 'gulp dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-burger-menu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-burger-menu
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-burger-menu
npm ERR! There is likely additional logging output above.
```

Also when I write 'gulp dev' to my command line, it says;
```
The term 'gulp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try aga
in.
At line:1 char:5
+ gulp <<<<  dev
    + CategoryInfo          : ObjectNotFound: (gulp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I'm new to React and really need help to import Github projects on my local. 
Please show me the path to start the project.

Thanks

**Comment by burakuluu** [comment]
I resolved the issue by installing 'gulp' and 'react-component-gulp-tasks' by 'npm install gulp' and 'npm install react-component-gulp-tasks'

**Comment by negomi** [comment]
Glad you got it working - it sounds like your `npm install` didn't succeed the first time.

**Comment by burakuluu** [comment]
Yes, I run **npm install** before those commands but it didn't work as I couldn't understand why.

**Comment by leadiville** [comment]
npm install should be done in the directory where you have your package.json file. In case its a full stack app and you have maybe client and server directories. Just in case. ; )
