### ISSUE TITLE
React 15.5.0 warnings

### ISSUE THREAD

**Issue by anna-kartynnik** [negomi/react-burger-menu#147]
After updating react to 15.5.0 I can see the following warnings in the browser console

    Warning: Accessing PropTypes via the main React package is deprecated. 
    Use the prop-types package from npm instead.
    
    printWarning	    @ warning.js:36
    warning	            @ warning.js:60
    get                 @ React.js:95
    (anonymous)	    @ style.js:93
    (anonymous)	    @ index.js:15
    (anonymous)	    @ menuFactory.js:17
    (anonymous)	    @ slide.js:9
    (anonymous)	    @ BurgerMenu.js:7

and

    Warning: A Component: React.createClass is deprecated and will be removed in version 16. 
    Use plain JavaScript classes instead. If you're not yet ready to migrate, 
    create-react-class is available on npm as a drop-in replacement.

    printWarning	     @ warning.js:36
    warning	             @ warning.js:60
    get	             @ React.js:95
    (anonymous)	     @ style.js:93
    (anonymous)	     @ index.js:15
    (anonymous)	     @ menuFactory.js:17
    (anonymous)	     @ slide.js:9
    (anonymous)	     @ BurgerMenu.js:7

More about [changes in 15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by negomi** [comment]
Hey, thanks for reporting!

Although react-burger-menu has now removed its own references to `React.PropTypes` and `React.createClass`, a dependency on Radium is unfortunately still causing these warnings to show.

They have an issue open (https://github.com/FormidableLabs/radium/issues/895) but to continue supporting React 0.14.x, we're also currently locked to Radium 0.18.1 (see https://github.com/FormidableLabs/radium/issues/885).

I will think about the best way to move forward. It might be time to lose the Radium dependency.

**Comment by negomi** [comment]
Fixed in v2.0.0 (removed Radium dependency 🎉 )
