### ISSUE TITLE
React es6 burger-menu animation

### ISSUE THREAD

**Issue by marshall86** [negomi/react-burger-menu#148]
Hi thanks for your repo, it was what I was looking for! I have a problem, I'm still a newbie with React.. 
This is my menu.js file:

```
import React, { Component } from 'react';
import { stack as Menu }    from 'react-burger-menu';
import { Link, IndexLink, Route }  from 'react-router';
import classNames           from 'classnames';
import Radium               from 'radium';
import '../assets/scss/menu.scss';

const RadiumLink = Radium(Link);
const RadiumIndexLink = Radium(IndexLink);

import Home from '../modules/Home';
import About from '../modules/About';
import Contact from '../modules/Contact';

export default class List extends Component {
    constructor(props, context){
        super(props, context);
        this.state = { isOpen: false };
        this.handleClick = this.handleClick.bind(this);
    }
    componentDidMount() {}
    componentWillUnmount() {}
    handleClick(event) {
        event.preventDefault();
        this.setState({isOpen: false});
    }
    render() {
        return (
            <Menu isOpen={this.state.isOpen} right>
                <RadiumLink onClick={this.handleClick} className="menu-item" to="/home"     activeClassName="active">Home</RadiumLink>
                <RadiumLink onClick={this.handleClick} className="menu-item" to="/contact"  activeClassName="active">Contact</RadiumLink>
                <RadiumLink onClick={this.handleClick} className="menu-item" to="/about"    activeClassName="active">About</RadiumLink>
            </Menu>
        );
    }
}
```

I would change the default animation to "bubble" and I would like to make the RadiumLink works.
For example my about.js file is :

import React from 'react'

```
export default React.createClass({
    render() {
        return <div>About</div>
    }
})
```

Unfortunately the routing doesn't works, if I click on About or one of the other links nothing happen, could you help me?

Thanks a lot!

**Comment by negomi** [comment]
Hi @marshall86,

There have been a couple of cases of react-router not working. I have just released v2.0.0, which removes the need to wrap Link in Radium.

Could you try upgrading and see if the problem still exists?

**Comment by marshall86** [comment]
Thanks for your support but unfortunately I am not enable to make the routing works yet

This is my code:

[export default class List extends Component {
    constructor(props, context){
        super(props, context);
        this.state       = { isOpen: false };
        this.handleClick = this.handleClick.bind(this);
    }
    componentDidMount() {}
    componentWillUnmount() {}
    handleClick(event) {
        event.preventDefault();
        this.setState({isOpen: false});
    }
    render() {
        return (
            <Menu isOpen={this.state.isOpen} right>
                <a id="home"    onClick={this.handleClick} className="menu-item" href="/">Home</a>
                <a id="about"   onClick={this.handleClick} className="menu-item" href="/about">About</a>
                <a id="contact" onClick={this.handleClick} className="menu-item" href="/contact">Contact</a>
                <a id="contact" onClick={this.handleClick} className="menu-item" href="/legals">Legals</a>
                <a id="contact" onClick={this.handleClick} className="menu-item" href="/skills">Skills</a>
            </Menu>
        );
    }
}](url)

I think the better way is to implements the routing in this way:

[<Router history={browserHistory}>
                <Route onClick={this.handleClick} className="menu-item" path="/" component={Home}/>
                <Route onClick={this.handleClick} className="menu-item" path="/about" component={About}/>
                <Route onClick={this.handleClick} className="menu-item" path="/contact" component={Contact}/>
            </Router>](url)

Could you fix this issue? thanks a lot again

**Comment by marshall86** [comment]
My fault, sorry, I found the problem, this is the right code:

```
<Menu isOpen={this.state.isOpen} right>
                <li><IndexLink to="/"   onClick={this.handleClick} className="menu-item" activeClassName="active">Home</IndexLink></li>
                <li><Link to="/about"   onClick={this.handleClick} className="menu-item" activeClassName="active">About</Link></li>
                <li><Link to="/contact" onClick={this.handleClick} className="menu-item" activeClassName="active">Contact</Link></li>
            </Menu>
```

I made a mistake in my Router configuration. Thanks a lot

**Comment by negomi** [comment]
Glad you got it working 👍
