### ISSUE TITLE
Unable to resolve module `react-dom`

### ISSUE THREAD

**Issue by marianaMarshaL** [negomi/react-burger-menu#149]
Hi,

When i try to install react burger menu using "npm install --save react-burger-menu" and try to running the project, i got this error:

error: bundling: UnableToResolveError: Unable to resolve module `react-dom` from `/Users/nana/Project/digital_onboarding/photon_digital_onboarding_widget/node_modules/react-burger-menu/lib/menuFactory.js`: Module does not exist in the module map or in these directories:
  /Users/nana/Project/digital_onboarding/photon_digital_onboarding_widget/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.
    at p.catch.error (/Users/nana/Project/digital_onboarding/photon_digital_onboarding_widget/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:366:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `webapp/resources/widget/index/overviewIndex.js`  99.1% (421/423), failed.

I have tried the three steps and the issued still happen.

**Comment by marianaMarshaL** [comment]
I have tried the three steps and the issued still happened

**Comment by negomi** [comment]
Have you installed the `react-dom` package?

**Comment by marianaMarshaL** [comment]
yes i did? did the react-burger-menu only working on specific react native version?

**Comment by negomi** [comment]
Ahh, are you trying to use this with React Native? This isn't for React Native, just web projects at the moment. That would be why the `react-dom` package isn't loading :)

**Comment by marianaMarshaL** [comment]
is there any way to implement this with react native?

**Comment by negomi** [comment]
Not currently, I'm afraid. It looks like there are a few similar projects for React Native though:
* https://github.com/ilansas/react-native-navigation-drawer
* https://github.com/root-two/react-native-drawer
* https://github.com/react-native-community/react-native-side-menu
Best of luck!

**Comment by marianaMarshaL** [comment]
thanks for your help :)
