### ISSUE TITLE
Is there a way to control the sizing design of the menubar? Eg. Width

### ISSUE THREAD

**Issue by iDVB** [negomi/react-burger-menu#15]
We love the menu, but we only need a bar that is like 150px or less wide and would only house icons.

Is there a way to customize the width without forking?

**Comment by negomi** [comment]
Hey! Unfortunately not at the moment. Depending on which animation style you want, it's probably not a very big change if you do decide to fork it.

I'll consider making the width specifiable as an option in a future release :)

**Comment by negomi** [comment]
As of [v1.3.0](https://github.com/negomi/react-burger-menu/releases/tag/v1.3.0), you can customize the width. See https://github.com/negomi/react-burger-menu#width :)
