### ISSUE TITLE
How I can implement exactly the Open state?

### ISSUE THREAD

**Issue by EmmanuelSkapple** [negomi/react-burger-menu#150]
Hi first, Thanks for you repo :D is so nice. I can't implement the Open state or rather I do not know, is confusing for me :D, 
I've been trying for 3 hours without results.

You cant help me? 

Pliss I a noob XD.

this is my class:

![image](https://cloud.githubusercontent.com/assets/17431888/25115093/305068b4-23c9-11e7-98d6-d3bb01ec8ad4.png)

**Comment by EmmanuelSkapple** [comment]
sorry for mi english XD

**Comment by negomi** [comment]
Hi @EmmanuelSkapple, sorry you're having trouble :)

In the most basic case, the menu handles its own open state, so you don't need to do anything. Have you added styles yet? If not, you won't see the burger icon to click on (and therefore won't be able to open the menu). See https://github.com/negomi/react-burger-menu#styling for the example styles to get you started.

Please let me know if you're still having issues!

**Comment by EmmanuelSkapple** [comment]
Hi negomi,
thanks for answering, yes in fact I have the styles
![image](https://cloud.githubusercontent.com/assets/17431888/25185294/95d3f498-24e2-11e7-88a8-e57d0ac41972.png)
but, When I press an item Is not hidden the menu, this is my problem XD, I do not know how to do it I read the state change section but I do not know how to implement it jejeje 😃

**Comment by negomi** [comment]
Ah ok. So you would need to do something like this:
```js
class ParentComponent extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      menuOpen: false
    }
  }

  handleStateChange (state) {
    this.setState({menuOpen: state.isOpen})  
  }
  
  handleItemClick () {
    this.setState({menuOpen: false})
  }

  render () {
    return (
      <Menu isOpen={this.state.menuOpen} onStateChange={this.handleStateChange}>
        <a onClick={() => this.handleItemClick()}>Home</a>
        <a onClick={() => this.handleItemClick()}>About</a>
        <a onClick={() => this.handleItemClick()}>Contact</a>
        <a onClick={() => this.handleItemClick()}>Settings</a>
      </Menu>
    )
  }
}
```

**Comment by EmmanuelSkapple** [comment]
Wow it is, thanks so much 😄

**Comment by pesterhazy** [comment]
It also took me a while to wrap my head around this, especially the fact that the component keeps its local state. This could be a great addition to the frontpage readme, as I'm guessing most people will need this eventually?
