### ISSUE TITLE
Works not smoothly when do a lot of updates on the page (on other parts of page)

### ISSUE THREAD

**Issue by ophite** [negomi/react-burger-menu#151]

**Comment by negomi** [comment]
Hi @ophite, sorry it's not working smoothly for you, but I would need some more information to determine if this is an issue with this component.

I'm curious what other updates you're doing at the same time the menu is opening/closing (I'm assuming you mean the animation isn't smooth), and whether they need to happen at that time? The animations are just CSS transitions, so aside from waiting for the menu to finish animating before performing your updates, I'm not sure there's actually much we can do about this.

Feel free to supply more explanation/screenshots/ideally a small repo which reproduces this problem and I will happily take a look.

Closing for now as not enough detail to be actionable.

**Comment by ophite** [comment]
Thanx for reply, i think u are right - need to wait finish updates and then do animation
