### ISSUE TITLE
large dependancy snapsvg

### ISSUE THREAD

**Issue by andrewmclagan** [negomi/react-burger-menu#152]
Currently webpack-analyzer throws up `snapsvg-cjs` as being a very large dependancy

245 KiB

Are there any alternatives to this? as this seems excessive.

**Comment by negomi** [comment]
Hi @andrewmclagan, yep, I'm aware of this issue :/

Aside from replacing the Snap.svg dependency with another library, I don't currently know of a way to avoid this, and I'm afraid I don't have much time to work on it at the moment.

I'd accept a PR if anyone else has any suggestions.

**Comment by andrewmclagan** [comment]
Cool, i will take a look when i have the time

**Comment by andrewmclagan** [comment]
@negomi Before I write up a PR can you give me a brief overview of what snap-svg is used for? Sorry, we roll our own buttons controlled by redux state. I'm assuming its used for the burger-menu buttons?

**Comment by andrewmclagan** [comment]
@negomi 

Actually I just did a brief investigation into the codebase and I realised that only a few menus actually use snap-svg. 

You also correctly export the full path structure of the library.

There for those rollup/webpack users can cherry pick the menu they need without importing those they dont.

e.g.

````javascript
import BurgerMenu from 'react-burger-menu/lib/menus/push';
````

For us this saved 80Kb even after GZip ... thats impressive. 

Perhaps this should be noted in the docs.

**Comment by negomi** [comment]
Oh sure, if you're not actually using one of the menus with SVG animation then that will work fine :)

I'll add it to the docs. Hopefully that will be enough to solve this issue for most people (definitely easier than finding a new SVG library) - I think the SVG-animated menus are the less popular ones anyway.

**Comment by andrewmclagan** [comment]
Awesome, its a pretty nice thing to doc. 

Not all packages export in this manner, its great.

There is a big push over at ImmutableJS to do that just now:

https://github.com/facebook/immutable-js/issues/1190
