### ISSUE TITLE
How to make the sidebar permanent

### ISSUE THREAD

**Issue by danielo515** [negomi/react-burger-menu#154]
Hello,

I was wondering if there is a way to allow the sidebar to be permanent on wide screens. 

Regards

**Comment by negomi** [comment]
Hi @danielo515, not officially, but it's possible to do with a combination of the `isOpen` and `noOverlay` props (see https://github.com/negomi/react-burger-menu/issues/39#issuecomment-263148475)

That issue has been open for a while now, and I may implement it as a feature at some point, just haven't had the time yet :)

Hope that helps!
