### ISSUE TITLE
Ability to give width of menu as %.

### ISSUE THREAD

**Issue by mouli-preddy** [negomi/react-burger-menu#156]
Ability to give width of menu as %. This requires the width to accept String inputs along with int.
Already tried it and except for a warning, this works perfectly. So ideally should not be a problem in implementing it.

**UseCase:** I need a menu that covers 50% of the screen and readjusts child elements as per screen dimensions. Thus cannot use static int values.

**Comment by negomi** [comment]
Good idea - added in v2.0.1 :)
