### ISSUE TITLE
Material UI debugging

### ISSUE THREAD

**Issue by mmarovich** [negomi/react-burger-menu#157]
Here is my repo for problems described below: https://github.com/mmarovich/trapped

I am currently learning how to use Material UI, so I have integrated a simple Appbar component into my project.  I have injected the react-burger-menu into the Appbar component using the iconElementLeft prop.
```
import React from 'react';
import AppBar from 'material-ui/AppBar';
import Sidebar from './Sidebar';



const Header = () => (
  <AppBar
    title="Title"
    iconClassNameRight="muidocs-icon-navigation-expand-more"
    iconElementLeft={<Sidebar />}
  />
);

export default Header;
```
This works, Buuuuuuuuuut... : )
Some quirky behaviors happen:

1) The outer wrapper doesn't seem to have any effect on the header.  The only explanation I can see for this is that it has a fixed positioning, but I don't know for sure.
2) It looks like there is some sort of margin above the sidebar menu.  I tried margin-top of 0 and padding 0, but this doesn't seem to fix it.
3) The burger-menu seems to be offset to the right, so that it sticks out even when it's closed.

I can tell that it's plugged in fine, but there are some css styles to deal with and I'm not exactly sure where the problems are coming from and which components need tweaking.

**Comment by mmarovich** [comment]
Okay, so.  I have realized the error of my ways, haha.

The whole reason I did it this way was because if I put the Sidebar where it's normally supposed to go:
```
class App extends Component {
  render() {
    return (
      <Router>
        <div id="outer-container" className="App">
          <Sidebar />
            <main id="page-wrap">
              <Header />
              <Route path="/" exact component={Home} />
              <Route path="/observation1" component={Observation1} />
              <Route path="/observation2" component={Observation2} />
            </main>
        </div>
      </Router>
    );
  }
}
```
If I do this, then the menu will be underneath the material-ui header.  This is because the MUI AppBar, by default, has a z-index of 1100.  I needed to go in and set it to 0.  After that, everything works as normal.

**Comment by negomi** [comment]
Aha! Glad you figured it out :)
