### ISSUE TITLE
Toggle menu with burger icon

### ISSUE THREAD

**Issue by maxrosecollins** [negomi/react-burger-menu#159]
How can I attach an event to the burger icon so I can toggle the menu with it?

**Comment by negomi** [comment]
Hey @maxrosecollins, what's your use case? By default, the component is designed to handle all its toggling internally, so you shouldn't need to attach any events just to make it work.

If you're trying to do something more complex, feel free to go into more detail and I'll see if I can help :)

**Comment by maxrosecollins** [comment]
I wanted to hide the CrossIcon and use the burger icon to open and close the menu.

**Comment by negomi** [comment]
The burger will do both. If you position it so it's visible when the menu is open (and hide the overlay with the `noOverlay` prop), then it will work. This is the demo page modified to demonstrate:

![may 24 2017 8-35 pm](https://cloud.githubusercontent.com/assets/3727684/26435095/a46df4ae-40c1-11e7-96d2-a49349b45d33.gif)
Is that what you mean?

**Comment by maxrosecollins** [comment]
Hmmmm very strange, it's working now.

Another question, is it possible to move the burger icon into the `page-wrap` div, so it moves with it?

**Comment by negomi** [comment]
Not directly, though you have a few options for ways to achieve that:
1. Reposition the burger icon on open/close via styling. For that, you would have to keep track of the menu state externally. It would look something like this:
```javascript
class ParentComponent extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      menuOpen: false
    }
  }

  handleStateChange (state) {
    this.setState({menuOpen: state.isOpen})  
  }
  
  handleItemClick () {
    this.setState({menuOpen: false})
  }

  render () {
    // Set the burger icon position based on the open state
    const styles = {
      bmBurgerButton: {
        left: this.state.menuOpen ? '336px' : '36px'
      }
    }
    return (
      <Menu onStateChange={this.handleStateChange} styles={styles}>
        <a onClick={() => this.handleItemClick()}>Home</a>
        <a onClick={() => this.handleItemClick()}>About</a>
        <a onClick={() => this.handleItemClick()}>Contact</a>
        <a onClick={() => this.handleItemClick()}>Settings</a>
      </Menu>
    )
  }
}
```

2. Hide the default burger icon, and create your own burger icon component to control the menu state; this way you can place it wherever you want. The code above demonstrates most of the same approach you would use for that (keeping track of the menu state in the parent component), and you'll want to use the [`isOpen`](https://github.com/negomi/react-burger-menu#open-state) prop.

3. Fork the component and move the `<BurgerIcon />` component where you want it.

Good luck! Going to close this as your original issue is resolved, but let me know if I can help any further.
