### ISSUE TITLE
Missing svg assets from snapsvg

### ISSUE THREAD

**Issue by ironng** [negomi/react-burger-menu#162]
Trying to use `react-burger-menu` with django leads to the following error when the backend is trying to collect all static assets:

`ValueError: The file '/node_modules/react-burger-menu/node_modules/snapsvg-cjs/node_modules/snapsvg/doc/img/search.svg' could not be found`

This might be an issue with the `snapsvg` package itself - I noticed that when you run `npm install` the `snapsvg/doc/img` does not get downloaded though it is referenced in the css for the docs and available in the original source repo on github. I will also open an issue with `snapsvg`.

**Comment by negomi** [comment]
Hey @ironng, I'm afraid I'm not very familiar with Django or its asset handling. It seems like that image is only required by Snap.svg's docs CSS, in which case it seems strange that it's being loaded at all when importing the package. I've not run across this problem before with any Node.js-based builds. Let me know if they have any useful advice!

**Comment by ironng** [comment]
@negomi Thanks for your response! I've raised an issue with Snap.svg. For now to get our Django environment to work with it we've just created own fork without references to Snap.svg
