### ISSUE TITLE
Cannot Apply style to the Menu

### ISSUE THREAD

**Issue by daveRanjan** [negomi/react-burger-menu#164]
I am not able to apply stylesheet to the menu, looks like some css styles are missing from what is shown in the example.

import slide from 'react-burger-menu';
import React from "react";
import '../style/SideMenu.css';

class SideMenu extends React.Component {
    render() {
        return (
            <slide>
                <a id="home" className="menu-item" href="/">Home</a>
                <a id="about" className="menu-item" href="/about">About</a>
                <a id="contact" className="menu-item" href="/contact">Contact</a>
                <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
            </slide>
        );
    }
}

export default SideMenu;

**Comment by negomi** [comment]
Hi @daveRanjan, from this snippet, it looks like you've imported the menu, but are not actually including it in the code yet.

Check out the code at the top of the usage section for an example of how to use it: https://github.com/negomi/react-burger-menu#usage
