### ISSUE TITLE
Burger icon hover

### ISSUE THREAD

**Issue by DeleurApps** [negomi/react-burger-menu#165]
If the menu component is rendered after the page is already loaded, and the mouse is over the spot where the burger icon will be, the hover state of the icon is inverted. It thinks that when the mouse is initially over the icon that its not hovering, and when the mouse leaves the icon it is hovering.

**Comment by negomi** [comment]
Hi @DeleurApps, thanks for the issue!

I actually struggled to reproduce this locally - I did just push a change which might've fixed it in v2.1.0 though. If not, let me know and I'll try to recreate it again.

**Comment by DeleurApps** [comment]
Yep that fixed it!
