### ISSUE TITLE
Open from top?

### ISSUE THREAD

**Issue by lightninglu10** [negomi/react-burger-menu#167]
So the react burger can open from the left and right, but can it also open from the top?

**Comment by negomi** [comment]
Hey @lightninglu10, not currently. It would be possible, but would involve adding a new animation.

I'll leave this here as an enhancement request for now. PRs would be welcome :)

**Comment by negomi** [comment]
Hi @mihailgaberov,

I responded in https://github.com/negomi/react-burger-menu/pull/198 explaining why it wasn't merged. If it's acceptable for you in its current state, you could always fork their branch and use it like that. 

I might be able to look at fixing it sometime, but work is pretty busy for me at the moment so I can't promise anything. Sorry about that.

**Comment by mihailgaberov** [comment]
Ho @negomi, 

Thank you for your answer. I will follow it up from there.

Cheers,
Mihail

**Comment by braco** [comment]
Is this issue dead?
