### ISSUE TITLE
Burger Button problems

### ISSUE THREAD

**Issue by aleablu** [negomi/react-burger-menu#169]
Hi,

I'm trying to use this awesome menu in my electron+react application, animations are working fine, but I can't get the burger button to work, the bars aren't visible and it extends to the whole body of the application, all the screen is a big invisible burger button! 

`import React from 'react';
import {Link,Route} from 'react-router-dom'
import {push as BurgerMenu} from 'react-burger-menu'
import Button from 'react-bootstrap'

import AllProjectsView from './allProjectsView.js'
import NewProject from './newProject.js'
import ProjectSelected from './prjctSelected'

export default class SideBarMenu extends React.Component{
    constructor(props){
        super(props)
    }
    componentDidMount(){
        this.state={
            isOpen : false
        };
    }
    isMenuOpen(state){
        return state.isOpen;
    }
    showMenu(){
        if(this.isMenuOpen()){
            this.setState({isOpen:false})
        }else{
            this.setState({isOpen:true})
        }
    }

    render() {
        let styles = {
            bmBurgerButton: {
                position: 'fixed',
                width: '36px',
                height: '30px',
                left: '36px',
                top: '36px'
            },
            bmBurgerBars: {
                background: '#373a47'
            },
            bmCrossButton: {
                height: '24px',
                width: '24px'
            },
            bmCross: {
                background: '#bdc3c7'
            },
            bmMenu: {
                background: '#fff63f',
                padding: '2.5em 1.5em 0',
                fontSize: '1.15em'
            },
            bmMorphShape: {
                fill: '#373a47'
            },
            bmItemList: {
                color: '#b8b7ad',
                padding: '0.8em'
            },
            bmOverlay: {
                background: 'rgba(0, 0, 0, 0.3)'
            }
        };
        return(
            <div id="outer-container">
                <BurgerMenu onStateChange={this.isMenuOpen} style={styles} pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" }>
                    <Link to="/allProjectsView" className="menu-item">All Projects</Link>
                    <Link to="/projectSelected" className="menu-item">Show Project</Link>
                    <Link to="/newProject" className="menu-item">New Project</Link>
                </BurgerMenu>
                <main id="page-wrap">
                        <Route path="/projectSelected" render={props => <ProjectSelected infos={some JSON things}/>}/>
                    <Route path="/allProjectsView" component={AllProjectsView}/>
                    <Route path="/newProject" component={NewProject}/>
                </main>
            </div>
        )
    }
};
`
All my routes are nested in #page-wrap div, and all the animations are working fine
Thank you for the help, really appreciate your work! :)

**Comment by darkship** [comment]
Hi,
<code>style={styles}</code> should be <code>styles={styles}</code>

**Comment by negomi** [comment]
Hi @aleablu, yep, @darkship got there before me ^

Feel free to reopen if you're still having issues :)
