### ISSUE TITLE
Warning: Invalid argument supplied to oneOfType, expected an instance of array.

### ISSUE THREAD

**Issue by gautier-lefebvre** [negomi/react-burger-menu#170]
There is a warning in the console when importing your package:
`Warning: Invalid argument supplied to oneOfType, expected an instance of array.`

It comes from this line (line 256 of menuFactory.js) ->
```js
bodyClassName: PropTypes.oneOfType([PropTypes.string, PropTypes.oneOfType(PropTypes.string)]),
```
I don't know what is the actual PropType you wanted to set, but I guess this fix would be enough
```js
bodyClassName: PropTypes.string,
```

**Comment by negomi** [comment]
Ugh, yeah, not sure what happened there...

Fixed in https://github.com/negomi/react-burger-menu/commit/deb6252e7ce82761e34be52017bb3b9cf282c35e

Thanks for reporting, @gautier-lefebvre! 👍
