### ISSUE TITLE
item on Hover

### ISSUE THREAD

**Issue by ssageghi** [negomi/react-burger-menu#171]
hi 
how can I change onHover style of items 
thanks

**Comment by negomi** [comment]
Hi @ssageghi, do you mean the items you pass to the menu?

They're just components, so you can apply CSS or inline styles to them as you would any other component.

Feel free to elaborate if I'm not understanding correctly :)

**Comment by ssageghi** [comment]
I mean menu item that a menu have

**Comment by negomi** [comment]
Does the above answer your question?

**Comment by ssageghi** [comment]
No
`var styles = {
  bmBurgerButton: {
    position: 'fixed',
    width: '36px',
    height: '30px',
    left: '36px',
    top: '36px'
  },
  bmBurgerBars: {
    background: '#373a47'
  },
  bmCrossButton: {
    height: '24px',
    width: '24px'
  },
  bmCross: {
    background: '#bdc3c7'
  },
  bmMenu: {
    background: '#373a47',
    padding: '2.5em 1.5em 0',
    fontSize: '1.15em'
  },
  bmMorphShape: {
    fill: '#373a47'
  },
  bmItemList: {
    color: '#b8b7ad',
    padding: '0.8em'
  },
  bmOverlay: {
    background: 'rgba(0, 0, 0, 0.3)'
  }
}
`
Actully I Don't know how to add onHover to style

**Comment by negomi** [comment]
Ah, you mean for the buttons/icons.

There isn't an easy way using inline styles like this - you would have to use a [custom icon](https://github.com/negomi/react-burger-menu#custom-icons). Then you would either:
1. detect and store the hover state of the icon using `onMouseOver` and `onMouseOut` and pass different `styles` objects depending on the hover state
2. wrap your custom icon with [Radium](https://github.com/FormidableLabs/radium), which supports declaring :hover states in an object

Alternatively, you can just use CSS, which would look like this:

```css
.bm-burger-button:hover .bm-burger-bars {
  /* Burger icon hover styles here */
}

.bm-cross-button:hover .bm-cross {
  /* Cross icon hover styles here */
}
```
