### ISSUE TITLE
bodyClassName not applying

### ISSUE THREAD

**Issue by jbschrades** [negomi/react-burger-menu#172]
Looks like this feature is dependent upon a pageWrap or outerContainer being defined.  But should it be?

```
applyWrapperStyles() { 
  if (styles.pageWrap && this.props.pageWrapId) {
    this.handleExternalWrapper(this.props.pageWrapId, styles.pageWrap, true);
  }
      
  if (styles.outerContainer && this.props.outerContainerId) {
    this.handleExternalWrapper(this.props.outerContainerId, styles.outerContainer, true);
  }
}
```
But I even tried adding an outContainer prop and style and couldn't get it to work.  Am I missing something obvious?

**Comment by negomi** [comment]
This was a bug - `bodyClassName` should now work for any menu. Thanks for reporting! 🎉
