### ISSUE TITLE
minimal demo code ?

### ISSUE THREAD

**Issue by littlee** [negomi/react-burger-menu#174]
Can you provide a minimal demo code?

the example demo code is a little hard to understand for me
my menu icon never shows, should I import a css file ?

thanks

**Comment by negomi** [comment]
Hi @littlee, yep, if you look at the [styling section](https://github.com/negomi/react-burger-menu#styling), it explains:

> All the animations are handled internally by the component. However, the visual styles (colors, fonts etc.) are not, and need to be supplied, either with CSS or with a JavaScript object passed as the styles prop.

So yes, you just need to import a CSS file or use JS inline styles. Good luck!
