### ISSUE TITLE
IDs not found when using this.props.children

### ISSUE THREAD

**Issue by iMerica** [negomi/react-burger-menu#176]
Hi,

Thanks for building this! Just want to to report this bug when embedded this using children. For example, this works fine:

```jsx
// Using {this.props.my_component}
<App 
     my_component={<Menu outerContainerId={ "outer-wrapper" } pageWrapId={ "main-wrap" } noOverlay isOpen>}
 />
```
but this results in some errors on the console:

```jsx
// Using {this.props.children}
<App>
   <Menu outerContainerId={ "outer-wrapper" } pageWrapId={ "main-wrap" } noOverlay isOpen/>
</App>
```

![screen shot 2017-07-12 at 8 28 56 pm](https://user-images.githubusercontent.com/487897/28149275-3a604840-6741-11e7-8cc4-cee6f3bdfb02.png)

I'm guessing this is because of the order of which components are rendered.

Thanks,

Michael

**Comment by negomi** [comment]
Hey @iMerica, thanks for reporting this.

I'm trying to understand your setup - where are you using `this.props.children`? Do you mean this bug occurs when you pass `Menu` as a child?

If it's easier, you can push a small example of the bug up to a repo and I'll take a look :)

**Comment by negomi** [comment]
Closing as no response - feel free to let me know if this is still an issue.
