### ISSUE TITLE
Improving accessibility

### ISSUE THREAD

**Issue by ghost** [negomi/react-burger-menu#177]
I'm trying to make sure I implement an accessible menu using react-burger-menu and have run into a few issues with keyboard navigation.  I'm wondering if others have found solutions to these:
1. tabbing focus should transfer from button that toggles the menu to the menu itself when opened and vis-a-versa when closed
    - currently wrapping the react-burger-menu in a div with tabIndex=-1 and an id, and controlling the focus of elements with a click handler
2. tabbing focus should not be possible on menu when the menu is closed
    - since the react-burger-menu only animates styles set on elements, I'm not sure how to accomplish this.  I would want to set display: none on the parent after the closing animation has completed. Maybe some sort of beforeTransition and afterTransition hooks would allow for this.

**Comment by negomi** [comment]
Hi @seansean11eis, great idea! I would love to make this more keyboard-navigation friendly.

For now, you could use [`onStateChange`](https://github.com/negomi/react-burger-menu#state-change) and `setTimeout` to achieve what you describe in point 2.

**Comment by AutoSponge** [comment]
I also think the base page should not be in tab order while the menu is open. see https://www.youtube.com/watch?v=fGLp_gfMMGU&list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g&index=25 for one technique option.

**Comment by marcysutton** [comment]
The problem I have is that the Menu button is buried in the component alongside the menuitems, so I can't easily target the menu contents without also hiding the menu button. Ideally, you could set the `inert` attribute on the menu contents but getting access to it is proving difficult. You'd have the same problem with `display:none`. How would you go about doing that without hiding the entire menu, including the menu button (which has its own accessibility problems, I'll submit a PR later)?

**Comment by durr04** [comment]
Hi @marcysutton  , @negomi Any updates on this. Do we have any PR for this? I'm also facing the same issue.

Kindly suggest to improve the keyboard navigation.

**Comment by lkopacz** [comment]
I've gotten some work on this, but currently, my work isn't passing mocha tests. I'll post a PR and link it here.

**Comment by lkopacz** [comment]
https://github.com/negomi/react-burger-menu/pull/288 @negomi I would love feedback on the testing.

**Comment by negomi** [comment]
This was fixed in v2.6.0.
