### ISSUE TITLE
Warning: a `span` tag (owner: `HamburgerMenu`) was passed a numeric string value for CSS property `marginTop` (value: `-1`) which will be treated as a unitless number in a future version of React.

### ISSUE THREAD

**Issue by jianpingw** [negomi/react-burger-menu#179]
I use React 15.6.1 and got the following warning:

Warning: a `span` tag (owner: `HamburgerMenu`) was passed a numeric string value for CSS property `marginTop` (value: `-1`) which will be treated as a unitless number in a future version of React.

It looks like the following line causes the warning:

`halfStrokeWidth = '-' + strokeWidth / 2,`

**Comment by negomi** [comment]
Hey @jianpingw!

Where is the `halfStrokeWidth = '-' + strokeWidth / 2,` line? I don't think that's coming from this component?

**Comment by negomi** [comment]
Closing as no response - feel free to let me know if this is still an issue.
