### ISSUE TITLE
[Ehancement] Adding "reveal" animation

### ISSUE THREAD

**Issue by prajapati-parth** [negomi/react-burger-menu#180]
Please add a reveal animation to the current library just like [here](https://tympanus.net/Development/SidebarTransitions/) to the existing set of animations. 
I know reveal is a little similar to push animation but having reveal would be really great :+1: 

Thanks for the awesome library. :+1:

**Comment by costagolub** [comment]
#193 pull request reveal animation

**Comment by prajapati-parth** [comment]
@costagolub Perfect :ok_hand:
