### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by yaolei** [negomi/react-burger-menu#183]
I just use the  demo code
  ```
 export default class TopMenu extends React.Component {
    showSettings (event) {
        event.preventDefault();
     }
  render () {
    return (
      <Menu>
          <a id="home" className="menu-item" href="/">Home</a>
          <a id="about" className="menu-item" href="/about">About</a>
          <a id="contact" className="menu-item" href="/contact">Contact</a>
          <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>

      </Menu>
    );
  }
}
```
on my home page 
```
if(typeof window !== 'undefined') {
    ReactDOM.render((
        <TopMenu />
    ), document.getElementById('head'))
}
```
get the error 
``` Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of TopMenu.```

**Comment by AlvaroFalcon** [comment]
did you imported the library? 
import {bubble as Menu} from 'react-burger-menu' for example.
I had the same issue, it has to be lowercase.

**Comment by JamesTheHacker** [comment]
@yaolei I fear you may have done exactly what I just did. The README says to use the following:

    import { nameOfAnimation as Menu } from 'react-burger-menu'

Im my case I copied and pasted the example to see it working before I implement it into my application. I didn't change `nameOfAnimation` and left it as is ... which produces the error you're facing.

@AlvaroFalcon answer is correct 💃

**Comment by negomi** [comment]
I'm guessing you solved the issue by now. I've just merged https://github.com/negomi/react-burger-menu/pull/187 (thanks @JamesTheHacker!) so hopefully others will avoid running into this in future :)
