### ISSUE TITLE
Prevent menu close when clicking on overlay

### ISSUE THREAD

**Issue by calvinwyoung** [negomi/react-burger-menu#184]
Is there a way to prevent the burger menu from closing when clicking on the overlay?

I have a sidebar with a few dropdown menu components. If a dropdown menu is open, and a user clicks on the menu's background overlay, the current behavior is to close the dropdown menu *and* the sidebar. Instead, I'd love if *only* the dropdown menu closed (with the sidebar menu remaining open). If the user clicks on the overlay *a second* time (when no dropdown menu is open), then I'd like the sidebar menu to close.

I'm using react-burger-menu with redux-burger-menu, but haven't found an obvious way to hook into the overlay's `onClick` handler.

What's the best way to implement this?

**Comment by negomi** [comment]
Hey @calvinwyoung, ooh, interesting use case.

I haven't heard anyone request this yet so no, it's not currently possible, but I would be happy to add a prop!

**Comment by negomi** [comment]
Added in 2.1.5 - see the new `disableOverlayClick` prop: https://github.com/negomi/react-burger-menu#overlay

**Comment by calvinwyoung** [comment]
@negomi This is awesome, thank you!
