### ISSUE TITLE
Hamburger button not showing

### ISSUE THREAD

**Issue by AlvaroFalcon** [negomi/react-burger-menu#186]
Hi, first of all, the component is great.

I only have one problem, when I add the menu to my view, there is no hamburger button, instead i can click in the middle of the window and get the menu opened.

```
`  render() {
    return (
      <div>
        <div className="App well ">
          <div className="container">
          </div>
          <Menu noOverlay >
            <a id="home" className="menu-item" href="/">Home</a>
            <a id="about" className="menu-item" href="/about">About</a>
            <a id="contact" className="menu-item" href="/contact">Contact</a>
          </Menu>
          <img className="header-image"  src="http://lorempixel.com/1900/300/cats/ReactJS/" alt="Error loading the image"></img>
        </div>
        <div className="container">
          <div className="row">
            {this._renderComponent()}
          </div>
        </div>
      </div>
    );`
```

**Comment by vikram7** [comment]
Check out the styling section in the docs.

Basically, you need to give some css to `.bm-burger-button`:

```css
.bm-burger-button {
  position: fixed;
  width: 36px;
  height: 30px;
  left: 36px;
  top: 36px;
  background-color: blue;
}
```

You'll see a blue square on your page and can adjust your css to place your button where you want it.

**Comment by negomi** [comment]
Thanks @vikram7, beat me to it :)

That's right - it sounds like you need to add styles. Both JS inline styles and CSS are supported. See https://github.com/negomi/react-burger-menu#styling for more info.
