### ISSUE TITLE
Set cursor: pointer for menu open & close buttons?

### ISSUE THREAD

**Issue by dsernst** [negomi/react-burger-menu#190]
Is there a way to add `cursor: pointer' to the open & close icons? It looks like their styles are hardcoded in.

**Comment by dsernst** [comment]
It looks like adding `cursor: pointer` to the hardcoded styles for [`BurgerIcon`](https://github.com/negomi/react-burger-menu/blob/master/lib/BurgerIcon.js#L58) and [`CrossIcon`](https://github.com/negomi/react-burger-menu/blob/master/lib/CrossIcon.js#L60) fixes this.

**Comment by hshelbur** [comment]
Where were you able to do this? I found the BurgerIcon.js in the node modules but I can't seem to get it to work.

**Comment by dsernst** [comment]
@hselbur: If you're hardcoding it into your existing node_modules dependency, you need to do it to the compiled `lib/` files, not the pre-compiled `src/` ones.

**Comment by negomi** [comment]
There was previously no way to do this without CSS.

I actually just made `cursor: pointer` the default in 2.1.5 (assuming most people will probably want this), so no need to edit the source files directly anymore :)
