### ISSUE TITLE
onClose hook

### ISSUE THREAD

**Issue by dbrrt** [negomi/react-burger-menu#192]
Wouldn't it be nice to have an `onClose` so that we could trigger for instance, a Redux action once the sidebar is closed. For now, I'm using states to toggle display of the sidebar, but when I'm closing the menu (e.g : typing esc key), it doesn't change the state `isOpen` and I'd be really more convenient to trigger an action when the menu disapear, to switch the correponding state.

**Comment by negomi** [comment]
Hey @dbrrt! 

Sounds like you're describing the [`onStateChange`](https://github.com/negomi/react-burger-menu#state-change) prop. Would that do what you want?

Let me know :)

**Comment by dbrrt** [comment]
@negomi I missing `onStateChange` in the documentation, it does the job, thanks !
For those who could be interested,
In my view, I trigger the display of the sidebar with a Redux action : 
``` JavaScript
 toggleBurgerSidebar() {
    const {
      show_sidebar
    } = this.props
    show_sidebar()
  }
```
And I used `onStateChange` prop to update the state with another action : 
``` JavaScript
   const {
      sidebarVisible,
      children,
      hide_sidebar
   } = this.props

   var isMenuOpen = function(state) {
     if(state.isOpen === false) {
        hide_sidebar()
     }
   }
```
It works like a charm :thumbsup:

**Comment by negomi** [comment]
Awesome 🎉
