### ISSUE TITLE
Wrapped Page Is Still Scrollable

### ISSUE THREAD

**Issue by monsonjeremy** [negomi/react-burger-menu#197]
Currently with an implementation like the following:
App:
```
      <div id="outer-container" className="forecast-page-container">
        <Menu
          pageWrapId={'page-wrap'}
          outerContainerId={'outer-container'}
          options={this.regions}
          {...this.props}
        />
        <div id="page-wrap" className={'forecast-page full-width'}>
          <Navbar />
          <ForecastPage {...this.props} />
        </div>
      </div>
```
Menu:
```
      <ReduxBurgerMenu
        pageWrapId={this.props.pageWrapId}
        outerContainerId={this.props.outerContainerId}
        isOpen={this.props.burgerMenu.isOpen}
        right
        customBurgerIcon={false}
      >
        .... Some items in the menu
      </ReduxBurgerMenu>
```

When the menu is open I am still able to scroll the page-wrap div element. 
Since I have a list of items in my menu, and it is scrollable this creates a really weird interaction. 

Is there any way to lock the scrolling on the page-wrap item.

**Comment by negomi** [comment]
Not sure if you've already tried this, but setting `overflow: hidden;` on the page wrap element seems to prevent this on the example page.

The overlay also prevents the page from scrolling on the example page, though, so I can only reproduce the scrolling behavior by disabling the overlay (which it doesn't look like you're doing).

If that doesn't help, there might be something more specific to your situation going on, so I could take a look at a working example if you can push up some code to a repo :)

**Comment by monsonjeremy** [comment]
Thanks for the reply @negomi, I ended up finding a workaround by checking the state of the menu and if it is open I set the Document Body style to have ```overflow: hidden```. 

This seems like a hacky workaround, but for some reason setting overflow: hidden on the page wrap element wasn't doing it. I have the overlay as well so i'm not sure why.

Here are the relevant files if you want to take a look:

Component where I put items in the menu:
https://github.com/monsonjeremy/Forecast-Me/blob/master/client/src/components/SpotSelectDrawer.jsx

Container where i do the page-wrap:
https://github.com/monsonjeremy/Forecast-Me/blob/master/client/src/containers/ForecastPageContainer.jsx

ReduxBurgerMenu container: 
https://github.com/monsonjeremy/Forecast-Me/blob/master/client/src/containers/ReduxBurgerMenu.jsx

**Comment by 440459012** [comment]
same trouble, using push animate, when menu is opened, all htm is scrollable, why did you add only overflow-x:hidden, if there is need full body,html overflow:hidden.

**Comment by Igfig** [comment]
I've been having the same problem, but I managed to fix it by explicitly setting height: 100% on the <html> and <body> elements.

**Comment by zeckdude** [comment]
Thanks to @monsonjeremy's suggestion, I followed the same approach, since I wasn't able to get any of the other suggestions to work. 

In case anyone finds value, here's my code snippet:
```js
componentDidUpdate(prevProps, prevState) {
  // If the hamburger menu is open, disable scrolling on the site
  if (prevState.menuOpen !== this.state.menuOpen) {
    if (this.state.menuOpen) {
      document.body.setAttribute("style", "overflow: hidden;");
    } else {
      document.body.setAttribute("style", "overflow: visible;");
    }
  }
}
```

**Comment by negomi** [comment]
Hi all,

I had some time to dig into this, and (as it seems like some people have already discovered), stopping the scrolling when the menu is open requires certain styles to be present on elements outside the menu.

Because these elements will be different in different cases, it's not something this component could reliably handle internally, but I have added an explanation (and suggested solution) to the FAQ: https://github.com/negomi/react-burger-menu/wiki/FAQ#my-page-content-is-still-scrollable-when-the-menu-is-open.

Hope that helps!
