### ISSUE TITLE
React 16 update

### ISSUE THREAD

**Issue by Shadowman4205** [negomi/react-burger-menu#199]
@negomi Hello about react 16 i get this warning,

> warning "react-burger-menu@2.1.6" has incorrect peer dependency "react@>=0.14.0 <16.0.0".
> warning "react-burger-menu@2.1.6" has incorrect peer dependency "react-dom@>=0.14.0 <16.0.0".

will be any update?

**Comment by negomi** [comment]
Fixed in v2.1.7 😃
