### ISSUE TITLE
Browser support: elastic and bubble animation does not work in IE 11

### ISSUE THREAD

**Issue by lancetw** [negomi/react-burger-menu#20]
tested: http://negomi.github.io/react-burger-menu/
Only `elastic` and `bubble` animation does not work in IE11, the others works well.

**Comment by negomi** [comment]
They work for me in IE11, but I have only tested IE11 with https://remote.modern.ie/.

What OS are you using?

**Comment by lancetw** [comment]
test failed:

Win8.1, IE11, 11.0.9600.18053, update versions 11.0.24 (PC, already run
window update)
Win7, IE11, 11.0.9600.17420, update versions 11.0.14 (modern IE VM)

ok:

Azure remote IE11, 11.0.10514.0, update versions RTM



--
lancetw (Hsin-lin Cheng)
http://lancetw.github.io

2015-11-14 3:34 GMT+08:00 Imogen Wentworth <notifications@github.com>:

**Comment by negomi** [comment]
Ah, I see. This project was pretty experimental so I'm not currently making any guarantees about browser support, but I've updated the docs to reflect the IE situation. Thanks for letting me know.

**Comment by lancetw** [comment]
OK, just want you to know that IE11 is still buggy.
