### ISSUE TITLE
Allow `disableOverlayClick` to be a function that returns a boolean

### ISSUE THREAD

**Issue by calvinwyoung** [negomi/react-burger-menu#203]
Hi there,

First, thanks for maintaining this ridiculously awesome package — it's been a life-saver. Also, thanks for adding the `disableOverlayClick` flag in #184 

As an additional enhancement, is it possible to make `disableOverlayClick` accept a function that returns a boolean? Here's the issue I'm running into:

1. Hamburger menu contains some input elements that the user interacts with.
2. I want to prevent the overlay from closing while the user is interacting with certain elements, so my child component executes a callback that flips the parent `Menu`'s `disableOverlayClick` value to `false`.
3. Changing `disableOverlayClick` triggers a re-render on my child component, thereby resetting the user's changes.

If `disableOverlayClick` could accept a function, then I believe I could just change some local value without triggering a full re-render.

If you're okay with this extension, I'd be happy to submit a pull request. Thanks again!

**Comment by negomi** [comment]
Hey @calvinwyoung, that makes sense - I'd happily accept a PR! :)

**Comment by calvinwyoung** [comment]
@negomi Sounds great! This seems to do the trick on my local machine:
https://github.com/negomi/react-burger-menu/pull/205

Feel free to let me know if you have any requests re style / formatting / etc. Thanks for taking a look!
