### ISSUE TITLE
Close menu when the user tap on an option.

### ISSUE THREAD

**Issue by slorenzo** [negomi/react-burger-menu#208]
Hi,

I wanna have the following behavior.

1- The user tap on the hamburger then opens the menu .
2 - The user select an option then closes the menu.

But I'm blocking in the second step.

It is possible?
Thanks!

Sebastian.

**Comment by negomi** [comment]
Hi @slorenzo, yes, this is possible using the `isOpen` prop :)

Check out the wiki for an example: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop
