### ISSUE TITLE
Link from react-router instead of a

### ISSUE THREAD

**Issue by FredericHeem** [negomi/react-burger-menu#21]
Do you mind updating the documentation on the usage of the `Link` component from `react-router`. It's not working out of the box, `Link` has to be wrapped into `Radium`:

```
import React from 'react';
import {stack as Menu} from 'react-burger-menu';
import {Link} from 'react-router';
import Radium from 'radium';

let RadiumLink = Radium(Link);

export default React.createClass({
    render: function() {
        return (
            <Menu>
                <RadiumLink className="menu-item" to="/home">Home</RadiumLink>
                <RadiumLink className="menu-item" to="/settings">Settings</RadiumLink>
                <RadiumLink className="menu-item" to="/blablabla">Blablabla</RadiumLink>
            </Menu>
        );
    }

});

```

Thanks a lot for this component, very useful.

**Comment by negomi** [comment]
Hey @FredericHeem! I think an FAQ page in the wiki would be a good place to document issues with third-party tools like this, so I've created one and added your example: https://github.com/negomi/react-burger-menu/wiki/FAQ

Thanks for the warning!
