### ISSUE TITLE
Don't set z-index to 1

### ISSUE THREAD

**Issue by barbush** [negomi/react-burger-menu#210]
You should change the default CSS z-index to higher than 1 so that if I need to set other page elements to z-index 2, I can do so without changing all the z-indexes for the helper classes.

The actual problem is the screen-overlay doesn't cover some of my other page elements, despite correct configuration.

I'm happy to commit a PR for this, let me know!

**Comment by negomi** [comment]
Good point, fixed in `2.2.0`!
