### ISSUE TITLE
How to integrate with animated hamburger icon

### ISSUE THREAD

**Issue by isuhendro** [negomi/react-burger-menu#212]
Hello,

Any suggestion how to integrated with `animated` hamburger icon like https://jonsuh.com/hamburgers/ ?

Thanks!

**Comment by negomi** [comment]
Hi @isuhendro,

Yes, this should be possible by making the menu a controlled component, hiding the default icons, and triggering open/close from your custom icon. 

See https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop to get an idea of how to implement it.

Hope that helps!
