### ISSUE TITLE
Not able to overwrite the inline style of bm-overlay or bm-menu-wrap

### ISSUE THREAD

**Issue by michaelsync** [negomi/react-burger-menu#214]
I found no way to overwrite the inline style of bm-overlay or bm-menu-wrap.

I have a page like below. 

![image](https://user-images.githubusercontent.com/192911/34474634-c1e60260-efd5-11e7-9400-9fecf698bcba.png)

I put the burger menu in the header which has a fixed width and is located in the center. 

```
<div id="outer-container">
  <div id="page-wrap">
     <div id="header">
          <Menu pageWrapId={"page-wrap"} outerContainerId={"outer-container"}  >
              <a id="home" className="menu-item" href="/">Home</a>
              <a id="about" className="menu-item" href="/about">About</a>
              <a id="contact" className="menu-item" href="/contact">Contact</a>
              <a className="menu-item--small" href="">Settings</a>
            </Menu>
     </div>   
     <div id="content">
     </div>   
  </div>   
</div> 
```

It shows the menu as below even IsOpen property is false. 

![image](https://user-images.githubusercontent.com/192911/34474688-9ae03518-efd6-11e7-8845-a90a1e490001.png)

I think it happend because of the `transform: translate3d(-100%, 0px, 0px)` of bm-menu-wrap. 

If I move Menu out of header DIV then it works. but the hurger icon will be out of header as well. 

I am thinking to overwrite the bm-burger-button but it is hard to make it look like it's in header div. 

And I am not able to overwrite the translate3d of  bm-menu-wrap from CSS as well. 

How do I fix it? Am I missing something? Thanks.

**Comment by negomi** [comment]
Hey @michaelsync,

I think most of the problems you're having will be solved by making sure the menu (and any elements directly wrapping it) are *outside* the page wrap element, like this:
```html
<div id="outer-container">
  <div id="header">
    <Menu pageWrapId={ "page-wrap"} outerContainerId={ "outer-container"}>
      <a id="home" className="menu-item" href="/">Home</a>
      <a id="about" className="menu-item" href="/about">About</a>
      <a id="contact" className="menu-item" href="/contact">Contact</a>
      <a className="menu-item--small" href="">Settings</a>
    </Menu>
  </div>
  <div id="page-wrap">
    <div id="content">
    </div>
  </div>
</div>
```
In general, with the elements laid out correctly, you shouldn't need to override the `transform` property at all. However, if you do want to override any inline styles with CSS, you'll need to use `!important`.

Hope that helps! :)

**Comment by michaelsync** [comment]
Hi @negomi 

Thanks. 

I already tried that and it doesn't work. It will show something similar to this. 

![image](https://user-images.githubusercontent.com/192911/34482430-1937e05c-f00c-11e7-84cb-f85719598243.png)

**Comment by michaelsync** [comment]
The solution that I found is that I hide the burger and put the menu right after the outer-container  div. So the overlay menu will be positioned right. 

then I created another div looked like the burger button and put it in the header div. On click, I changed the state.

**Comment by negomi** [comment]
Hmm ok. If you wanted to link me your code somewhere I can run it, I'm happy to take a look at why this is necessary. I think there's probably a simpler way to get around this, but glad you found a solution for now :)

**Comment by michaelsync** [comment]
@negomi 

Thanks. 

I have created a sample for you to replicate the issue. 

I am just using almost all default resources from create-react-app (type-script version) and your sample CSS with minor modification.

Please check the sample here https://github.com/michaelsync/js-lab/tree/master/react-burger-align-issue

I am using yarn so you can just do the following steps to run the sample. 

- yarn install 
- yarn start 

The code in App.tsx is as below. 

```
import * as React from 'react';
import './App.css';
import { slide as Menu } from 'react-burger-menu';

const logo = require('./logo.svg');

class App extends React.Component {
  render() {
    return (
      <div id="outer-container" className="fill">
        <div className="App-header">
          <Menu pageWrapId={"page-wrap"} outerContainerId={"outer-container"} >
            <a id="home" className="menu-item" href="/">Home</a>
            <a id="about" className="menu-item" href="/about">About</a>
            <a id="contact" className="menu-item" href="/contact">Contact</a>
            <a className="menu-item--small" href="">Settings</a>
          </Menu>
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <div>
          <p id="page-wrap">
            To get started, edit <code>src/App.tsx</code> and save to reload.
        </p>
        </div>
      </div>
    );
  }
}

export default App;

```

This is what I see in Chrome and Edge. You can also try clicking the cross button (x) on the menu to see how the burger menu hides. 

![image](https://user-images.githubusercontent.com/192911/34502393-5c3af42e-f067-11e7-9d0d-d70ca189046d.png)

Feel free to let me know if you need more information. Thanks.

**Comment by negomi** [comment]
Thanks for this! So there are a few things going on:

1. If you just want the slide animation, you don't actually need the outer container and page wrap divs (they are for the more complex animations), so you can stop passing them as props.

2. The menu cannot be inside an element that has other layout styles, so these on its parent element will all cause it not to work properly:
```
width: 1025px;
padding: 0 15px;
display: table;
```
If you need a narrow column layout, create that from a new div somewhere after the menu, instead of using the outer container.

3. The fact you want a max-width on the header means you can't really position the menu inside the header (otherwise its positioning won't work and it will be visible even when 'off screen', as you saw). If you want the burger icon to be inside it, it sounds like you already discovered the recommended way - create a new element and trigger the state based on that.

**Comment by michaelsync** [comment]
Thanks negomi.

**Comment by nikkiczx** [comment]
I found another way around this. I changed the value of the translate3d inside baseStyles.js from -100% to -110% in the menuWrap function. Just sharing..
