### ISSUE TITLE
Animation is broken on mobile phone

### ISSUE THREAD

**Issue by TonyHYK** [negomi/react-burger-menu#215]
Hi, I'm noticing that the css transition for the animation when opening the burger menu is broken. When I open the menu, the menu appears followed by the actual animation (of sliding in for example). As a result, I see the menu appearing and then disappearing before sliding in. The reverse is true when closing.

This happens on safari and chrome on my iphone 6 when I visit http://negomi.github.io/react-burger-menu/.

**Comment by negomi** [comment]
Hi @TonyHYK, thanks for the report!

I'm afraid I don't have a lot of devices to test on, but it works correctly on my iPhone 6s with:
* iOS (Safari) version 11.2.1
* Chrome version 63.0.3239.73

Happy to accept PRs/suggestions for how to fix if anyone has ideas for what might be wrong.

**Comment by TonyHYK** [comment]
hi @negomi , thanks for looking into this, i can confirm that the transition works fine on my friend's phone, this seems like a device-wide glitch with transition on my phone, because i'm seeing it when i use other sites, so probably not a problem with react-burger-menu. I'm closing this issue for now.

**Comment by mrinmoymsarkar** [comment]
Yeah same here, I used this plugin for my website and same happens in iphones, not in android.
