### ISSUE TITLE
Transition timing / transition-timing-function

### ISSUE THREAD

**Issue by lightninglu10** [negomi/react-burger-menu#216]
What's the timing of the transition and also the transition-timing-function? Is this configurable?

I want to change the width of my app in accordance to the entrance of the menu, but want the transition of the app to follow along with that of the menu.

Where can I find this information?

**Comment by negomi** [comment]
Hey @lightninglu10!

You can find the transition-related code for each animation here: https://github.com/negomi/react-burger-menu/tree/master/src/menus

Overriding those properties is not recommended for general usage as it can be tricky to get right and has the potential to break other things (particularly for the more complex animations) but for custom use cases like yours, you can do it by passing a `styles` object or using `!important` if you're using CSS.

Hope that helps!
