### ISSUE TITLE
CLOSE ON CLICK!! HELP!! ASAP!

### ISSUE THREAD

**Issue by KunleMichaels** [negomi/react-burger-menu#218]
how can i configure the menu to close after a user clicks on an item in it?

**Comment by negomi** [comment]
You'll need to close the menu programmatically using the `isOpen` prop: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop
