### ISSUE TITLE
Add prefixed css3 properties for better browser support

### ISSUE THREAD

**Issue by lytvynenkosv** [negomi/react-burger-menu#22]
There are number of browsers that support transform and transition but with prefixes. Android default browser is one of them.

**Comment by negomi** [comment]
Hi @lytvynenkosv, the CSS3 properties are already prefixed by [Radium](https://github.com/FormidableLabs/radium). I know the browser support isn't great for IE and Safari in places but it shouldn't be due to prefixing.

**Comment by lytvynenkosv** [comment]
Looks like it inline-style-prefixer issue https://github.com/rofrischmann/inline-style-prefixer/issues/26

**Comment by negomi** [comment]
It looks like that issue has been fixed now. Is it working for you?

**Comment by negomi** [comment]
This was fixed by inline-style-prefixer 0.5.2, so `npm install` should get you the updated version. Please re-open if still a problem.
