### ISSUE TITLE
how to use this package in gatsby?

### ISSUE THREAD

**Issue by milad1367** [negomi/react-burger-menu#223]
hi.i have be using react modules in my gatsby project but while i added these modules likes:

      <Menu>
        <a id="home" className="menu-item" href="/">Home</a>
        <a id="about" className="menu-item" href="/about">About</a>
        <a id="contact" className="menu-item" href="/contact">Contact</a>
        <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
      </Menu>
I must use the react modules in my Gatsby project but while I added these modules like this: the css not worked.I don't know how to edit class names.please help me i have similar problems in using at eact-headroom.

**Comment by negomi** [comment]
Hi @milad1367,

That depends on how you're using CSS. It sounds like Gatsby might encourage CSS Modules? If so, this might help: https://www.gatsbyjs.org/tutorial/part-two/#css-modules

If not, I would need some more information (ideally a sample of your project I can check out).

Closing this for now as it's not an issue with this package.

**Comment by milad1367** [comment]
i wanted to use this module in my project but since the css not worked i forced delete it.please write a example with gatsbyjs.
