### ISSUE TITLE
How to specify our own menu button?

### ISSUE THREAD

**Issue by qbitza** [negomi/react-burger-menu#224]
In our case we would like the button and the menu separated. The button should be located on a floating div (such as headroom). Including the entire nav menu at that point defeats the purpose of headroom.

Any suggestions?

**Comment by negomi** [comment]
Hi @qbitza, yes, you can do this with a combination of the `isOpen` and `customBurgerIcon` props.

You will want to do `customBurgerIcon={false}` to avoid rendering the default button, then trigger the open state from your custom button. See https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop for an example.

Hope that helps!

**Comment by qbitza** [comment]
Thanks
