### ISSUE TITLE
I see no reference about submenu, is it possible to implement it? 

### ISSUE THREAD

**Issue by killvung** [negomi/react-burger-menu#225]
given example code from README.md
```
<Menu>
        <a id="home" className="menu-item" href="/">Home</a>
        <a id="about" className="menu-item" href="/about">About</a>
        <a id="contact" className="menu-item" href="/contact">Contact</a>
        <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
</Menu>
```

I assumed the way to implement submenu should be similar to 
```
<Menu>
        <a id="home" className="menu-item" href="/">Home</a>
        <div>
               <a>...</a>
         <div/>
        <a id="about" className="menu-item" href="/about">About</a>
        <a id="contact" className="menu-item" href="/contact">Contact</a>
        <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
</Menu>
```

I wanna verify it first before scratching my-own

**Comment by danieljuvito** [comment]
I'm surprised how this menu using <a> tag right away instead of using <ul> tag. It can support tree structure. Maybe the submenu can be implemented like this.

```
import { Menu, SubMenu, Item } from ''

<Menu>
  <Item id="home" className="menu-item" href="/">Home</Item>
  <SubMenu id="" text="Click to Expand">
    <Item>...</Item>
  <SubMenu/>
  <Item id="about" className="menu-item" href="/about">About</Item>
  <Item id="contact" className="menu-item" href="/contact">Contact</Item>
  <Item onClick={ this.showSettings } className="menu-item--small" href="">Settings</Item>
</Menu>
```

Menu is <ul> ... <ul>
Item is <li> <a> ... </a> </li>
Submenu is <li> <a> ... </a> <ul> ... </ul> <li>

**Comment by negomi** [comment]
Hi @killvung, yep, that's a completely valid way to do it.

The menu just provides you a container - it has no opinions about what you put inside it so you can build submenus however you like.

**Comment by therohitjha** [comment]
> Hi @killvung, yep, that's a completely valid way to do it.
> 
> The menu just provides you a container - it has no opinions about what you put inside it so you can build submenus however you like.

@negomi i tried adding sub categories but unable to do that,can give some working live example?

**Comment by therohitjha** [comment]
> given example code from README.md
> 
> ```
> <Menu>
>         <a id="home" className="menu-item" href="/">Home</a>
>         <a id="about" className="menu-item" href="/about">About</a>
>         <a id="contact" className="menu-item" href="/contact">Contact</a>
>         <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
> </Menu>
> ```
> 
> I assumed the way to implement submenu should be similar to
> 
> ```
> <Menu>
>         <a id="home" className="menu-item" href="/">Home</a>
>         <div>
>                <a>...</a>
>          <div/>
>         <a id="about" className="menu-item" href="/about">About</a>
>         <a id="contact" className="menu-item" href="/contact">Contact</a>
>         <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
> </Menu>
> ```
> 
> I wanna verify it first before scratching my-own

```
 <Menu {...props}>
      <div className="dropdown">
    <button className="dropbtn">Dropdown 
      <i class="fa fa-caret-down"></i>
    </button>
    <div className="dropdown-content">
      <a href="/">Link 1</a>
      <a href="/">Link 2</a>
      <a href="/">Link 3</a>
    </div>
  </div> 
      
    </Menu>
```


then add below css 
`.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}


.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}`

**Comment by riddhijshetty** [comment]
> > given example code from README.md
> > ```
> > <Menu>
> >         <a id="home" className="menu-item" href="/">Home</a>
> >         <a id="about" className="menu-item" href="/about">About</a>
> >         <a id="contact" className="menu-item" href="/contact">Contact</a>
> >         <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
> > </Menu>
> > ```
> > 
> > 
> > I assumed the way to implement submenu should be similar to
> > ```
> > <Menu>
> >         <a id="home" className="menu-item" href="/">Home</a>
> >         <div>
> >                <a>...</a>
> >          <div/>
> >         <a id="about" className="menu-item" href="/about">About</a>
> >         <a id="contact" className="menu-item" href="/contact">Contact</a>
> >         <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
> > </Menu>
> > ```
> > 
> > 
> > I wanna verify it first before scratching my-own
> 
> Here is working example for you. :)
> 
> ```
>  <Menu {...props}>
>       <div className="dropdown">
>     <button className="dropbtn">Dropdown 
>       <i class="fa fa-caret-down"></i>
>     </button>
>     <div className="dropdown-content">
>       <a href="/">Link 1</a>
>       <a href="/">Link 2</a>
>       <a href="/">Link 3</a>
>     </div>
>   </div> 
>       
>     </Menu>
> ```
> 
> then add below css
> 
> ```
> .dropdown {
>   float: left;
>   overflow: hidden;
> }
> 
> .dropdown .dropbtn {
>   font-size: 16px;  
>   border: none;
>   outline: none;
>   color: white;
>   padding: 14px 16px;
>   background-color: inherit;
>   font-family: inherit;
>   margin: 0;
> }
> 
> 
> .dropdown-content {
>   display: none;
>   position: absolute;
>   background-color: #f9f9f9;
>   min-width: 160px;
>   box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
>   z-index: 1;
> }
> 
> .dropdown-content a {
>   float: none;
>   color: black;
>   padding: 12px 16px;
>   text-decoration: none;
>   display: block;
>   text-align: left;
> }
> 
> .dropdown-content a:hover {
>   background-color: #ddd;
> }
> 
> .dropdown:hover .dropdown-content {
>   display: block;
> }
> ```

What are the properties in the menu ?
