### ISSUE TITLE
Not fully collapsed drawer option?

### ISSUE THREAD

**Issue by arovillard** [negomi/react-burger-menu#226]
Sometimes it's nice to not fully collapse the drawer and instead keep a narrow-icon-only version of the nav. Would is be possible currently? All I think would be required is to not fully collapse the menu (pass a prop with the pixel or % width when collapsed) and then mange the menu items to have a full and collapsed state using a state hook.

something like this:
http://social.technet.microsoft.com/wiki/cfs-file.ashx/__key/communityserver-wikis-components-files/00-00-00-00-05/8883.sidemenu.gif

Cheers

**Comment by negomi** [comment]
Hi @arovillard, yep, this has been suggested before.

I implemented one way of doing it (for a very old version of the menu) to demonstrate, which is here if you're interested: https://github.com/negomi/react-burger-menu/tree/navbar-extension

It would be even easier to adjust the % that shows when collapsed, as that would just require changing the transform on this line: https://github.com/negomi/react-burger-menu/blob/master/src/baseStyles.js#L42

You wouldn't even have to fork the project for this as you could actually just do it by passing the correct style in for the closed state using the `styles` prop.

The reason I have hesitated to make this a feature officially is that it wouldn't work for all the animations, and I'd like to keep all props working for all animations to avoid confusion.

Hope that helps!
