### ISSUE TITLE
scripts in index.html

### ISSUE THREAD

**Issue by sruthisripathi** [negomi/react-burger-menu#229]
Hi,
In the example that is given, there are 3 scripts included - common.js, bundle.js and example.js

Example.js is the main component. Not sure why it is included and where did the other 2 files come from ?

Also, the stylesheet example.less is included as example.css. How does it work?

**Comment by negomi** [comment]
Hi @sruthisripathi,

They're generated during the build process using Browserify (https://browserify.org/). 

common.js is vendor (external library) code, bundle.js is the component code and example.js is the demo page code (separate from the component as it's only needed for the demo page).

.less files are styles written using the Less preprocessor (http://lesscss.org/) and need to be compiled to CSS (also done by the build process) before they can be used by a browser.
