### ISSUE TITLE
Menu doesn't close when clicking Link in react-router-dom

### ISSUE THREAD

**Issue by individual11** [negomi/react-burger-menu#231]
I've looked through some of the other issues, and I see people have used `isOpen={ false }` to solve their problem, but that doesn't seem to work for me. The basic code is below. Every time I click on any of the links, the menu doesn't close, and the bubble animation starts over.

```Javascript
import React from "react";
import { BrowserRouter as Router, Route, Link, Switch, Redirect} from "react-router-dom";
import { bubble as Menu } from 'react-burger-menu'

const BasicExample = () => (
  <Router>
    <div className="bg-navy w-100 h-100">
      <Menu width={ 180 } isOpen={ false }>
        <Link className="menu-item" to="/">Home</Link>
        <Link className="menu-item" to="/about">About</Link>
        <Link className="menu-item" to="/contact">Contact</Link>
        <Link className="menu-item" to="/settings">Settings</Link>
      </Menu>
         <Switch>
            <Route exact path="/" component={Home} />
            <Route path="/about" component={About} />
            <Route path="/topics" component={Topics} />
            <Redirect to="/" />
         </Switch>
      </div>
  </Router>
);
```

**Comment by individual11** [comment]
I ended up managing the state in the component and that gets it closed, but if there is a cleaner way, I would love to know.

**Comment by negomi** [comment]
Hi @individual11,

The recommended way to manage programmatic closing of the menu like this is to wrap it in a parent component and use that to manage its state.

See https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop for an example.

Hope that helps :)

**Comment by individual11** [comment]
That's basically what I ended up doing. It made sense when I thought about it from React point of view. thanks for replying, love the component!

**Comment by strangeBird3** [comment]
Thank you for responding to this Negomi. Helpful! love your widget
