### ISSUE TITLE
How can I add a background to the bars?

### ISSUE THREAD

**Issue by Jeel-Shah** [negomi/react-burger-menu#236]
Hello!

I would like to add a background to the bars (by having an additional rectangle surrounding it with a background color of xxx, I have attached an image)  so that when a user scrolls over different colors, the bars are easily visible.

** What I have tried **

1. Surrounded `<Menu ... />` with a div and tried to style that.
2. Added a `className` to `Menu .. />` called `bm-background`. This styles the menu itself and not the bars.
3. Targeted `bm-burger-button` div and added a black background followed by an increase in padding; this only results in an increase in the size of the button. 

> How can I achieve this?

Thanks a bunch!

![bars with a background](https://user-images.githubusercontent.com/4922694/38450313-bf2e4858-39e9-11e8-92a3-ac2e4e0d45ae.png)

**Comment by negomi** [comment]
Hey @Jeel-Shah,

One way to achieve this would be to add a border to the `.bm-burger-button` div in the same color as the background, then make sure you apply `box-sizing: content-box;` to avoid shrinking the button.

For example, this CSS:
```css
.bm-burger-button {
    background: yellow;
    border: 8px solid yellow;
    box-sizing: content-box;
}
```
Produces this effect on the demo page:
![screen shot 2018-04-06 at 7 42 44 pm](https://user-images.githubusercontent.com/3727684/38450442-b6a14968-39d2-11e8-88df-157cbb933ee5.png)

Does that do what you want?

**Comment by Jeel-Shah** [comment]
Yes! That's awesome and exactly what I was looking for. Thank you for the quick reply. :D
