### ISSUE TITLE
Close 'X' button not working in mobile

### ISSUE THREAD

**Issue by banderson5144** [negomi/react-burger-menu#24]
When I try to click the close 'X' button on any mobile device it doesn't register. Clicking on the main body of the page does close it. The 'X' does work on desktop. Any reason why this may be happening?

**Comment by negomi** [comment]
Just tested and it's working for me on iPhone 6 (iOS 9.1) in Chrome and Safari. I don't have access to any other devices right now, but I can't think of any obvious reason why it wouldn't be working. Are you trying with the demo page or using the component in a project?

**Comment by banderson5144** [comment]
Nexus 5 marshmallow 6.0,  chrome, just tested on your demo page and same issue, even used a stylus to be ultra precise

**Comment by banderson5144** [comment]
When zoomed in (a lot) I can click on it and see it register and close. But at initial zoom it doesn't register

**Comment by negomi** [comment]
I just tried on BrowserStack, and it seems to work (sort of) depending on where you click. It's definitely Android (maybe even device) specific, so I'll try to find a more reliable way to test and look into it when I get some time. Thanks for letting me know.

**Comment by benjy** [comment]
I can confirm this is also reproducible on the demo page with a Samsung S5.

**Comment by patrik-piskay** [comment]
I had the same issue, what helped was to make the target area of the close button bigger.

Setting
```
width: 30,
height: 30,
right: 5,
top: 5,
```
on buttonStyle in `CrossIcon.js` (or targeting the button via CSS rules with `!important` really) solved it for me. But it would be nice to have the possibility of styling the button via props or custom class name.

**Comment by negomi** [comment]
It seems like this is due to the size of the button. I've expanded the default size (from v1.5.1), and also added a class to the button (`.bm-cross-button`), plus the option to style it via the `styles` prop.
