### ISSUE TITLE
Hiding the burger icon after an onClick?

### ISSUE THREAD

**Issue by raindecastro** [negomi/react-burger-menu#242]
Hi there i'm having some trouble making this work. I'm not sure on how I'll be able to make the burger icon hide when I for example click a button. Can't seem to find it in the documentation. Thank you in advance!

**Comment by ragboyjr** [comment]
Can you give a bit more info?

You can hide the burger icon by passing `customBurgerIcon={false}` to the Menu component.

**Comment by negomi** [comment]
Hi @raindecastro,

Yep, when you listen for an event (e.g. the click of a button), you should be able to set some flag/variable in state which you can then use to pass `false` to `customBurgerIcon`.

If that isn't what you mean, feel free to paste some code snippets or a link to your code and I can try to help further.
