### ISSUE TITLE
Disable the events on the original button

### ISSUE THREAD

**Issue by Asher978** [negomi/react-burger-menu#243]
Hello, 

So I using a custom React Element to show the icon. The custom icon is also handling the open/close of the draw menu. How i can turn off the events on the original button. They are both clashing with each other.
`<Menu left customBurgerIcon={<Hamburger openMobileNav={this.openMobileNav}/>} isOpen={isOpen} customCrossIcon={ false } >`

**Comment by Asher978** [comment]
Sorry about posting. I just figured it out

**Comment by negomi** [comment]
Hey @Asher978,

It sounds like your best option is to pass `customBurgerIcon={false}` and then just keep your `Hamburger` component separate from the menu.

Glad you figured it out :)
