### ISSUE TITLE
"scale rotate" and "reveal" animations glitch in macOS Safari

### ISSUE THREAD

**Issue by mvasin** [negomi/react-burger-menu#245]
When closing sidebar in "scale rotate" example, the page body jumps to a different position and starts movement from there.

**Comment by negomi** [comment]
Hi @mvasin, what browser (and version) are you seeing this in? Is it reproducible on the demo page?

**Comment by mvasin** [comment]
Hello @negomi, I experience it in macOS Safari. Here is a gif I made.

It works fine in Chrome and Firefox though.

![quirk](https://user-images.githubusercontent.com/12434833/40617845-46fc8ebc-6298-11e8-964f-eb4452d5d007.gif)

**Comment by mvasin** [comment]
Reveal effect also looks problematic:

![reveal](https://user-images.githubusercontent.com/12434833/40618163-52965d1a-6299-11e8-8bb6-07dc47a4bf53.gif)
