### ISSUE TITLE
isOpen attribute has no effect

### ISSUE THREAD

**Issue by Fintasys** [negomi/react-burger-menu#254]
I tried to open the BurgerMenu as default but attribute isOpen makes no change. Redux state is still isOpen=false
Clicking on the Button changes the state and opens the Menu.
Other attributes like customBurgerIcon, animation, styles are working fine.

`<ReduxBurgerMenu isOpen={ true }>`

**Comment by negomi** [comment]
Hi @Fintasys,

If you're using Redux, you should set the isOpen value in your Redux store instead:
```js
const initialState = {
  burgerMenu: {
    isOpen: true
  }
};
const store = createStore(initialState);
```
The `isOpen` prop will have no effect because if you're using redux-burger-menu, that takes control of the open/closed state so it will reflect the state set in your store instead.
