### ISSUE TITLE
Menu opening on all button clicks

### ISSUE THREAD

**Issue by jkerrwilson** [negomi/react-burger-menu#255]
The menu component is opening on all button clicks unless I explicitly call e.preventDefault() in every onClick handler. This is a huge pain, is there something I've missed that prevents this behavior?

**Comment by negomi** [comment]
Hi @jkerrwilson,

How are you managing the menu open state? Are you setting it with the `isOpen` prop? If so, check you're keeping your external state in sync and passing down the correct value. This issue sounds similar: https://github.com/negomi/react-burger-menu/issues/230

If it's something else, feel free to provide a code sample (ideally a repo reproducing the issue) and I can help to debug further.

**Comment by jkerrwilson** [comment]
I think this is probably the same issue.
