### ISSUE TITLE
Safari: Animations using pageWrapId break document.width if Menu is on left side

### ISSUE THREAD

**Issue by netlemur** [negomi/react-burger-menu#26]
On OS X Safari 9.0.1, the current Safari on iOS and WebKit Nightly (r194006): 

When using animations requiring `pageWrap` and `outerContainer` (like elastic, push, etc.) with a Menu on the _left side_ the document.width gets wider after closing the menu.
It works fine if the Menu is on the right.

![screen shot 2015-12-12 at 17 13 19](https://cloud.githubusercontent.com/assets/773681/11762811/b729ca7e-a0f3-11e5-8cb3-d9ccb474068f.png)

**Comment by negomi** [comment]
Fixed in v1.4.6. Thanks!
