### ISSUE TITLE
Working with a canvas with react-burger-menu

### ISSUE THREAD

**Issue by NotoriousGOR** [negomi/react-burger-menu#260]
I am using particles.js as my background and of course it's using a canvas. Some of the animations aren't working with the canvas (pushRotate won't push the background) and I was just curious if there is a way I can have this work with a canvas.

Thank you

**Comment by GabeDesigns** [comment]
I deleted the canvas element and it still did the same so I think it just means that I am doing something wrong in my CSS. Is there any documentation on how to write the CSS?
