### ISSUE TITLE
scalerRotate not working

### ISSUE THREAD

**Issue by Mattaious** [negomi/react-burger-menu#261]
having difficulty getting this working 100%, menu works and slides out however, the content of my page does not scale and rotate nor does the burger align on the right of the page but the menu is.   what am i doing wrong?
---------------------------------------------------------------------------------------
import React, {Component} from 'react';
import { scaleRotate as Menu } from 'react-burger-menu'

class Nav extends Component {
    showSettings(event) {
        event.preventDefault();

    }

    render() {
        return (

            <div id="outer-container">
                <Menu pageWrapId={"page-wrap"} outerContainerId={"outer-container"}/>
                <main id="page-wrap">
                    <Menu right>
                        <a id="home" className="menu-item" href="/">Home</a>
                        <a id="about" className="menu-item" href="/about">About</a>
                        <a id="contact" className="menu-item" href="/contact">Contact</a>
                        <a onClick={this.showSettings} className="menu-item--small" href="">Settings</a>
                    </Menu>
                </main>
            </div>

        );
    }
}

export default Nav;

---------------------------------------------------------------------------------
import React, {Component} from 'react';
import NavHeader from './NavHeader';
import ImageHeader from './ImageHeader';
import Body from './body';

export default class App extends Component {

    render() {
        return (
            <React.Fragment>
                <div>
                    <NavHeader/>
                    <ImageHeader/>
                    <Body/>
                </div>
            </React.Fragment>
        );

    }
}

**Comment by mehmetkose** [comment]
![Screen Shot 2019-05-08 at 17 19 13](https://user-images.githubusercontent.com/706678/57382354-7821a180-71b5-11e9-9501-d71dbc83c37f.png)


Same here. The other types working but this one is not working.

**Comment by usama-asfar** [comment]
Does anyone know how to fix this?
