### ISSUE TITLE
Menu's children always wrapped in <nav /> making it hard to use as normal off-canvas widget

### ISSUE THREAD

**Issue by jnachtigall** [negomi/react-burger-menu#264]
Hey :)

I'd like to use this for an off-canvas widget. However, the off-canvas should not contain a `<nav />` but on the left a list of elements. And on the right there should be another off-canvas with various filters.

Similar to this: https://www.plattform-i40.de/I40/Navigation/Karte/SiteGlobals/Forms/Formulare/karte-anwendungsbeispiele-formular.html (Click on "LISTE" on the left, or "FILTEROPTIONEN" on the right) So there's a map in the middle which has 2 off-canvas elements left and right that can be toggled.

Not sure this is possible or the best widget for this? 

For one I've seen that all `<Menu />` children are wrapped in a `<nav />`. This is something I would not want since the children are not a navigation. 

https://github.com/negomi/react-burger-menu/blob/7e35a2d83b12b0e4132a7f459cbcd663610c7efe/src/menuFactory.js#L236-L259

I read https://github.com/negomi/react-burger-menu/issues/224#issuecomment-360362734 and thought of going down this way but I am not sure. Thanks for pointers, happy to contribute a PR if appropriate.

**Comment by negomi** [comment]
Hey @jnachtigall,

Is your concern about semantic accuracy?

The menu was built with the navigation use case in mind, which is why we make that assumption, but it's true that it's just a sidebar and doesn't have to be used for navigation at all.

I'd be open to adding a prop (`itemListElement` or something) and allowing you to pass in a tag name string (e.g. `'div'`) with the default as `'nav'`, which we could then use to construct that element.

Would that help?

**Comment by gerdneuman** [comment]
> Is your concern about semantic accuracy?

Yes, this and accessibility (screens reader often have kind of "jump to nav" functionality.

...

> I'd be open to adding a prop (itemListElement or something) and allowing you to pass in a tag name string (e.g. 'div') with the default as 'nav', which we could then use to construct that element.
>
> Would that help?

I think so. Should be easy to add. I'll try this. Thank you!

**Comment by jnachtigall** [comment]
> Is your concern about semantic accuracy?

Yes, this and accessibility (screens reader often have kind of "jump to nav" functionality.

...

> I'd be open to adding a prop (itemListElement or something) and allowing you to pass in a tag name string (e.g. 'div') with the default as 'nav', which we could then use to construct that element.
>
> Would that help?

I think so. Should be easy to add. I'll try this. Thank you!

**Comment by jnachtigall** [comment]
Another thing for this use case: The `position` of `.bm-menu-wrap` needs to be `absolute` not `fixed` since the off-canvas moves only the middle part of the page (the map) not the whole page. Not sure how to tackle this though. Maybe it's easier to just use some custom CSS...

**Comment by imshuffling** [comment]
> Hey @jnachtigall,
> 
> Is your concern about semantic accuracy?
> 
> The menu was built with the navigation use case in mind, which is why we make that assumption, but it's true that it's just a sidebar and doesn't have to be used for navigation at all.
> 
> I'd be open to adding a prop (`itemListElement` or something) and allowing you to pass in a tag name string (e.g. `'div'`) with the default as `'nav'`, which we could then use to construct that element.
> 
> Would that help?

I'd be interested in this, gives a bit more flexibility.

Would like to add aria-role to the wrapper.

**Comment by tbredin** [comment]
Same issue here, would be lovely to add a prop for the wrapper element to change it to, say, a `div`. Your suggestion sounds perfect @negomi 👍 

For context: our use case is in a web document editor (similar to a google doc), and it simply opens a tray of text editing tools in the sidebar, which to our users (including those using accessibility tools like screen readers) doesn't make sense as a `nav` component. Hope that helps :)

**Comment by jnachtigall** [comment]
I think this is still an issue. `react-burger-menu` could be perfectly used as a sidebar, but would need another wrapper tag than `nav` for this. So please keep open :)

**Comment by negomi** [comment]
This is now possible to switch to a `div` as of `v2.8.0`: https://github.com/negomi/react-burger-menu#custom-item-list-element 🥳
