### ISSUE TITLE
Looking for a solution to achieve this (link below) sidebar behavior.

### ISSUE THREAD

**Issue by gaaabor** [negomi/react-burger-menu#267]
Hey!

I'm trying to recreate [THIS](http://www.oasisgracebay.com/) sidebar behavior for a few days now, but i can't figure it out. I'm using the PUSH animation.

The features i would need: 

- When the page loads up on Desktop the sidebar is open and the `<main id="page-wrap">` is fully visible and scrollable. (I managed to set the `isOpen` state to `true` as a default, but the main div is pushed to the right so you can't see approx 20% of the site)

- However if you resize the browser (go below 900px for example) or load up the page on Tablet/Mobile the sidebar should function as normal.

Sorry if my explanation wasn't clear enough, but if you click the link you'll see what I'm talking about :)

Do you @negomi or anyone else has an idea how i could achieve this? Thanks in advance! :)

**Comment by negomi** [comment]
Hi @gaaabor,

This issue has a long discussion with some suggestions to achieve a responsive menu, which is close to what you want: https://github.com/negomi/react-burger-menu/issues/39

One problem is that there is currently no animation that keeps all content visible when the menu is open. Push pushes it to the right (as you found), and Slide covers it to the left. You could possibly do something with margin or padding on the invisible part to create the illusion that all your content is visible, but it's a bit hacky.

**Comment by gaaabor** [comment]
Thanks for answering, at the end i've decided to keep the sidebar close at all times, so problem solved :)
