### ISSUE TITLE
Why is overflow-x: hidden being set on html and body elements?

### ISSUE THREAD

**Issue by dlong500** [negomi/react-burger-menu#268]
I'm not understanding why `overflow-x: hidden` is being set on the `<html>` and `<body>` elements.  It causes a lot of problems when trying to deal with scrolling issues (at least with the `<html>` element) because browsers infer a value of `auto` for `overflow-y` when only `overflow-x` is set.

Wouldn't it make sense to not set any default styling on the html and body elements and instead use props passed to the menu?  In this case we would also need a `htmlClassName` property for setting styling on the root `<html>` element just like `bodyClassName` does for the `<body>` element.

That way everyone can customize the styling for those elements however is needed.  This also seems like it would be more in line with the already stated philosophy that scrolling issues are really outside the scope of this project.

As a side note, while the demo page appears to work OK, the method of setting all the containing elements to `height: 100%` can cause massive problems with in-site navigation using routers like react-router (like having the page stay scrolled way down when navigating from one route to another).  And without the `height: 100%` styling we run into other problems (like what I mentioned above).  It's a shame that there isn't an easier way to handle things, but for now I think the only thing to do is let users handle all of the styling directly.

**Comment by negomi** [comment]
Hi @dlong500,

I forget the exact reason for setting `overflow-x: hidden`, but I think it was that in a certain browser (possibly Firefox), the page was horizontally scrollable when the menu was open. Setting that property prevented the issue, though I'm sorry it's potentially causing other problems.

It's a fair suggestion to just make users handle all their own styling, but it's a tricky balance between making something that 'just works' in the most simple use cases so people don't have to put in too much work to just get it working at all, while also being customizable enough to work for more complex cases.

You could use the `onStateChange` prop and set your own `html` or `body` class names if you wanted to override the styles the menu sets when it opens - would that help?

**Comment by dlong500** [comment]
I'm not sure that would work because inline styles get applied after classes, so there would be no way to override the `overflow-x: hidden` style on the `<html>` element as things currently stand.  Maybe if you added the suggested `htmlClassName` property and then only apply the default html and body styling if the respective `htmlClassName` and/or `bodyClassName` props are not passed?

**Comment by negomi** [comment]
Yeah, you'd have to use `!important` to solve the specificity issue. I'll leave this open as a feature request to add those props :)

**Comment by richardxia** [comment]
We're also running into an issue with `overflow-x: hidden` being set on the `html` and `body` elements because we have a `position: sticky` navigation bar. Apparently, `position: sticky` has issues if [any of its ancestor elements has `overflow` set to anything besides `visible`](https://github.com/w3c/csswg-drafts/issues/865), so it's causing our navigation bar to stop sticking once the hamburger menu opens.

I think these are the lines in react-burger-menu that set overflow-x on `html` and `body`, so we'd need to make them conditional if we add a new prop for them: https://github.com/negomi/react-burger-menu/blob/5c89005d60cdf16e0ed53fe3fc091014214a8eb2/src/menuFactory.js#L98-L101
