### ISSUE TITLE
Not an issue: thanks and usage

### ISSUE THREAD

**Issue by Offirmo** [negomi/react-burger-menu#271]
Thanks a lot for your cool lib and the hard work behind it.

My usage: (hobby game) https://www.online-adventur.es/apps/the-boring-rpg/index.html

I always wanted this menu effect and got it for free thanks to your nice lib!

**Comment by shakhbulatgaz** [comment]
awww

**Comment by negomi** [comment]
Aw thanks @Offirmo, glad you like the menu ❤️ 

Your game is awesome by the way!

**Comment by Offirmo** [comment]
@negomi thanks 😊
