### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by RenanNeitzel** [negomi/react-burger-menu#273]
I am not able to access the classes of the menu component. In the css file, when calling the bm-cross class, stylization does not occur, just as it was not happening with other classes.

It looks like the class is private in the element and I can not access it.

How could I stylize the cross button in this case?

![printcss](https://user-images.githubusercontent.com/41584304/46223760-a3443880-c32a-11e8-983c-5c0949f6db76.png)
![printjs](https://user-images.githubusercontent.com/41584304/46223764-a50dfc00-c32a-11e8-90b0-2e0d2ae199dd.png)

**Comment by negomi** [comment]
Hi @RenanNeitzel,

The classes in the docs (`bm-cross` etc.) are just applied as regular CSS classes which can be accessed globally, so they're not private or anything.

It looks like you might be using CSS Modules. I would check what your Sass is actually being transformed into, i.e. does the CSS output contain the literal class names, or are they being shortened or scoped in some way? If so, you'll need to make sure they're excluded from those aspects of compilation (this might help https://github.com/css-modules/css-modules#exceptions).
