### ISSUE TITLE
Sidemenu dragging the wrapper div

### ISSUE THREAD

**Issue by freitasdfb** [negomi/react-burger-menu#275]
How can I do to make the Sidemenu div move the wrapper div like the reveal example in demo

**Comment by freitasdfb** [comment]
Yes! I followed de docs and added the wrapper and container div. I'm sorry but now I can't send my code, but I will add as soon as possible.

**Comment by negomi** [comment]
Hi @freitasdfb, you're not passing the `pageWrapId` and `outerContainerId` props down the Menu component, only to your Sidemenu component.
