### ISSUE TITLE
Do search input fields need a special wrapper inside the menu?

### ISSUE THREAD

**Issue by papanugget** [negomi/react-burger-menu#276]
Hello, 

First of all, let me say this is a great component.  Exactly what I needed!  I'm trying to implement a search bar inside the burger and I'm trying to call the onChange event with an eventHandler but the eventHandler never seems to get called (i.e. can't console log any changes to the text field).  Funny thing is this behaves as expected in a [CodeSandbox](https://codesandbox.io/s/9yq70z211p) but not in dev environment.  If anyone has any ideas it would be greatly appreciated!  Thanks in advance.

Example code: 
App.js
```
import React, { Component } from 'react';
import Sidebar from './components/Sidebar';

class App extends Component {
  render() {
    return (  
      <div className="wrapper">
        <Sidebar/>
      </div>
    );
  }
}

export default App;
```
Sidebar.js
```
import React, { Component } from "react";
import { slide as Menu } from "react-burger-menu";

class Sidebar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      term: "hell"
    };
    this.onInputChange = this.onInputChange.bind(this);
  }
  onInputChange(e) {
    console.log(e.target.value);
    this.setState({ term: e.target.value });
  }

  render() {
    return (
      <Menu>
        <div className="locations" id="locations">
          <h2 className="title-large">Public Restrooms</h2>
          <form id="search-form">
            <input
              id="restroom-search"
              type="text"
              onChange={this.onInputChange}
            />
            Whatever you enter: {this.state.term}
          </form>
        </div>
      </Menu>
    );
  }
}

export default Sidebar;
```

**Comment by negomi** [comment]
Hi @papanugget,

That is very strange, I can't see any obvious reason why this would not work in your dev environment.

Are all other event handlers in your app working correctly? I'm wondering if something is happening in your build process to affect this.

**Comment by papanugget** [comment]
Hi @negomi, 

It may have had something to do with a lifecycle method as I was using the sidebar to pull in data from JSON also.  I'm still new at this stuff.  In any case, I wound up not using your burger menu even though I really wanted to :-).  I built one from scratch instead.  Thanks for the reply!

**Comment by negomi** [comment]
Sorry you couldn't get it to work, but glad you managed to build your own :)
