### ISSUE TITLE
Is there a way to preventDefault() on the click on the button?

### ISSUE THREAD

**Issue by yeshwanthjagannath** [negomi/react-burger-menu#278]
Is there a way to preventDefault() on the click on the menu button? If so how do can we override the e.preventDefault() method for the button click?

**Comment by negomi** [comment]
Hi @yeshwanthjagannath, the only way to do this currently would be to disable the default burger icon (see https://github.com/negomi/react-burger-menu#custom-icons) and trigger the menu from a custom button.

**Comment by yeshwanthjagannath** [comment]
Thanks for the response @negomi . I will give this a shot and let you know how it goes! Great nav lib BTW! Thank you for this!

**Comment by negomi** [comment]
No problem, good luck! :)
