### ISSUE TITLE
Is it possible to display menu as "regular flat menu" when screen is wide enough?

### ISSUE THREAD

**Issue by Acerbic** [negomi/react-burger-menu#281]
So, desirable behavior:

1) when @media query is detecting wide screen (desktop browser, for example) render the menu as normal (static position, flexbox) block nav -> [ item, item, item], 

2) and when the screen is small (mobile), render as it does right now - a burger button + popup menu.

It this currently possible? I've resorted to having 2 parallel menu's on the page - one is flat, one is burger and showing/hiding them accordingly, but if I could only have one and switch it from flat-mode to burger-mode, it would be great.

**Comment by negomi** [comment]
Hi @Acerbic,

To achieve this, I would put your menu contents in a component, and then reuse it for each case. So for wide screens, just render it as-is, then for narrow screens, render it inside the burger menu. That way you shouldn't need 2 copies of the burger menu (because for wide screens you don't want the burger functionality at all).

Does that help?

**Comment by peyo** [comment]
Hi Negomi,

Is there a way to show a regular flat menu using a ternary operator and window.innerWidth?

Something like. FYI, I'm still debugging:

`function ResponsiveBurger() {
    const [width, setWidth] = useState(window.innerWidth);
    const breakPoint = 700;
    useEffect(() => {
      const handleResizeWindow = () => setWidth(window.innerWidth);
      window.addEventListener("resize", handleResizeWindow);
      return () => {
        window.removeEventListener("resize", handleResizeWindow);
      };
    }, []);
    if (width > breakPoint) {
      return (
        <div className="navbar__links">
          ... // regular flat menu goes here
        </div>
      )
    } else {
      return (
        <Menu right width={"210px"} noOverlay>
          ... // hamburger menu goes here
        </Menu>
      );
    }
}
export default ResponsiveBurger;`

**Comment by negomi** [comment]
Hi @peyo, I haven't tested your code but it looks good, that is how I would suggest making a responsive menu.
