### ISSUE TITLE
Slide animation customization.

### ISSUE THREAD

**Issue by durr04** [negomi/react-burger-menu#287]
Hello,

I am sung the `slide effect` for `react-burger-menu`  from the `left ` side. Its working as expected. But currently its sliding the menu from the left of the screen. I want to make the animation 50px from the left side of the screen. I am trying using overriding the transition property as mentioned in your **[FAQ](https://github.com/negomi/react-burger-menu/wiki/FAQ)** questions. But still somehow its not working. 

Can you suggest some inputs on this?

**Comment by negomi** [comment]
Hi @durr04,

Do you mean you always want 50px of the menu visible, even when it's closed?

**Comment by JSteeleAZ** [comment]
@negomi I'm not sure if the OP wanted 50px always visible, but that is something I'm interested in also. I can probably figure it out, but if you have a quick suggestion, that would be super!

**Comment by JiayiZhaoUofT** [comment]
> Hi @durr04,
> 
> Do you mean you always want 50px of the menu visible, even when it's closed?

Hi Negomi, I am trying to make 50px of menu visible when it is closed. Could you please give me any hints about how to do it?

**Comment by negomi** [comment]
Hi @JiayiZhaoUofT,

You can achieve that with something like this:
```js
<Menu>
  // Regular menu items here
  <div className="always-visible">
    // Some always visible contents here
  </div>
</Menu>
```
```css
.always-visible {
    position: absolute;
    left: 100%;
    top: 0;
    bottom: 0;
    width: 50px;
    background: #373a47;
}
```

**Comment by JiayiZhaoUofT** [comment]
Hi Nogomi, Thank you very much for getting back to me, I will try it :)
