### ISSUE TITLE
Looking for a solution to achieve a certain sidebar functionality (picture included)

### ISSUE THREAD

**Issue by jacobgranberry** [negomi/react-burger-menu#289]
Hi there!

I am working on a project and hoping to recreate something like [this](http://puu.sh/CvTb8/d266e1f052.jpg) where each of the five icons pushes out a sidebar with unique information.  I'm a bit of a React noobie and wondering the best way to accomplish this, or if its even possible with the react-burger-menu.  Should I make the UI bar the parent component, and have the menuopen state on each icon?

Thanks for your help!

**Comment by jacobgranberry** [comment]
figured it out :)

**Comment by negomi** [comment]
Hey @jacobgranberry, glad you figured it out!

It sounds like you were on the right track - UI bar separate, then each icon should trigger the menu open state as needed (while disabling the default burger icon).

**Comment by jacobgranberry** [comment]
@negomi 
Yep thats pretty much what I did!  Thanks again for the great component
