### ISSUE TITLE
Can't get Link to work with scaleRotate.

### ISSUE THREAD

**Issue by HarleySalas** [negomi/react-burger-menu#291]
It should be noted that I'm also using react-scroll with the menu.

I absolutely love scaleRotate. I got everything up and running, menu closing on click and so fourth. However, when I decided to start using react-scroll with it, it simply would not work. If I change the import from scaleRotate back to slide and I remove the outer container ID ('App'), the smoothscroll works fine with the slide Menu. Could it possibly be that smoothscroll or Link will not work with outer containers?

Would really, appreciate the help!

`
import { scaleRotate as Menu } from 'react-burger-menu';
import { Link, animateScroll as scroll } from 'react-scroll';

class BurgerMenu extends Component {
  constructor (props) {
    super(props)
    this.state = {
      menuOpen: false
    }
  }

  handleStateChange (state) {
    this.setState({menuOpen: state.isOpen})
  }

  closeMenu (event) {
    this.setState({menuOpen: false})
  }

  toggleMenu () {
    this.setState({menuOpen: !this.state.menuOpen})
  }

  scrollToTop = () => {
    scroll.scrollToTop();
  }
  render() {
    return (
      <Menu
        isOpen={this.state.menuOpen}
        onStateChange={(state) => this.handleStateChange(state)}
        burgerBarsClassName={ "navbar__menu-icon" }
        pageWrapId={"page-wrap"}
        outerContainerId="App"
      >
        <span className="menu__text">Salas</span>
        <Link
          onClick={() => this.closeMenu()}
          to="welcome"
          className="menu__link"
          activeClass="active"
          data-word="WELCOME"
          spy={true}
          smooth={true}
          duration={500}
        >
        Welcome
        </Link>
        <Link
          onClick={() => this.closeMenu()}
          to="about"
          className="menu__link"
          activeClass="active"
          data-word="ABOUT"
          spy={true}
          smooth={true}
          duration={500}
        >
        About
        </Link>
      </Menu>
    );
  }
}

export default BurgerMenu;
`

**Comment by negomi** [comment]
Hi @HarleySalas,

Just had a look at react-scroll and I think your problem is that Scale Rotate has to set `overflow: 'hidden'` and `height: '100%'` on the wrapper elements, which is how it is able to show the rotated window.

A side-effect of this is that it won't be possible to scroll to other sections on the page, which is I assume what you're doing with react-scroll.

You could override these styles and then it would show your whole page as a long rotated window, but I'm not sure if that would produce the effect you want.

**Comment by LeroyHutchinsonJ** [comment]
I found a work around for this, I added 
```
 var scrollToBegin = () => {
    var intro = document.getElementById("introduction");
    intro.scrollIntoView({ block: "end", behavior: "smooth" });
  };
```

Into my nav bar component, then I set the function to call when the nav bar link button is pressed 
```
 <a className={`menu-item introduction`} onClick={() => scrollToBegin()}>
Press Me!
</a>
```

In the component I am trying to scroll to, I set the returned parent element id to "introduction", it worked for me
```
var Slideshow = () => {
  return (
    <Carousel id="introduction">
...
```
