### ISSUE TITLE
Elastic menu broken in IE 11 

### ISSUE THREAD

**Issue by sarahannnicholson** [negomi/react-burger-menu#292]
## Description

This library so far has been amazing, thank you for all your hard work! 

I noticed something in IE 11 (not sure if you support it) but all the other menus seem to work, so I am assuming so. 

The problem is, the elastic menu is visible when the menu is closed in IE. But only when there is not enough content in `<main id="page-wrap">`

### Steps to reproduce

In /example.js 
1. set `currentMenu: 'elastic'`
2. set `const menus = {
  elastic: {buttonText: 'Elastic', items: 1},
  bubble: {buttonText: 'Bubble', items: 1},
  push: {buttonText: 'Push', items: 1}
};
`
3. run npm start
4. Open localhost:8000 in IE

### Expected result

The menu should act like the others and not be visible when closed.

### Actual result

The elastic menu is showing even though it is closed.
![image](https://user-images.githubusercontent.com/10520771/51774972-f34cc500-20a8-11e9-9d58-bf180cf66e7b.png)

You can see when you resize the window, that when there is a scroll bar this issue goes away. I have also noticed that adding `overflow: scroll` on #page-wrap causes the issue to go away as well, with the added empty scrollbars on the screen.

**Comment by negomi** [comment]
Hi @sarahannnicholson, thanks for the detailed report!

I haven't put too much effort into making sure this component works as far back as IE11, but if there's an easy fix for this, I'd be happy to implement it.

I'd be hesitant to add `overflow: scroll` because it would likely be annoying for most people to suddenly have permanent scrollbars appear. Does `overflow: auto` also solve the problem? (Asking because I don't currently have an easy way to test this in IE11 myself.)

**Comment by sarahannnicholson** [comment]
Hey @negomi, that's totally understandable, IE 11 is pretty ancient at this point. In the meantime, I have just hidden the menu on IE. 

To answer your question,
`Overflow: auto` is already set on the `#page-wrap` because of this in the .less file 
```
main {
  height: 100%;
  padding: 3em 2em;
  text-align: center;
  background: #b4bad2;
  overflow: auto;
}
```
I mean, the regular demo you have works because the page has scrollbars, its only when the page isn't scrollable. But I completely understand if IE 11 isn't fully supported, after all it only appears to be the elastic menu on an old browser, on non scrollable pages.
