### ISSUE TITLE
Menu won't close when overlay is clicked

### ISSUE THREAD

**Issue by huttj** [negomi/react-burger-menu#294]
I am using the menu in Cordova, and I re-enabled touch, which might have caused this issue. However, tapping the overlay would trigger close, but the sidebar would not close because it read it as a touch.

I had to add `this.setState({ touchIdentifier: null });` to `overlayClicked()` to get it to work, properly.

For my use case, I'd prefer to be able to enable touch on iOS, and have the sidebar close when the overlay is clicked.

**Comment by negomi** [comment]
Hey @huttj,

I've not used Cordova, but are you saying that the menu doesn't close because the overlay is listening for a click event, but is receiving a touch event instead?

Is this just a problem for the overlay, or do the burger/cross buttons have the same issue?

**Comment by negomi** [comment]
Ok cool, I'll leave this open as an enhancement to look into sometime, as I'm not sure what the best fix would be without some investigation.

I'm glad you found a workaround for the moment :)
