### ISSUE TITLE
How would I style with Tailwind CSS

### ISSUE THREAD

**Issue by ashpreetbedi** [negomi/react-burger-menu#297]
Hi,

What would be the best way to style this with [Tailwind CSS](https://tailwindcss.com/docs/what-is-tailwind/) ? I can't get the `bodyClassName/burgerBarClassName`... to work :(

I tried a bunch of different classes `<Menu menuClassName="h-4 w-4 bg-black" bodyClassName="h-4 w-4 bg-black" burgerBarClassName="h-4 w-4 bg-black">` but can't get it to work, is there an example I can follow?

**Comment by negomi** [comment]
Hi @ashpreetbedi,

That looks correct to me. I just tried one of your examples, and when I pass `burgerBarClassName="h-4 w-4 bg-black"` as a prop, I get these classes rendered on the burger bars:

![screen shot 2019-02-04 at 7 52 36 pm](https://user-images.githubusercontent.com/3727684/52252329-bd80bb00-28b6-11e9-983c-c7bb42eaa757.png)

Are the classes not being applied at all, or are the styles being overridden by something else? Unless you were using an extremely old version of the menu, I can't think what else could be wrong.

If you're still stuck, feel free to push some code up to a repo reproducing this and I'll help you figure out what's wrong.

**Comment by ashpreetbedi** [comment]
Thanks @negomi, I'll take the next hour to work through this and reply back.

**Comment by ashpreetbedi** [comment]
for some reason I still was unable to get the different classes to work. Most likely because my component is structures like:
```
App Component 

<div id="app">
  <div id="nav">
    <div id="upper-nav">
      <Menu ...>
    </div>
    <div id="lower-nav">
        ....
    </div>
  </div>
</div>
```

But, I can get the styles to work - i'm going to use the javascript styles and luckily they've got amazing type support making it a lot easier. Thank you!

**Comment by negomi** [comment]
Ok, glad you have a workaround :)
