### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by douglasrcjames** [negomi/react-burger-menu#298]
I am trying to add a drop down menu to the sidebar when it is popped out. 
Such as " Login || Register || More > [ About || Contact ||  F.A.Q ] "

What's the easiest way to do this?

**Comment by negomi** [comment]
Hi @douglasrcjames, you can pass any component you like as a child of the menu, so any dropdown menu from a library or one that you implement yourself should just work.

**Comment by douglasrcjames** [comment]
Okay thanks, that's a good call, I'll try that!

**Comment by mujtaba-1214** [comment]
any example of drop down in react burger menu

**Comment by negomi** [comment]
@mujtaba-1214 there are a a few tutorials around (I don't know exactly what you want but maybe something like https://medium.com/@vayamjain/making-a-nested-sidebar-menu-in-react-f8595031995e), so if you can build a regular dropdown, you can just render it as a child of react-burger-menu.
