### ISSUE TITLE
Is there a way to swipe open menubar on mobile touch devices

### ISSUE THREAD

**Issue by ashpreetbedi** [negomi/react-burger-menu#299]
I would love to be able to open the sidebar with swiping left to right on mobile devices, is that possible?

Thanks!
Ashpreet

**Comment by negomi** [comment]
No but I love that idea! I'll try to look into adding it at some point :)

**Comment by ashpreetbedi** [comment]
It would be a game changer :) Thank you for building this though, I was able to get it to work and its so smooth!

**Comment by heshamelmasry77** [comment]
yeah we really need this feature

**Comment by kenfehling** [comment]
Wouldn't that activate the back button behavior on mobile browsers though?

**Comment by pashtet422** [comment]
i wanna this feature too!

**Comment by tky5622** [comment]
I really need it !

**Comment by Stophface** [comment]
This should be pretty straight forward with this library https://github.com/FormidableLabs/react-swipeable

Simply implement it here https://github.com/negomi/react-burger-menu/blob/main/src/menuFactory.js on the `<div />` with the class `bm-overlay`.
