### ISSUE TITLE
Cannot find module 'react-burger-menu' from...

### ISSUE THREAD

**Issue by Fabioloza** [negomi/react-burger-menu#3]
I've installed this module:
npm install react-burger-menu --save

When I try building my project after requiring it, I get:
_Cannot find module 'react-burger-menu' from....[location]_

I can install other modules and require them just fine - it's only this one which breaks the build process. Any ideas?

Thanks

**Comment by sotojuan** [comment]
Hi. I just had this problem too. Looking at the `package.json`, the entry point for the component seems to be `src/ReactBurgerMenu.js`—but that file doesn't exist. In the `src` directory there's a `BurgerMenu.js` file. Maybe that should be the entry point?

**Comment by Fabioloza** [comment]
Yeah, you're right...! Looks like ReactBurgerMenu.js has been left out of the commit. As setting the entry point to BurgerMenu.js obviously conflicts because it doesn't follow React framework requirements...

@negomi - could you please check if you have a quickfix for this? We'd love to use your plugin.

Thanks

**Comment by sotojuan** [comment]
Yeah, I really like this component and want to use it on a current project, but (and I don't want to sound rude) it just doesn't work out of the box or even with some fiddling.

**Comment by sotojuan** [comment]
Upon further experimentation, it seems that after fixing the misspelled name error, the SVG animation code throws an error. Luckily enough I was only going to use the "slide" effect, so I just deleted everything that has to do with SVG animations and got my slider working.

**Comment by Fabioloza** [comment]
@sotojuan did you fix the error by renaming the file or by changing the entry point in the package.json? Is there anything else that you had to tweak to get this to work? Ta for the feedback btw!

**Comment by sotojuan** [comment]
I actually ended up making a lot of edits, but [this](https://github.com/sotojuan/coffee-timers/tree/master/client/scripts/components/Menu) is what I used to get a working slider menu. Extra styles [here](https://github.com/sotojuan/coffee-timers/blob/master/client/stylesheets/menu.scss).

**Comment by Fabioloza** [comment]
Legend - will take a look. So to clarify - you did have to edit quite a lot of the source, and this plugin isn't actually React "ready"?

**Comment by sotojuan** [comment]
Well, the SVG animations simply don't work (forgot what the error I got was). The rest of the code I modified was mostly my own style and preferences.

**Comment by sotojuan** [comment]
By the way, I heavily modified the code so it probably won't be as useful now. If still want the "old" version, it's [this](https://github.com/sotojuan/coffee-timers/tree/ca9c0963f8c97e5eef223df72147b3449789214a/client/scripts/components/Menu) one.

**Comment by Fabioloza** [comment]
Thanks. Although I've decided to use this menu instead: https://mango.github.io/slideout/ If I'm required to manually hack this one to make it work I'll rather custom fit one in React that at least has touch/gesture controls baked in.

Thanks again for the suggestions @sotojuan !

**Comment by garrettguy457** [comment]
This is still broken :( Though it seems like it might have something to do with React-kit. I am going to see if I can fix anything and make a PR, but might have no luck.

**Comment by sylphdesign** [comment]
I manually downloaded this version https://github.com/negomi/react-burger-menu/releases/tag/v1.0.1 and was able to load it locally. I may try to create a fork of this since there seems to be a lack of support.

**Comment by negomi** [comment]
Sorry, I've only just seen this. The generated entry point in the package.json was wrong. It should have been using the transpiled `lib/` directory instead.

I've fixed that, tested the component in another app and it works now.
