### ISSUE TITLE
document.activeElement not defined in IE11

### ISSUE THREAD

**Issue by Sebastiansc** [negomi/react-burger-menu#300]
Error:  unable to get property 'blur' of undefined or null reference.

```ts
document.activeElement.blur();`
```

By default `document.activeElement` should return `document.body`. This is working fine on other browsers but it is `null` in IE11

**Comment by ajoshi0** [comment]
broken in release 2.6.0 https://github.com/negomi/react-burger-menu/commit/095605de825a36770757c996bc0ad85f8317b5cc

**Comment by negomi** [comment]
Fixed in v2.6.4
