### ISSUE TITLE
Gap when using pushRotate on right

### ISSUE THREAD

**Issue by sbardian** [negomi/react-burger-menu#303]
Gap on right while using pushRotate menu on right.  Seems to show up on your demo page as well. 

Settings: 
 - Right
 - pushRotate

**Comment by negomi** [comment]
Hi @sbardian,

Which browser are you using? Could you send a screenshot of the gap? I'm not seeing it in Chrome.

**Comment by sbardian** [comment]
Hmm you are right, not seeing it in chrome canary. It is there in FF and FF Developer Ed. Fix I submitted isn't there in either, but it maybe causing some other issues in chrome.

**Comment by sbardian** [comment]
I have updated the PR, but it still has issues, maybe you can see something I'm not.
