### ISSUE TITLE
How to remove outline on burger or cross click?

### ISSUE THREAD

**Issue by ashpreetbedi** [negomi/react-burger-menu#309]
Is there a CSS property for removing this outline on focus? When I click on the burger menu or the cross, this outline appears.

![image](https://user-images.githubusercontent.com/22579644/54499649-63214400-48d1-11e9-9a44-6254be5f6179.png)
![image](https://user-images.githubusercontent.com/22579644/54499656-6fa59c80-48d1-11e9-919f-42dd0cbae4af.png)

I'm using a customBurgerIcon and customCrossIcon. Here are my current styles:

```
const sideBarStyleLargeScreen: Styles = {
  bmBurgerButton: {
    position: "fixed",
    width: "1.8em",
    height: "1.5em",
    left: "1.2em",
    top: "1em",
  },
  bmBurgerBars: {
    background: "#00091E",
  },
  bmCrossButton: {
    width: "1.5em",
    height: "1.5em",
    top: "0",
  },
  bmCross: {
    color: "#0BBA7F",
    width: "3em",
    height: "3em",
    top: "0",
    paddingRight: "1.5em",
  },
  bmMenuWrap,
  bmMenu,
  bmMorphShape,
  bmItemList: {
    background: "#00091E",
    paddingTop: "5em",
    paddingLeft: "1.5em",
  },
  bmOverlay,
};
```

Thank you again for building react-burger-menu :) :) :)

**Comment by JSteeleAZ** [comment]
I wonder if you're being "attacked" by Chrome!  After a bunch of debugging, it turned out that Chrome wants to add an "outline" property to :focus elements:
![image](https://user-images.githubusercontent.com/4723429/54935013-b6e8ea00-4edc-11e9-83ca-19ea0110bf00.png)

We're using Material-UI, so I set the "root" property of "outline: 'none !important'" for the MuiList element and it removed the outlining!

**Comment by negomi** [comment]
Hey @ashpreetbedi, @JSteeleAZ is correct - you'll need to set the `outline` property to `none` if you want to disable this. It's there for accessibility reasons though, so if you remove it, your site won't be keyboard navigable.

**Comment by youngestdj** [comment]
Which of the bm classes has the outline? I can't seem to be able to find out which of the elements has the :focus
