### ISSUE TITLE
Custom Prop for `.bm-item` tabIndex

### ISSUE THREAD

**Issue by GYTO** [negomi/react-burger-menu#315]
I just started using this library and I mention that the first element of the `.bm-item-list` apply a tabIndex to the first child if `.bm-item` when the menu is open to `1`. Is it possible to overwrite this when the menu is open? I am passing a single Node and I don't need autofocus every time I open the menu.

**Comment by negomi** [comment]
@GYTO thanks for the suggestion, just added the `disableAutoFocus` prop in v2.6.6 https://github.com/negomi/react-burger-menu#focusing-the-first-menu-item

**Comment by GYTO** [comment]
@negomi thanks, works great!
