### ISSUE TITLE
Reveal animation not work properly

### ISSUE THREAD

**Issue by kozak-jeka** [negomi/react-burger-menu#318]
Hi! First of all, thanks for the library. I'm trying to use reveal burger menu with react router and I fell into a problem with animation of sidebar, for better understanding please checkout the video. My simple component looks like this:

```
render () {
        return (
            <Router>
                <div id="outer-container">
                    <Menu pageWrapId={"page-wrap"} outerContainerId={"outer-container"} noOverlay disableOverlayClick>
                        <Link to='/'>Home</Link>
                        <Link to='/'>test1</Link>
                        <Link to='/'>test2</Link>
                    </Menu>
                    <div id="page-wrap">
                        <Switch>
                            <Route exact path="/login" component={Login} />
                            <Route exact path="/registration" component={SignUp} />
                            <PrivateRoute exact path="/" ><Home /></PrivateRoute>
                        </Switch>
                    </div>
                </div>
            </Router>
        )
    }
```
As you can see, page-wrap is moving, but sidebar is not, what I am doing wrong?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49211750/55435314-4019b400-55a2-11e9-8d46-f6e70dfa3a93.gif)

**Comment by negomi** [comment]
Hi @kozak-jeka, I think the problem is that your page-wrap div is transparent.

This isn't a problem with most of the animations, but for reveal, the menu shows immediately, and the animation is applied to the page-wrap element, so it needs to have a background color set.
