### ISSUE TITLE
Menu opens the first time but not the second

### ISSUE THREAD

**Issue by meninoebom** [negomi/react-burger-menu#319]
I am using a custom icon to trigger the opening of the menu. Locally this works, but on Netlify the menu opens the first time the icon is clicked but will not open again even though I have verified that the menu is being rendered with prop 'isOpen' === true.  The transform just isn't firing. I would be extremely helpful for any advice  or ideas on how to troubleshoot this.

https://ourprism.netlify.com/1750874

**Comment by negomi** [comment]
Hey @meninoebom, it looks like your state isn't getting updated and passed down to the component correctly.

What does your `onStateChange` prop callback look like?

**Comment by meninoebom** [comment]
Hi @negomi, 
On which component is the `onStateChange` prop?

I've simply been logging this prop:
```
import { slide as SlidingMenu } from 'react-burger-menu'
...
const Menu = ({ data, isOpen }) => {
  console.log('isOpen', isOpen)
  ...
  return (
    <SlidingMenu
      isOpen={isOpen}
      styles={styles}
    >
    ...
    </SlidingMenu>
  )
}
```

**Comment by meninoebom** [comment]
Sorry, seeing that in the docs. WIll start there troubleshooting. Thank you.
