### ISSUE TITLE
customCrossIcon is not working

### ISSUE THREAD

**Issue by Babettestam** [negomi/react-burger-menu#322]
The customCrossIcon doesn't seem to work.
I'm also using the customBurgerIcon that works great, so I would expect the same implementation should work for the customCrossIcon. As you can see in the screenshots the className for customBurgerIcon is added and the customCrossIcon is not. Am I doing something wrong here?

I'm using version 2.6.9.

The code:
![Schermafbeelding 2019-04-23 om 20 17 24](https://user-images.githubusercontent.com/3521402/56605620-d9b60d80-6604-11e9-9a89-fe618c0d6d6f.png)

The output in my Chrome console:
![Schermafbeelding 2019-04-23 om 20 16 30](https://user-images.githubusercontent.com/3521402/56605619-d91d7700-6604-11e9-887c-4e42fd0057e0.png)

**Comment by negomi** [comment]
Hi @Babettestam, you are totally right, that's a bug.

I've just pushed a fix - if you upgrade to `2.6.10` this should work now. Thanks for the report!

**Comment by Babettestam** [comment]
@negomi Great, the fix indeed works. Thanks for the quick action!
