### ISSUE TITLE
navigation menu doesn't show up on menu right

### ISSUE THREAD

**Issue by Amahnui** [negomi/react-burger-menu#323]
I really appreciate the work you're putting in to maintain this library. But for some reason, only the overlay shows when to apply the 'right' attribute to the menu tag. i actually slides in from the right but the menu navigation links do not show up. i don't know if i has something to do with the inbuilt z index of the element or something else. please review this

**Comment by negomi** [comment]
Hi @Amahnui,

I'm not sure what's going on from your description. Are you able to paste your code/screenshots, or a link to a repo reproducing this problem?
