### ISSUE TITLE
FAQ edit

### ISSUE THREAD

**Issue by dumblole** [negomi/react-burger-menu#324]
I don't mean to be a stickler but in https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop
you should change the `setState()` in `toggleMenu()` so it refrains from using `this.state` since `setState()` is an async function and could cause some confusion to people new to React or unintended side effects.

**Comment by negomi** [comment]
Good catch, just updated the example. Thanks @dumblole!
