### ISSUE TITLE
Please Update README to Better Demonstrate How to Use Styling

### ISSUE THREAD

**Issue by pamelaabreu** [negomi/react-burger-menu#326]
As a new developer it took me more than three hours and with the help of an experienced developer to show the react-burger on my project. I had to search through many workarounds and at one point I started to look for another library to use. 

We realized the problem was that I wasn't passing the styles prop into the menu. I suggest updating the docs to better emphasize that styling **MUST** be passed for the component to render since this is not clear enough. 

One solution is to have have the styling information come earlier in the docs. Another solution is in the example of the react-burger menu being used at the top of the docs. You can create a better menu example to use and show what it looks like with the styles prop being passed.
 
Considering that the menu absolutely needs the styling to show up, this needs to be **emphasized** more. I really loved this library but it was a stressful experience that took longer to use the menu because of the passing of styling props.

Thank you.

**Comment by negomi** [comment]
Hi @pamelaabreu,

I'm sorry to hear it was a stressful experience! This is useful feedback though, thanks for taking the time to write it. I will add something to the docs to make it more obvious earlier on that you don't get the styles by default.

**Comment by Taslinda** [comment]
Hi @negomi, 
How to set up
transform: translate3d (300px, 0px, 0px);
transition: all 0.5s ease 0s;
on push animation? I have tried changing it on my own css but my css can't change it, I want to change the transform part: translate3d (150px, 0px, 0px);
please )-:

**Comment by negomi** [comment]
Hi @Taslinda, the `transform` styles are applied as inline styles, so you would need to use `!important` if you want to override them in CSS to get around the specificity issue.

**Comment by Taslinda** [comment]
But I have tried to give !important to my css but it still can't, and I try again using inline styles but I still can't, which is surprising when I try to add a color style: blablabla / or uses !important in inline style and I inspect elements , the color style will appear but nothing has changed from its appearance

**Comment by negomi** [comment]
Which element are you trying to add it to? This works:

```
.bm-menu-wrap {
  transform: translate3d(150px, 0px, 0px) !important;
}
```

I'm not sure exactly what you're trying to change with the transform though - as a warning, it is likely to break things.
