### ISSUE TITLE
customBurgerIcon FOUC

### ISSUE THREAD

**Issue by corysimmons** [negomi/react-burger-menu#328]
When I use the `customBurgerIcon` props I always get a flash of unstyled content (FOUC)...

How to get rid of it?

**Comment by negomi** [comment]
Hi @corysimmons,

I'm unable to reproduce this locally. Could you push some code up to a repo demonstrating the issue so I can look into it?

**Comment by corysimmons** [comment]
Actually I'm sorry.

When I made a reduced test case it turned out it was because [this sizing pkg](https://npm.im/react-resize-aware) I'm using is slow. 😬

**Comment by negomi** [comment]
Ah, no worries :)
