### ISSUE TITLE
latest menu overwrites onkeydown event listener of previous

### ISSUE THREAD

**Issue by kimchirichie** [negomi/react-burger-menu#329]
menuFactory.js L#189 `window.onkeydown = this.listenForClose.bind(this);` overwrites previous `window.onkeydown` and consequently fails to close upon escape key down.

**Comment by negomi** [comment]
Hi @kimchirichie,

Yep, I don't think there's any need for this component to overwrite that method completely. I will replace it with `window.addEventListener('onkeydown', () => ...)` when I get a minute.

Thanks for the report.

**Comment by negomi** [comment]
Fixed in `2.9.0`
