### ISSUE TITLE
docs don't say how to open the menu

### ISSUE THREAD

**Issue by mgenev** [negomi/react-burger-menu#33]
This plugin looks awesome, but I don't see a straightforward way to connect a button to the menu... and the example is convoluted, not a basic use case...

**Comment by negomi** [comment]
Hey @mgenev, do you mean open/close the menu with a separate button?

You can set the open/closed state when you render the component, as described here: https://github.com/negomi/react-burger-menu#open-state. The best way to control the menu with a separate button is to trigger a re-render when your button is clicked, passing the `isOpen` prop to determine whether it should be open or closed. Hope that helps.

I've tried to keep the examples minimal, but feel free to suggest simpler versions/file an issue about any that are confusing :)
