### ISSUE TITLE
How can I select first bmBurgerBars?

### ISSUE THREAD

**Issue by mhabel** [negomi/react-burger-menu#331]
I tried like this:

var styles = {
  bmBurgerButton: {
    position: 'fixed',
    width: '36px',
    height: '30px',
    left: '36px',
    top: '36px'
  },
  bmBurgerBars: {
    background: '#373a47'
  },
**'bmBurgerButton>span:firstChild': {
   backgorund: #00FF00
},**
  bmBurgerBarsHover: {
    background: '#a90000'
  },
  bmCrossButton: {
    height: '24px',
    width: '24px'
  },
  bmCross: {
    background: '#bdc3c7'
  },
  bmMenuWrap: {
    position: 'fixed',
    height: '100%'
  },
  bmMenu: {
    background: '#373a47',
    padding: '2.5em 1.5em 0',
    fontSize: '1.15em'
  },
  bmMorphShape: {
    fill: '#373a47'
  },
  bmItemList: {
    color: '#b8b7ad',
    padding: '0.8em'
  },
  bmItem: {
    display: 'inline-block'
  },
  bmOverlay: {
    background: 'rgba(0, 0, 0, 0.3)'
  }
}

<Menu styles={ styles } />

but doesn't work:

Do you know a better solution? Thanks a lot

**Comment by negomi** [comment]
Hi @mhabel, this isn't possible with inline styles, see https://stackoverflow.com/questions/25646683/how-to-add-nth-child-style-in-inline-styling

You would have to use CSS. Also watch out for your typo 'backgorund'. Hope that helps!
