### ISSUE TITLE
gap on right appears when closing slide menu (only Safari)

### ISSUE THREAD

**Issue by rkretch91** [negomi/react-burger-menu#332]
Hi everyone! Love the ease of this menu and library, but despite doing what research I could, a gap appears on the right of my page while using Safari - desktop and mobile (Chrome is fine) after closing the menu. 

Here is the page in case you feel intrigued to inspect ;) https://zealous-pike-163f63.netlify.com/

Thank you so much in advanced for any answers on this.

**Comment by negomi** [comment]
Hi @rkretch91, sorry for the delayed response. Are you still seeing this? I looked at your site and was unable to see any gap after closing the menu (in Safari 12.1.2).

**Comment by jchesterman** [comment]
@negomi I can confirm this is still happening on Safari - possibly only an issue on Mac/iOs?

I'm going to try to do a little debugging :)

**Comment by dylanjha** [comment]
@rkretch91 Thanks for reporting this, I'm seeing this issue too. @negomi @jchesterman were you able to find a work-around?

Thanks!

**Comment by cabdesigns** [comment]
Adding `overflow-x: hidden` to the page wrap element (e.g. #page-wrap) seemed to fix it for me.

**Comment by ntgussoni** [comment]
Im experiencing the same bug. Adding `overflow-x: hidden` does not seem to do the trick for me

**Comment by ntgussoni** [comment]
I had to do something like this: 

```javascript
onOpenBurger={state => {
                              if (state) {
                                this.setState({ openBurguer: true });
                                document.getElementById("container").style[
                                  "overflow-x"
                                ] = "initial";
                              } else {
                                this.setState({ openBurguer: false });
                                document.getElementById("container").style[
                                  "overflow-x"
                                ] = "hidden";
                              }
                            }}
```

**Comment by JonathanRosado** [comment]
Having exactly the same problem.

**Comment by MatthewThornton** [comment]
I am experiencing the same problem. I haven't found  solution yet.

**Comment by victorgarciaesgi** [comment]
Having the same problem on Safari for Mac and Iphone when the width is <~ 400px. Really infuriating

**Comment by victorgarciaesgi** [comment]
It has to be a Safari bug, has usual

**Comment by ghughes13** [comment]
Did we ever find a fix for this?
