### ISSUE TITLE
How to skip animation?

### ISSUE THREAD

**Issue by decimoseptimo** [negomi/react-burger-menu#333]
I'm using react-burger-menu in gatsbyjs, so the component has to re-render between pages. When it's open, you'll get to see the "slide-in" effect on every page change (e.g. using the browser back button).

Is there a way to skip the transition during the initial render?

> Note: If you want to render the menu open initially, you will need to set this property in your parent component's componentDidMount() function.

Is that sentence related to this use case?

**Comment by negomi** [comment]
Hi @decimoseptimo,

That's correct, to stop the animation happening on each mount, you would need to set the `isOpen` prop to `true`. I don't know exactly how your app is structured, but you would need to store the menu open state somewhere that persists between page changes, then look at that to determine whether the menu should render open or not.

**Comment by decimoseptimo** [comment]
In gatsby, `isOpen=true` keeps the menu open BETWEEN (re)renders. But upon FIRST render, it will re-open the menu (trigger the animation). I need way force the menu to (sometimes=page change) stay open.

**Comment by negomi** [comment]
Where are you storing the menu open state that forms the variable that you pass to `isOpen`?

If you can share your code I can take a look.

**Comment by decimoseptimo** [comment]
More or less, my `layout.js` component:
- reads `isOpen` from useContext
- renders <BurgerMenu isOpen={ctx.isOpen} />

Please take a look : https://github.com/decimoseptimo/test/tree/test-react-burger-menu

**Comment by negomi** [comment]
Can you include your menu implementation in your example?

**Comment by negomi** [comment]
Hi @decimoseptimo, I see what's going on now.

The menu did not provide a way to disable the animation, but I have just added a prop to do this: https://github.com/negomi/react-burger-menu#transitions (published in v2.6.11).

You will still have to figure out how to identify when the re-mount is due to a page change vs. some other reason, and use that to determine when to set `noTransition` to `true`.

Unrelated to the animation problem, you will also want to use `onStateChange` (https://github.com/negomi/react-burger-menu#transitions) and make sure that updates the `isOpen` in your context so everything stays in sync. There is an example of how to do this here: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop

**Comment by decimoseptimo** [comment]
> You will still have to figure out how to identify when the re-mount is due to a page change vs. some other reason, and use that to determine when to set noTransition to true.

I've managed that with reach router's location, and session storage. But this approach is not working because once `{noTransition=true}`:

1. Transition will be skipped on re-mount... ✓
2. ...But will remain skipped after re-mount ✗

Is there a way to set `noTransition=false` after `react-burger-menu` was mounted?

**Comment by negomi** [comment]
You could make a component to wrap the menu and hold the `noTransition` state and pass it down to the menu.

Then, in the `componentDidMount` method of that component, set the `noTransition` state to `false`.

**Comment by decimoseptimo** [comment]
I'm not sure if understand what this means
> Note: If you want to render the menu open initially, you will need to set this property in your parent component's componentDidMount() function.
AFAI can see, the menu only renders open `onLoad`, upon re-mounts it tranisions (animates).

I tried my best, bt couldn't make it work.
```js
useEffect(() => {
    if(noTransition) setNoTransition(false) //useState
  }, [])```
will trigger the animation immediately.

I already found a way to avoid the re-mount altogether. But for the sake of completeness, could you take a look and tell me whats'up? I did my try but failed.

**Comment by negomi** [comment]
It looks like you have an ordering problem, and `noTransition` is being set to `false` too early, so you still see the animation.

If you force it to update later with `setTimeout`, it works:
```
setTimeout(() => {
    if (noTransition) setNoTransition(false)
})
```

Disclaimer: I don't have enough familiarity with hooks to know if this is a correct way to solve this, but it does produce the effect you want :)

**Comment by decimoseptimo** [comment]
Ordering problem 🤔 hum, ok. So... useState produces a different result than componentDidMount in this case. Well your sugestion worked, i think i feel better. Thanks, you've been very helpful.
