### ISSUE TITLE
Close menu if active?

### ISSUE THREAD

**Issue by alexanderfountain** [negomi/react-burger-menu#336]
Wondering if there is a way to close the menu if the user clicks on the active menu item?

**Comment by negomi** [comment]
Hi @alexanderfountain, you would have to make the menu into a controlled component using the `isOpen` prop. An example of how to do that is here: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop
