### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by ClemMakesApps** [negomi/react-burger-menu#34]
Does this run on react native? I'm getting odd errors about snap.svg but it still did not work after importing that library

**Comment by negomi** [comment]
I know Snap.svg has caused some problems before, but I'm afraid I haven't tested this component on React Native. What error are you getting?

**Comment by ClemMakesApps** [comment]
It doesn't let me build after I import the library. Xcode gives me:

```uncaught error Error: UnableToResolveError: Unable to resolve module imports?this=>window,fix=>module.exports=0!snapsvg/dist/snap.svg.js from /Users/ClemMakesApps/Documents/react-burger-menu-native/node_modules/react-burger-menu/lib/menuFactory.js: Invalid directory /Users/node_modules/imports?this=>window,fix=>module.exports=0!snapsvg/dist/snap.svg.js```

**Comment by negomi** [comment]
We added a workaround for Webpack as [Snap.svg wasn't working with it](https://github.com/adobe-webplatform/Snap.svg/issues/341), and it looks like that's what's causing your error.

I'll look into it when I get some time, but this is the code if you want to try editing that bit temporarily: https://github.com/negomi/react-burger-menu/blob/master/lib/menuFactory.js#L169-L175

**Comment by matheuztavarez** [comment]
Did anyone got it to work with native? :/

**Comment by franciscop** [comment]
Also getting some trouble with the menu in Meteor:

```bash
Unable to resolve some modules:

"imports?this=>window,fix=>module.exports=0!snapsvg/dist/snap.svg.js" in
[REDACTED]/node_modules/react-burger-menu/lib/menuFactory.js (web.browser)
```

**Comment by negomi** [comment]
These errors should be gone with v1.8.0.

Not officially testing or guaranteeing support for React Native yet, but the code that was causing this particular error has now been removed :)

**Comment by GrolaElmahdi** [comment]
it work with react-native ?

**Comment by negomi** [comment]
@GrolaElmahdi no, but I am considering making a version compatible with React Native.

**Comment by MichelDiz** [comment]
@GrolaElmahdi very cool your project. I was researching about SVG and menus in RN. Having RN support is really interesting. If you can support React-Navigation it would be much more advantageous. They have a Drawer navigation that you can create Custom. The result would be exceptional because it would already support out-of-the-box, navigation.

I loved the effects you keep by default. Congratulations.

Cheers.
