### ISSUE TITLE
isOpen not working with React 16.9 ?

### ISSUE THREAD

**Issue by fleflochN** [negomi/react-burger-menu#340]
Hello,

I'm using the burger menu in a project for some months now and everything was working fine.
But few days ago I updated to React 16.9 (previously using 16.3) and now even if I try to toggle the menu when clicking on an item by passing the isOpen param to false it doesn't seem to work anymore.
Every other actions are working fine: I'm able to open the menu with the open button, closing it with the cross or clicking the overlay or even with the esc keycode. 
I'm even able to open or closing it by defaut by defining the isOpen param, but once the component is mounted it's like it doesn't use this param anymore.

I also made some minor CSS updates but since the menu seems to display correctly with the other actions I doubt it could be the problem.

Am I missing something here?

Thank you.

**Comment by fleflochN** [comment]
So, I figured out what was happening.
The problem lays on the componentDidUpdate method. You define a variable named wasToggled which check if the prop isOpen has changed (comparing it with the prevProp.
Since the opening of the menu doesn't change the prop I have to listen to onStateChange and update the isOpen from the parent component every time the menu itself change.
This cost an extra render but it seems to work.
This wasn't necessary before updating to React 16.9, does it has something to do with the deprecation of the componentWillUpdate lifeCycle?

**Comment by raskri** [comment]
Yes please fix @negomi, we need it to still be awsome!

**Comment by negomi** [comment]
Hey @fleflochN, is this still an issue?

I just tried to reproduce (with React 16.11) and it seems to be working for me.

**Comment by fleflochN** [comment]
Hey @negomi Nope it's working fine from my side with the extra trick I just did as mentioned earlier (listening to the onStateChange event).
@raskri where you able to do the same trick ? You should be able to do the same workaround.

**Comment by raskri** [comment]
OK, so I read the "[how-to](https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop)" and no need to workaround..
