### ISSUE TITLE
Need to handle onMouseOver event for custom burger icon

### ISSUE THREAD

**Issue by chukwuemeka** [negomi/react-burger-menu#344]
Hello,

I'm trying to switch the custom icon image on hover like the example below: 

    import React, { useState } from 'react';
    import './App.css';`
    import { slide as Menu } from 'react-burger-menu';

    function App() {
      const [imageSource, setImageSource] = useState('icon.png');
      return (

        <Menu customBurgerIcon={<img src={imageSource} />}
              onIconStateChange={(iconState) => 
                   setImageSource(iconState.isMouseIn ? 'icon-focused.png' : 'icon.png') }  >

          <a id="home" className="menu-item" href="/">Home</a>
          <a id="about" className="menu-item" href="/about">About</a>
          <a id="contact" className="menu-item" href="/contact">Contact</a>
        </Menu>
      );
    } 

    export default App;

In order to achieve this, I had to put in this caller line in the `onMouseOver` callback in `BurgerIcon.js`:

    if(_this.props.onIconStateChange) _this.props.onIconStateChange({isMouseIn: true});

..this in `onMouseOut` callback:

    if(_this.props.onIconStateChange) _this.props.onIconStateChange({isMouseIn: false});

and this in the createElement call in `menuFactory.js`

     onIconStateChange: this.props.onIconStateChange,

Is there some neater route to achieving this that I'm missing?
`

**Comment by negomi** [comment]
Hi @chukwuemeka, unfortunately I don't think there is a cleaner way currently. I can see why that would be useful though! I'll leave this open as an enhancement.

**Comment by chukwuemeka** [comment]
Alright! 🙂 
That means I may go ahead and implement as described above, right?

**Comment by negomi** [comment]
Yes, that's your best option for now.
