### ISSUE TITLE
bm-cross-button custom styling overridden by buttonWrapperStyle

### ISSUE THREAD

**Issue by kylestarr** [negomi/react-burger-menu#345]
I am unable to use custom styles in bm-cross-button as CrossIcon.js includes hardcoded style attribute buttonWrapperStyle.

Style Attribute
``` 
{
position: absolute;
width: 24px;
height: 24px;
right: 8px;
top: 8px;
}
```

/Users/kylestarr/Git/maguire/src/styles/global.scss:287.bm-cross-button
```
{
~~height: 20px;~~
~~width: 20px;~~
~~right: 20px;~~
~~top: 30px;~~
}
```

**Comment by negomi** [comment]
Hi @kylestarr, unfortunately you will have to use !important if you want to target `.bm-cross-button` styles with Sass.

**Comment by kylestarr** [comment]
Done and done.
