### ISSUE TITLE
Show Confirm before close

### ISSUE THREAD

**Issue by 0xori** [negomi/react-burger-menu#347]
Hi, I'm trying to show a confirm that will prevent the menu to close on overlay click.
I tried to use the `onStateChange` to show a confirm, but it's called after the internal state has already changed. 
Is there anything like `onBeforeStateChange` or `onOverlayClick` that can prevent the internal state change?
Is it possible that the menu state will be 100% controlled? because right now the overlay click is managed internally.

**Comment by negomi** [comment]
Hi @0xori, yep, there isn't anything like `onBeforeStateChange` unfortunately. There is `disableOverlayClick`, which can accept a function - you might be able to get somewhere with that depending on what you're trying to do.

**Comment by behnazbgh** [comment]
Hi @0xori,
did you manage to find a way for this issue?
actually I am having same issue.
thanks for helping

**Comment by negomi** [comment]
https://github.com/negomi/react-burger-menu/issues/387 provides a solution to this problem. Change available in `2.7.0`
