### ISSUE TITLE
cross button

### ISSUE THREAD

**Issue by trd-cuizonjesse** [negomi/react-burger-menu#349]
is it possible to put the cross button in overlay? and is it possible to override when overlay is clicked?
I'm using props to toggle the drawer

**Comment by trd-cuizonjesse** [comment]
also, can I hide scrollbar?

**Comment by negomi** [comment]
Hi @trd-cuizonjesse, 

> is it possible to put the cross button in overlay?

You could position the cross button with CSS to make it look like it's in the overlay, if that's what you mean.

> is it possible to override when overlay is clicked?

You can disable the overlay click so it doesn't close the menu, or remove the overlay altogether, depending on what you're trying to do: https://github.com/negomi/react-burger-menu#overlay

> can I hide scrollbar?

Which scrollbar do you mean? Inside the menu or the whole page? You can make scrollbars only show when necessary with `overflow: auto;` but would need to apply this to the element with the undesirable scrollbars.
