### ISSUE TITLE
how can i modfy the styles.css

### ISSUE THREAD

**Issue by quockhanh21299** [negomi/react-burger-menu#350]
first, your burger bar is great, but i'm running in trouble :((, it about styles.css
in brower inspect it show 
`<div class="bm-overlay" style="position: fixed; z-index: 1000; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.3); opacity: 1; transition: opacity 0.3s ease 0s;"></div>`
it not the styles.css i created
```
 .bm-overlay {
   height: 100%;
  }
```
 so how can i modfy this, thank you alot

**Comment by negomi** [comment]
Hi @quockhanh21299, if you are using CSS you would need to add `!important` to override the inline styles, like this:
```css
.bm-overlay {
  height: 100% !important;
}
```
