### ISSUE TITLE
Question : is it possible to have relative burger button position ?

### ISSUE THREAD

**Issue by Eric691983** [negomi/react-burger-menu#351]
When I scroll the page including the burger menu, the button follows the display of the content : it is displayed on top of the content, outside the navbar at the top of the page.
I'd like to include the button in the navbar and make it stay here.

Is there a property to do it ?
Or should it be a possible enhancement ?

I've tried modifying css but without success, it breaks the overlay for example.

**Comment by negomi** [comment]
Hi @Eric691983, do you mean you have a fixed top nav bar, and would like to put the burger icon inside it?

If so, this might help: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-have-a-fixed-header-but-its-scrolling-with-the-rest-of-the-page-when-i-open-the-menu

Let me know if this isn't what you mean though.

**Comment by Eric691983** [comment]
Hi @negomi, yes sorry for my colorful english, you're right, I meant this feature. Weird that I missed this question/answer on the faq. Thanks ! Cheers from Lyon
