### ISSUE TITLE
Consider using hooks

### ISSUE THREAD

**Issue by Ronkiro** [negomi/react-burger-menu#353]
Hooks basically make the code more legible and easier to maintain.

To help with future updates, slowly upgrading to use hooks would be a great idea.

**Comment by negomi** [comment]
Hi @Ronkiro, I totally agree!

This project is now almost 5 years old, and I'm afraid I don't have much time to work on it these days, so I'm unlikely to be able to prioritize this myself.

I will leave this open as an enhancement though - thanks for your suggestion 😃

**Comment by Jack-Aaron** [comment]
This worked for me:

[App.js]

function App() {

  const [isOpen, setIsOpen] = useState(false);

  function showSettings(event) {
    event.preventDefault();
    setIsOpen(true)
  }

  return (
    <div className="App">
       <Navigation />
      <Header isOpen={isOpen} showSettings={showSettings} />
      <Hero />
    </div>
  );
}

export default App;

[Sidebar.js]

import React from 'react';
import { slide as Menu } from 'react-burger-menu'

function Sidebar(props) {




    // NOTE: You also need to provide styles, see https://github.com/negomi/react-burger-menu#styling
    return (
        <Menu isOpen={false}>
            <a id="home" className="menu-item" href="/">Home</a>
            <a id="about" className="menu-item" href="/about">About</a>
            <a id="contact" className="menu-item" href="/contact">Contact</a>
            <a onClick={props.showSettings} className="menu-item--small" href="">Settings</a>
        </Menu>
    );
}

export default Sidebar;

**Comment by Ronkiro** [comment]
@Jack-Aaron this issue is about using hooks  in react-burger-menu's code, not inside users code.

Thanks for the contribution anyway :D

**Comment by negomi** [comment]
Fixed in `3.0.0`
