### ISSUE TITLE
How to do lazy loading 

### ISSUE THREAD

**Issue by joseph-vedadi** [negomi/react-burger-menu#356]
Base on examples  I import :
```js
import { push as Menu } from 'react-burger-menu';
```

I wonder how can I do lazy importing to split my code .. Thanks..

**Comment by negomi** [comment]
Hey, not sure what you mean - do you mean Webpack tree shaking?

**Comment by joseph-vedadi** [comment]
The component I use "react-burger-menu" is getting very big. and based on my understanding, if I lazy load the component, Webpack will break them up to smaller pieces and load them when it is needed. 
I wonder if it would apply to the case as well.

**Comment by pasleto** [comment]
> The component I use "react-burger-menu" is getting very big. and based on my understanding, if I lazy load the component, Webpack will break them up to smaller pieces and load them when it is needed.
> I wonder if it would apply to the case as well.

This might help you:

`import Menu from 'react-burger-menu/lib/menus/push';`

**Comment by Mukhammadali** [comment]
> The component I use "react-burger-menu" is getting very big. and based on my understanding, if I lazy load the component, Webpack will break them up to smaller pieces and load them when it is needed.
> I wonder if it would apply to the case as well.

You can use **React.lazy** or react-loadable for that, I guess
