### ISSUE TITLE
button srcolling

### ISSUE THREAD

**Issue by MASDXI** [negomi/react-burger-menu#357]
i have problem about button scrolling with page how to disable???

**Comment by negomi** [comment]
Can you post a link to some code which reproduces this problem?

**Comment by MASDXI** [comment]
thank for support fixed that problem rn. with css burger button position
absolute

ในวันที่ ศ. 31 ม.ค. 2020 11:31 Imogen Wentworth <notifications@github.com>
เขียนว่า:

**Comment by negomi** [comment]
Ok great!
