### ISSUE TITLE
Push - sidebars should push the main content aside.

### ISSUE THREAD

**Issue by billshannon** [negomi/react-burger-menu#361]
When implementing left and right sidebars is there a way to push the main content aside?

**Comment by hocineismail** [comment]
when i used pageWrapid push work well now, try to follow this structure
<div id="outer-container">
  <Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } />
  <main id="page-wrap">
    .
    .
    .
  </main>
</div>

**Comment by hocineismail** [comment]
when i used pageWrapid push work `well,` now try to follow this structure
`<div id="outer-container">`
`<Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container"} />`
`<main id="page-wrap">`
....... 
`</main>`
`</div>`

**Comment by negomi** [comment]
Hi @billshannon, 

Push should actually push the main content aside, yes. I haven't actually tried it with left and right sidebars though.

What problem are you seeing? If you can paste your code, I'll try to reproduce it.
