### ISSUE TITLE
Width prop broken on elastic menu

### ISSUE THREAD

**Issue by fredriknorlin** [negomi/react-burger-menu#362]
**Changing the prop `width` on the elastic menu from the default of 300 creates a gap in the menu background:**

The code:
```jsx
<Menu 
    right 
    width={ 500 }
    ...
/>
```
Creates the following result:

<img src="https://i.imgur.com/d6hWYyb.png" height="300x" />
<img src="https://i.imgur.com/dQ1gYff.png" height="300x" />

**I guess at least part of the problem is the hardcoded width on row 57 in [elastic.js](https://github.com/negomi/react-burger-menu/blob/master/lib/menus/elastic.js).**

**Comment by negomi** [comment]
Thanks for reporting this @fredriknorlin, it's fixed in 2.6.14 🎉

**Comment by fredriknorlin** [comment]
Perfect! Thank you! 🎉 @negomi
