### ISSUE TITLE
scaleRotate backs page to top, when menu is openned

### ISSUE THREAD

**Issue by Dolidodzik** [negomi/react-burger-menu#364]
Here's the code:
```
<div id="outer-container">

         <Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" }>
              // Those spans are scrolling to specific parts of conent
              <span className="first-option option"
                onClick={() => goToAnchor('welcome') }>
                Welcome!
              </span>

              <span href="/about" className="option"
                onClick={() => goToAnchor('about') }>
                Tech details!
              </span>

              <span href="/projects" className="option"
                onClick={() => goToAnchor('projects') }>
                My projects!
              </span>

              <span href="/contact" className="option"
                onClick={() => goToAnchor('contact') }>
                Contact me!
              </span>
          </Menu>

          <main id="page-wrap">
                  CONTENT CONTENT CONTENT
          </main>
</div>
```

I want to create effect like [on demo, for **scaleRotate**](https://negomi.github.io/react-burger-menu/) animation. Above you can see what I had tried. It seems to work, until user opens hamurget menu, then he got scrolled to the top (which is unwanted, what if user was reading sth, he missclick on hamburger, and he is scrolled to top). Other things are werid too, for example I can still scroll page content, when menu is opened. Do you think it is some mistake in my code, or an acctutal bug?

**Comment by negomi** [comment]
Hey @Dolidodzik,

The content should not be scrollable or jump back to the top of the page when you open the menu. Your code looks fine from what I can see though.

Are the correct styles applied when the menu is open? You can check that both the page-wrap and outer-container have `overflow: hidden;`.

If you can provide a repo with an example of the problem, I will try to help more.
