### ISSUE TITLE
Slidemenu

### ISSUE THREAD

**Issue by diedel** [negomi/react-burger-menu#365]
Hi,

Is it possible to implement a slidemenu or multiple page menu using react-burger-menu?

See as example https://www.primefaces.org/primereact/showcase/#/slidemenu, but with multiple back buttons to navigate to any of the previous pages.

**Comment by negomi** [comment]
Hi @diedel, definitely possible, just not natively.

react-burger-menu just provides a container you can put anything you like in, so if you built a component that had multiple pages of items and a back button like that, you could render it inside react-burger menu 🙂
