### ISSUE TITLE
Can't get button highlighting off burger and cross buttons

### ISSUE THREAD

**Issue by EliranGooner** [negomi/react-burger-menu#367]
Whenever I click the burger and cross buttons on my Mac they function fine but it adds to them a not-so-good-looking highlight that I wish I could get rid of.
I tried a few StackOverflow suggestions with no success yet. If anyone figured out this kind of problem that'd be greatly appreciated.

**Comment by CoopNich** [comment]
I'm having this same issue. Did you find a solution?

**Comment by amorote** [comment]
I was able to solve it by using SASS.
`.bm-burger-button {
  button {
    outline: none;
  }
}
`
The same goes with the close button
`.bm-cross-button {
  button {
    outline: none;
  }
}`

I hope it's not too late to help 😄

**Comment by EliranGooner** [comment]
@amorote  Thank you! I think I tried this once with no success but your suggestion inspired me to add the ever-important ```!important``` to the ```outline: none``` and now it works.
