### ISSUE TITLE
When I close the drawer It's returning to the head of the page

### ISSUE THREAD

**Issue by florianzemma** [negomi/react-burger-menu#368]
Hi !

I have installed the package everything is Ok except that when I close the drawer It's returning to the head of the page
.

I've put an anchor on a menu item when I click on the menu item on question It's going on the wright anchor but when I close the drawer It's returning to the head of the page .

Someone can help me please ?

**Comment by negomi** [comment]
Hey @florianzemma, are your menu items linking to new pages, or to ID elements on one long page?

If you can paste some code, I will try to help debug.
