### ISSUE TITLE
slide menu close so fast

### ISSUE THREAD

**Issue by behnazbgh** [negomi/react-burger-menu#369]
How can I decrease the speed of closing menu?
I want to achieve some behavior like the attached link,
is it possible?
https://codepen.io/juneveu/pen/WNvPMXG

thanks for helping

**Comment by negomi** [comment]
Hi @behnazbgh, yes you can change it for Slide: https://github.com/negomi/react-burger-menu/wiki/FAQ#can-i-change-the-transition-property-of-the-menu
