### ISSUE TITLE
before closing menu, add some animation

### ISSUE THREAD

**Issue by behnazbgh** [negomi/react-burger-menu#371]
Hi,
how can I add some custom class name before the menu closes?

thanks for helping

**Comment by FuadAliah** [comment]
Same problem here, Any advise?

**Comment by negomi** [comment]
Hey @behnazbgh, there isn't a way to do this currently, only after the state change has already happened.

Can you give some more detail on what you're trying to achieve?

**Comment by negomi** [comment]
This recent change should solve your issue: https://github.com/negomi/react-burger-menu/pull/388
