### ISSUE TITLE
Scale-Rotate Menu bugs out when one its items is a button with a scrollIntoView function attached to it

### ISSUE THREAD

**Issue by LeroyHutchinsonJ** [negomi/react-burger-menu#373]
On my webapp, I use the scale-rotate menu, in the menu I have a button that scrolls the page vertically.

This bug sorta came out of nowhere, my page was working fine about eight months or so ago, but recently for some reason when ever I click a button with a scrollIntoView function attached, the page shifts slightly to the left, other than scalePush, I dont seem to have this issue with the other menus.

This is the function attached to the button that is giving me this issue.

` var scrollToIntro = () => {
    var intro = document.getElementById("introduction");
    intro.scrollIntoView({
      block: "start",
      behavior: "smooth"
    });
  };`

**Comment by negomi** [comment]
Hey @LeroyHutchinsonJ,

Thanks for reporting. I was able to reproduce this with:
- Elastic
- Push
- Push Rotate
- Fall Down
- Reveal

I don't have an immediate solution (I'm actually not sure how possible it is to make browsers handle all of these things together smoothly), but I'll leave this open as a bug 😃

**Comment by LeroyHutchinsonJ** [comment]
Darn, but thanks for the reply!
