### ISSUE TITLE
Problems with the final render using elastic option

### ISSUE THREAD

**Issue by alejandrotoro** [negomi/react-burger-menu#375]
Hi @negomi first of all, thanks for this amazing library.

I'm having a problem with the `elastic` option:
![Captura de Pantalla 2020-05-06 a la(s) 10 25 12 a  m](https://user-images.githubusercontent.com/395062/81196011-235d6600-8f84-11ea-8f4a-a3e2c22f3404.png)

Versions:
`"@types/react-burger-menu": "^2.6.1"`
`"react-burger-menu": "^2.6.13"`
`"react": "^16.13.1"`

This happened on Mac OS 10.15.3 (19D76) and Chrome Versión 81.0.4044.129 (Build oficial) (64 bits)

**Comment by negomi** [comment]
Hi @alejandrotoro, can you paste your code too? Thanks!

**Comment by alejandrotoro** [comment]
Sure!
This one is for the menu:
```
    <SidebarMenu {...props} isOpen={true} noOverlay customCrossIcon={<FiArrowLeft color="#bdc3c7" size="36" />}>
      <h2 className="workspace-name" tabIndex={-1}>
        <span>{dashboardData?.workspaceName}</span>
      </h2>
      <SidebarButton name="Values" itemsArray={sidebarValuesData} depth={0} />
      <SidebarButton name="Categories" itemsObject={sidebarCategoriesData} depth={0} />
    </SidebarMenu>
```

And this one is for the container:
```
      <div id="outer-container">
        <Sidebar pageWrapId={'page-wrap'} outerContainerId={'outer-container'} />
        <main id="page-wrap" className="dashboard-container">
          <TilesContainer />
        </main>
      </div>
```

**Comment by negomi** [comment]
Hmm ok, your code looks correct.

The animated shape (the part missing in your screenshot) uses Snap.svg, so my guess is that the library is not being imported properly somehow.

If you can push some code up to a repo reproducing this, then I would be happy to take a look further.
