### ISSUE TITLE
Blue border around the menu

### ISSUE THREAD

**Issue by varunvenky99** [negomi/react-burger-menu#379]

**Comment by peyo** [comment]
Hello,

I've been searching the Wiki for a potential solution but haven't come across an answer yet. Is there a way to remove the blue border around the menu when it is opened?

![Screen Shot 2020-11-07 at 1 31 04 PM](https://user-images.githubusercontent.com/55764217/98451745-93000980-20fd-11eb-930b-64ca4a8d5d94.png)

Thank you.

**Comment by peyo** [comment]
It appears it's an accessibility feature built into the browser. I'll leave it as is.

[More reading about the blue border](https://medium.com/@ricardozea/how-to-remove-the-blue-border-outline-in-chrome-safari-and-dotted-line-in-firefox-edge-fe5e2155d44c)

**Comment by negomi** [comment]
Hey @peyo,

You're right, but it also shouldn't surround all your items like that.

I think this issue might explain what's going on: https://github.com/negomi/react-burger-menu/issues/411

**Comment by peyo** [comment]
Hi @negomi,

I see. Thank you for the link. I pass the links as direct children now.
