### ISSUE TITLE
Webpack Example

### ISSUE THREAD

**Issue by learntoswim** [negomi/react-burger-menu#38]
Hi there,

I'm hoping you can provide an example of how to integrate this into an existing Webpack setup using import-loaders (as suggested in your readme)?

Menu looks amazing!

**Comment by negomi** [comment]
Hey @learntoswim, as far as I remember, you just need to `npm install imports-loader --save-dev` and it should work.

I don't have a current example of using this with Webpack but I can create one to help with debugging if this isn't working.

**Comment by learntoswim** [comment]
Thanks, actually that worked brilliantly. Full disclosure, I'm all very new to React / Radium so I appreciate your time in responding. I'm also attempting to add this menu into the https://github.com/kriasoft/react-starter-kit project out of the box. I am receiving a Radium warning:

```
Radium: userAgent should be supplied for server-side rendering. See https://github.com/FormidableLabs/radium/tree/master/docs/api#radium for more information.
Either the global navigator was undefined or an invalid userAgent was provided. Using a valid userAgent? Please let us know and create an issue at https://github.com/rofrischmann/inline-style-prefixer/issues
```

This also occurs without the export withStyles line (straight export default Menu)

```
# ./src/components/Menu/Menu.js
import React, { Component, PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Menu.scss';
import BurgerMenu from 'react-burger-menu';

class Menu extends Component {

  static propTypes = {
    side: PropTypes.string.isRequired,
  }

  render() {
    const SlidingMenu = BurgerMenu.slide;
    return (
      <div className={ this.props.side }>
        <SlidingMenu id="slide" pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } left>
          <a key="0" href=""><i className="fa fa-fw fa-star-o"></i><span>Favorites</span></a>,
          <a key="1" href=""><i className="fa fa-fw fa-bell-o"></i><span>Alerts</span></a>,
          <a key="2" href=""><i className="fa fa-fw fa-envelope-o"></i><span>Messages</span></a>,
          <a key="3" href=""><i className="fa fa-fw fa-comment-o"></i><span>Comments</span></a>,
          <a key="4" href=""><i className="fa fa-fw fa-bar-chart-o"></i><span>Analytics</span></a>,
          <a key="5" href=""><i className="fa fa-fw fa-newspaper-o"></i><span>Reading List</span></a>
        </SlidingMenu>
      </div>
    );
  }
}

export default withStyles(Menu, s);
```

**Comment by texttechne** [comment]
As the warning points out, this is a server side rendering problem: Radium cannot figure out on the server which user agent is being used (this info is used to determine appropriate vendor prefixes). You have to provide something along these lines:
```
<App radiumConfig={{userAgent: req.headers['user-agent']}} />
```
Unfortunately the `<App>` component seems to be buried in [routes.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes.js#L24) which in turn is used by client (no request object available and no radiumConfig needed) and server (this is when you need to provide it). Not a biggie though...

Anyway, not a problem with react-burger-menu and nothing actionable left to do for @negomi.

**Comment by learntoswim** [comment]
Thank you, @texttechne.
