### ISSUE TITLE
Disable closing the menu by clicking the content part?

### ISSUE THREAD

**Issue by jeongmincha** [negomi/react-burger-menu#380]
I want to use this library by setting 'reveal' animation, and I want to set the main content and sidebar menu stay unless I clicked the hide/show menu button.

Is it possible while using this library?
What options do I need?

**Comment by negomi** [comment]
Hey @jeongmincha, you can pass [`noOverlay`](https://github.com/negomi/react-burger-menu#overlay) if you want to be able to interact with the main content while the menu is open.
