### ISSUE TITLE
ScaleRotate not working properly when the menu is open

### ISSUE THREAD

**Issue by alejandrotoro** [negomi/react-burger-menu#381]
Closed side menu:
![Captura de Pantalla 2020-05-26 a la(s) 8 39 24 p  m](https://user-images.githubusercontent.com/395062/82966720-1f27d580-9f91-11ea-9290-e71288f673bc.png)

Opened side menu:
![Captura de Pantalla 2020-05-26 a la(s) 8 39 10 p  m](https://user-images.githubusercontent.com/395062/82966744-32d33c00-9f91-11ea-9f96-ceda5fd75210.png)

Even adding a 100% height to the outer-container it is not showing the elements with the full height of the screen.

This is the code where I'm rendering the menu:
```
<div id="outer-container">
  <SidebarContainer pageWrapId={'page-wrap'} outerContainerId={'outer-container'} />
  <main id="page-wrap" className="dashboard-container">
    <Dashboard />
  </main>
</div>
```

**Comment by negomi** [comment]
Hey @alejandrotoro, do the other menus have this problem too or is it just ScaleRotate?

**Comment by alejandrotoro** [comment]
@negomi only this one, I realized that I didn't read the documentation deeply, here is the solution for that: [My page content is still scrollable when the menu is open.](https://github.com/negomi/react-burger-menu/wiki/FAQ#my-page-content-is-still-scrollable-when-the-menu-is-open)
