### ISSUE TITLE
Project now locked to old LTS

### ISSUE THREAD

**Issue by annaemu** [negomi/react-burger-menu#386]
As part of https://github.com/negomi/react-burger-menu/commit/f8c7faeef300c71c3c42b5b9a478093857e3a1b4 it looks like the project was locked to an old LTS (10.*.*).

This has subsequently broken all of our builds that run on the 12.*.* LTS and were working fine before.

**Comment by negomi** [comment]
Hey @annaemu, literally just fixed in 2.6.17 - sorry about that 🙂

**Comment by annaemu** [comment]
> Hey @annaemu, literally just fixed in 2.6.17 - sorry about that 🙂

That's great, thank you!
