### ISSUE TITLE
Custom overlay click function

### ISSUE THREAD

**Issue by badtant** [negomi/react-burger-menu#387]
Hi,

I'm using the meny with my own state and would like to request an option to use a custom overlay click function.

I tried using the onStateChange function but that fires all the time and I only want to "catch" when the state changes without me handling it. So I figured it would be much easier if I could handle the overlay click myself also. Right now I have to disable it.

Thanks

**Comment by negomi** [comment]
Fixed by #388 

Change available in `2.7.0`
