### ISSUE TITLE
Cross Button CSS is overridden inline

### ISSUE THREAD

**Issue by pixelfreak** [negomi/react-burger-menu#389]
See screenshot below:

<img width="1476" alt="Screen Shot 2020-07-19 at 1 46 26 PM" src="https://user-images.githubusercontent.com/833548/87882560-4c5b9780-c9c6-11ea-89f0-5901fdfb37d7.png">

**Comment by negomi** [comment]
Hey @pixelfreak, yes, you'll need to use `!important` to override these with CSS.

Resizing the cross icon can be tricky because of how it's constructed, so you might prefer to use a custom icon. This issue has more info on that: https://github.com/negomi/react-burger-menu/issues/282
