### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by matejstrasek** [negomi/react-burger-menu#39]
A really nice feature of the library would be to integrate responsiveness to the menu. Keep the menu always open after certain screen width and on the other hand close it if the screen width is too small.

Something like [this](https://github.com/balloob/react-sidebar#responsive-sidebar).

**Comment by negomi** [comment]
Nice idea! I'm going to leave this open as I don't have time to work on it right now, but I agree it would be a great feature to add at some point.

**Comment by vizFlux** [comment]
Yea, would be great to include this feature.

**Comment by 2easy** [comment]
You can set `isOpen` and `noOverlay` props to `window.innerWidth > 768`. The only issue with this approach is that menu closes when user presses ESC key. If only there was the option `disableEscKey`, then you could set it also to `window.innerWidth > 768` and you have your responsiveness.

**Comment by marcospassos** [comment]
@2easy any update about that? I'm really interested in this feature.

**Comment by 2easy** [comment]
@marcospassos Yeah, no update. I didn't have time to rewrite test. I'll do it asap.

**Comment by wlingke** [comment]
Despite me also needing this, I actually disagree that this should be a feature. I really appreciate that react burger menu (RBM) does one thing really well and has a very clear use case. This feels like feature bloat to me.

Plus there are some weird CSS issues you'd have to think about. RBM works by leveraging CSS transforms. If you had some permanent menu that was always open, you'd have to write the rest of your content to account for this which is not natural.

IMO, a better structure is to re-factor out your actual menu content into a separate component. Then display it normally (using flexboxes or whatever) when you're in desktop mode. And when you're in mobile, display the icon that you click to show RBM. You can inject your menu into both your webpage layout and RBM easily this way.

**Comment by 2easy** [comment]
> If you had some permanent menu that was always open, you'd have to write the rest of your content to account for this which is not natural.

@wlingke In desktop mode menu is docked - there are no transforms. If you're talking about padding (so the menu does not cover the content) it must be taken into account either way. RBM can do it automatically, as some animations take content into div - it can be padded easily.

The update preserves old behaviour so it does not interfere with your implementation. Furthermore, it compresses it so you don't have to worry about which menu to display, additional components and so on.

As for updates for PR, I'm sorry it can't be done till mid february. Deadlines in work.

**Comment by seanseany** [comment]
Really looking forward to this feature!

**Comment by fgiarritiello** [comment]
Not having this feature is the only thing that is not making me use this menu. So I can't wait until it's available :)

**Comment by OKNoah** [comment]
The `closeOnEsc` boolean param seems vital. Not feature-bloaty at all, in fact if you want close on ESC functionality it's not hard to make yourself.

**Comment by trollboy** [comment]
in the interim, passing in
`<Menu styles={ styles } className={ "hidden-lg-up" } >`
 doesn't seem to work. Using bootstrap and react-strap. That bootstrap class should hide all objects unless on tablet or smaller. All it accomplishes is making the menu items themselves disappear.  The hamburger button is still there. I was hoping that would be a nice work around, but alas.

[react-strap] (https://reactstrap.github.io/)
[Bootstrap responsive tools] (https://v4-alpha.getbootstrap.com/layout/responsive-utilities/)

**Comment by negomi** [comment]
If you want to hide the burger icon for smaller screens, you could apply a similar hack using the `customBurgerIcon` prop: https://github.com/negomi/react-burger-menu#custom-icons

**Comment by trollboy** [comment]
Thanks for the response! I considered that, but I was trying to avoid doing responsive checking programatically preferring to opt for media queries and css.  Thanks, I'll play with this!

**Comment by HankSmith22** [comment]
This works in initial testing, might be a good start. Menu throws uncaught errors when using push and initialized to open=true. No solution for esc key though.

```
...
import { push as Menu } from 'react-burger-menu'
const mql = window.matchMedia(`(min-width: 800px)`);

export default class App extends Component {
	constructor(props) {
		super(props);

		this.state = {
			mql: mql,
			menuIsOpen: false //Menu bugs out if set to true initial on push mode
		}

		this.mediaQueryChanged = this.mediaQueryChanged.bind(this);
	}

	componentDidMount() {
		//Using componentDidMount because the menu bugs if setting isOpen = true before mounted
		this.setState({ mql: mql, menuIsOpen: this.state.mql.matches });
	}

	componentWillMount() {
		mql.addListener(this.mediaQueryChanged);
	}

	componentWillUnmount() {
		this.state.mql.removeListener(this.mediaQueryChanged);
	}

	mediaQueryChanged() {
		console.log("width below 800px", !this.state.mql.matches);
		this.setState({ menuIsOpen: this.state.mql.matches });
	}

	render(props) {
		return (
			<div id="outer-container">
				{/* Probably better off using your own button for menu open with this method (customBurgerIcon={false}) */}
				<Menu pageWrapId={"page-wrap"} outerContainerId={"outer-container"} isOpen={this.state.menuIsOpen} noOverlay> 
					<a id="home" className="menu-item" href="/">Home</a>
					<a id="about" className="menu-item" href="/about">About</a>
					<a id="contact" className="menu-item" href="/contact">Contact</a>
					<a className="menu-item--small" href="">Settings</a>
				</Menu>
				<main id="page-wrap">
					test content
				</main>
			</div>
		);
	}
}
```

scss
```
.bm-cross-button {
  height: 24px;
  width: 24px;
    @media screen and (min-width: $size-xs) {
    display:none;
    }
}
```

**Comment by dagi12** [comment]
My way to workaround esc key for responsive menu

import {slide as BurgerMenu} from 'react-burger-menu';

```
export default class MyBurgerMenu extends BurgerMenu {

    listenForClose() {
        console.log('catch')
    }

}
```

**Comment by 0aps** [comment]
I have a similar use case where this enhancement will be useful. I'm using the workarounds in the issue but would be nice to get it into the core.

**Comment by philmcp** [comment]
My work around for the ESC problem:

   

       componentDidMount() {
          document.addEventListener("keydown", (e) => this.handleKeyDown(e));
        }

	handleKeyDown(e) {
		if (e.keyCode == 27) {
			e.preventDefault();
			e.stopPropagation();
		}
	}`

**Comment by mfish0005** [comment]
Thanks all.  This was one of those times I found the solution to a problem in 5 minutes instead of 5 hours.

**Comment by negomi** [comment]
I have just published v2.3.0, which adds a [`disableCloseOnEsc`](https://github.com/negomi/react-burger-menu#close-on-escape) prop. This should provide a cleaner way to achieve what people have already figured out hacks for here, if anyone is interested :)

This, combined with the approach in https://github.com/negomi/react-burger-menu/issues/39#issuecomment-263148475 should be enough to make the menu responsive.

**Comment by imshuffling** [comment]
Has anyone managed to implement this successfully? 

@gsdnano - I've used your example which is great but I'm getting stuck on the 'window. is not a function' part.

`//const mql = window.matchMedia(`(min-width: 30em)`);
const mql = typeof window !== 'undefined' && window.matchMedia(`(min-width: 30em)`);

class Sidebar extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      mql: mql,
      menuIsOpen: true //Menu bugs out if set to true initial on push mode
    }
    this.mediaQueryChanged = this.mediaQueryChanged.bind(this);
  }

  componentDidMount() {
    //Using componentDidMount because the menu bugs if setting isOpen = true before mounted
    this.setState({ mql: mql, menuIsOpen: this.state.mql.matches });
  }

  UNSAFE_componentWillMount() {
    mql.addListener(this.mediaQueryChanged.bind(this))
  }

  componentWillUnmount() {
    this.state.mql.removeListener(this.mediaQueryChanged);
  }

  mediaQueryChanged() {
    console.log("width below 30em", !this.state.mql.matches);
    this.setState({
      menuIsOpen: this.state.mql.matches
    });
  }`

**Comment by rug1** [comment]
I've used @2easy suggestion with `noOverlay`, `isOpen` and `disableCloseOnEsc` props set to `window.innerWidth > 768`. However, the menu still closes when clicking outside the menu, I tried adding `disableOverlayClick` set to `false` but this doesn't seem to work if `noOverlay` is also set to `false`.

**Comment by negomi** [comment]
@rug1 you want the following values for those props:
```
isOpen={window.innerWidth > 768}
noOverlay={true}
disableCloseOnEsc={true}
```

**Comment by ivan-aksamentov** [comment]
Here is my attempt on responsive `react-burger-menu`:
https://github.com/ivan-aksamentov/example-react-burger-menu-responsive

In this example `react-burger-menu`, responds to a media query event by opening/closing the menu, disabling/enabling ESC key, overlay and mouse click-off.

It is similar to examples above, but I use [MediaQueryList.onchange](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/onchange) handler bound to an instance of `MediaQueryList`, which simple and allows to avoid the usage of unsafe React lifecycle methods.

Relevant code:
https://github.com/ivan-aksamentov/example-react-burger-menu-responsive/blob/afb048f27c4da50aee684e5730dbf2270bf2b6f1/src/components/App.js#L13-L24

Known issues:
 - In sticky (large viewport) mode, main contents is translated away from viewport and truncated, which is by-design for push-menu, but is not desirable in our case.
 - ESC key still closes the menu in sticky (large viewport) mode (see PR #317)

**Comment by darshantejani007** [comment]
As @ivan-aksamentov mentioned, this method has a **big issue** : In sticky (large viewport) mode, main contents is translated away from viewport and truncated, which is by-design for push-menu, but is not desirable in our case. Any workaround of this issue to keep the menu open stickily?

**Comment by negomi** [comment]
@darshantejani007 could you use the slide menu instead (when the menu is open all the time) and add a left margin to your content?

**Comment by darshantejani007** [comment]
@negomi yes, it seems to answer my question. Haven't tried this but it should work. Thanks and I will edit this comment once I get it working.
