### ISSUE TITLE
Burger button overlaps content

### ISSUE THREAD

**Issue by ghood97** [negomi/react-burger-menu#393]
The burger button is overlapping the content on my page (mainly when the screen is small). Is there a way to make the content and burger button keep their distance?

**Comment by negomi** [comment]
Hi @ghood97, this is determined by how you style the button.

If you're using fixed positioning like on the demo page, it will cover the content. A few suggestions to get around this:

* Put a colored background around the burger with some padding (the content would still disappear behind it, but it would look cleaner than if it's visible through the icon)
* Put the burger icon in a fixed nav bar, so the content disappears behind the whole bar, something like this:
  <img width="378" alt="Screen Shot 2020-07-26 at 2 10 20 PM" src="https://user-images.githubusercontent.com/3727684/88489571-cf8e6780-cf49-11ea-86ef-f9560053e59b.png">
* Don't use fixed positioning (this way the icon will just stay at the top of the page and not overlap any content as you scroll)
