### ISSUE TITLE
Creating a second expanding drawer/panel

### ISSUE THREAD

**Issue by moimikey** [negomi/react-burger-menu#397]
I've seen some issues posted/created, showing requests/questions about creating submenus. I had only seen them referencing hierarchical collapse/expand menus, but not extending the sidebar to multiple levels:

![image](https://user-images.githubusercontent.com/182661/91337119-e6221b80-e7a0-11ea-9153-fe1a853e403c.png)

is there an extensible way to achieve this using events?

**Comment by negomi** [comment]
Hey @moimikey,

There's nothing built in, but I think you could achieve something like this by passing submenu components inside the menu items, and then conditionally showing them on click.

They'd need absolute positioning, but I was able to achieve that kind of effect visually with an extra element and these styles:

<img width="1133" alt="Screen Shot 2020-09-02 at 8 14 31 PM" src="https://user-images.githubusercontent.com/3727684/92067573-80fa9700-ed59-11ea-918d-f42c9b9d0c86.png">
