### ISSUE TITLE
Menu not sliding open on mobile 

### ISSUE THREAD

**Issue by VladimirNeri** [negomi/react-burger-menu#398]
Everything seems to be working on desktop devtools however when I open the app on mobile the menu doesn't slide open.

**Comment by negomi** [comment]
Hi @VladimirNeri,

Which animation, and which mobile browser are you seeing this in?

I just tested with the demo page on iOS Chrome and Safari and wasn't able to reproduce.

**Comment by VladimirNeri** [comment]
Hi, 

It’s the Hamburger slide animation.  Basically the menu isn’t sliding open on IOS Chrome or Safari.  It looks fine on desktop but on mobile it’s kind of stuck.  I think it slides open but behind the carousel.  Here’s the link to the app…

https://vladimirneri.github.io/elemental/#/ <https://vladimirneri.github.io/elemental/#/>


Thanks in advance, 

Vladimir Neri

**Comment by negomi** [comment]
Ah I see. There's a lot going on in your layout so it's hard to tell what's going on. I would start by removing/reordering some elements to see if you can get any closer to the problem.

**Comment by VladimirNeri** [comment]
I fixed it.  I had overflow: hidden on my fixed navbar that was causing the problem.
