### ISSUE TITLE
How to make 2 different sidebars in the same page (left and right) using this library

### ISSUE THREAD

**Issue by simron-smwork** [negomi/react-burger-menu#399]
Hi, I am new to react. I want to make 2 different sidebars in the same page (left and right) using this library. How do I achieve that? (as there are predefined classes I am not able to make two different sidebars)

**Comment by negomi** [comment]
Hi @simron-smwork, welcome!

Two instances of the menu should be possible because classes don't have to be unique.

This issue was opened a while ago by someone else doing the same thing, maybe it can help you get started: https://github.com/negomi/react-burger-menu/issues/250
