### ISSUE TITLE
Is there a custom prop for onClick overlay?

### ISSUE THREAD

**Issue by karmingc** [negomi/react-burger-menu#401]
Hi, 

- using typescript

I am currently passing custom props down and am wondering if there is any custom props for closing on clicking the overlay. For e.g, for keydown, we have `customOnKeyDown` and I can pass my custom close func. 

Thanks!

**Comment by negomi** [comment]
Hey @karmingc,

Yes, I think https://github.com/negomi/react-burger-menu#close-menu-handler should do what you want.

If you use that prop, the menu will not close automatically, but your callback will be called instead so you can handle the close yourself.

**Comment by karmingc** [comment]
Hi @negomi,

Thank you for your response. Seems there's a typescript issue with that specific prop. Upon further reading in FAQ, I decided to use `onStateChange={(state) => this.handleStateChange(state)}` which triggers upon `state.isOpen === false`.

For e.g.
```
# closeMenu being a custom func
      onStateChange={(state) => {
        if (!state.isOpen) {
          closeMenu();
        }
      }}
```
Hope this helps for further use cases! Thanks for the library as well!
