### ISSUE TITLE
aria-hidden and visibility:hidden on closed menu

### ISSUE THREAD

**Issue by fabb** [negomi/react-burger-menu#404]
Currently on iOS with VoiceOver, the hidden elements of the menu are being highlighted when stepping through all elements when swiping with two fingers. To improve this, the menu should set `aria-hidden="true"` in the DOM when being hidden.

Related: even when the menu is hidden, the menu content is tabbable. The cleanest solution to solve this would be to set `visibility:hidden` on the menu when it is hidden (but not during hide animation, as it would blank out).

**Comment by negomi** [comment]
Fixed in `2.9.0`
