### ISSUE TITLE
Open State

### ISSUE THREAD

**Issue by msimonc** [negomi/react-burger-menu#41]
Thanks again for this,

for isOpen, if the default value is false,
```
is <Menu isOpen /> the same as <Menu isOpen={true}/> and

<Menu /> the same as <Menu isOpen={false}/>
```
can't get either working for some reason.  My current workaround (in an onClick handler for each \<a\> element) is:
```
		const clickEvt = new MouseEvent("click", {
			view: window,
			bubbles: true,
			cancelable: true
		});
		var crossButton = document.getElementsByClassName('bm-overlay');
		try {
			crossButton[0].dispatchEvent(clickEvt);
		} catch(err) {}
```
This closes the menu after an item has been selected.

**Comment by negomi** [comment]
Hey @msimonc, I'm not sure I understand your description - it seems like something didn't paste quite right? :)

**Comment by msimonc** [comment]
Fixed up the egregious original cut / pasting :)

**Comment by negomi** [comment]
Thanks :)

There was actually a bug preventing the `isOpen` prop from working as intended, but you're correct that that's how it should work. If you update to version 1.5.4, it should now be fixed.
