### ISSUE TITLE
Burger Menu Items - tabIndex - 1

### ISSUE THREAD

**Issue by Lulololu** [negomi/react-burger-menu#413]
Hello,

I've realized that, whether the side menu is OPEN or NOT OPEN, the tabIndex of the Menu Items still stay the same : -1.

Is there a way to change it to 0 when the menu is open, for accessibility purpose ?

Thanks a lot.

**Comment by negomi** [comment]
Hey @Lulololu,

The menu handles keyboard navigation internally with JavaScript, so it's still accessible without needing `tabindex="0"`.

It does only use the up/down arrow keys for navigating through the items though, and I can see why it might be useful to tab through them as well.

I'll try to add this soon if I get some time 🙂

**Comment by Banaanas** [comment]
Thank you, Negomi. :-)

**Comment by Lulololu** [comment]
Thank you, Negomi :-)

**Comment by negomi** [comment]
Fixed in `3.0.1`
