### ISSUE TITLE
Is it possible to have burger menu inside navbar 

### ISSUE THREAD

**Issue by wrushasendakhane** [negomi/react-burger-menu#414]
I am trying to have navbar inside react-bootstrap Navbar component

**Comment by negomi** [comment]
Hey @wrushasendakhane,

Yes this is possible, but you probably want to trigger the menu from a custom button, and not place the entire menu inside the nav bar.

To do this, you can [use a custom icon](https://github.com/negomi/react-burger-menu#custom-icons) and [control the menu state with the isOpen prop](https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop).
