### ISSUE TITLE
Dependency issue with React 17

### ISSUE THREAD

**Issue by azivkovi** [negomi/react-burger-menu#415]
Trying to install the package to React 17 project results with the following error message:

`npm ERR! Could not resolve dependency:
npm ERR! peer react@">=0.14.0 <17.0.0" from react-burger-menu@2.9.0`

**Comment by rafipiccolo** [comment]
I guess you only need to change thoses lines in this file :
https://github.com/negomi/react-burger-menu/blob/main/package.json

"peerDependencies": {
    "react": ">=0.14.0 <17.0.0",
    "react-dom": ">=0.14.0 <17.0.0"
  },

to

"peerDependencies": {
    "react": ">=0.14.0 <18.0.0",
    "react-dom": ">=0.14.0 <18.0.0"
},

Could you provide a pull request ? then the author will merge it ?

**Comment by negomi** [comment]
This would need https://github.com/negomi/react-burger-menu/issues/353 to be completed too, as well as just changing the peer dependency versions.

**Comment by rafipiccolo** [comment]
pull request done.
can some please merge it and publish the new package ?
I think that #353 is not required. (although it may be good)

**Comment by negomi** [comment]
Fixed in `3.0.0`
