### ISSUE TITLE
Could you elaborate on how to set width?

### ISSUE THREAD

**Issue by peyo** [negomi/react-burger-menu#416]
Hi Negomi,

Thanks for building the react-burger-menu!

Could you elaborate on how to set the width?

I see that this is how one would set width:
`<Menu width={ '20%' } />`

My codebase looks something like this:
```
<Menu right>
    <Nav.Link href="www.linkedinlink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            linkedin
        </div>
    </Nav.Link>
    <Nav.Link href="www.githublink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            github
        </div>
    </Nav.Link>
    <Nav.Link href="www.leetcodelink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            leetcode
        </div>
    </Nav.Link>
    <Nav.Link href="www.resumelink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            resume
        </div>
    </Nav.Link>
</Menu>
```
I tried adding `width` inside `<Menu right>`, but it does not work. I also tried playing around with the page wrapper and outer container, but that didn't work either.

Thanks,
Peter

**Comment by negomi** [comment]
Hey @peyo,

Do you mean it's just not changing the width at all?

I just tested on the demo site and was able to change the width with that prop:
<img width="1438" alt="Screen Shot 2020-11-05 at 8 06 04 PM" src="https://user-images.githubusercontent.com/3727684/98325004-9d59c080-1fa2-11eb-9f04-42d8a2a7aac4.png">

If it's just visually not what you expect, could there be something else going on with your layout?

**Comment by peyo** [comment]
That's interesting. I can change it through inspect > elements. But the width won't change through CSS.

Should this work?

```
.bm-menu-wrap {
  position: fixed;
  **width: 30%;**
  height: 100%;
}
```

**Comment by negomi** [comment]
You should change it using the prop rather than CSS. So your example above would look like this:

```html
<Menu width={'30%'} right>
    <Nav.Link href="www.linkedinlink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            linkedin
        </div>
    </Nav.Link>
    <Nav.Link href="www.githublink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            github
        </div>
    </Nav.Link>
    <Nav.Link href="www.leetcodelink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            leetcode
        </div>
    </Nav.Link>
    <Nav.Link href="www.resumelink.com" target="_blank" rel="noopener noreferrer">
        <div className="header__navLink">
            resume
        </div>
    </Nav.Link>
</Menu>
```

**Comment by peyo** [comment]
I see. That works. Thanks!

**Comment by negomi** [comment]
Awesome, glad it's working! 😄
