### ISSUE TITLE
Error in npm start

### ISSUE THREAD

**Issue by GustavoSouza12** [negomi/react-burger-menu#417]
After npm install and npm start im receiving this error, how can i fix it?

   <img width="800px" height="400px" src="https://user-images.githubusercontent.com/62048657/98433507-68369680-20a6-11eb-9c7d-0d03716cb602.png">

**Comment by negomi** [comment]
Hey @GustavoSouza12, you have to use Node 10 to run it locally.

It's an old project and doesn't work with newer versions I'm afraid!
