### ISSUE TITLE
Tab key closes menu

### ISSUE THREAD

**Issue by sacummings91** [negomi/react-burger-menu#422]
Version 2.9.0 introduced some code that now always closes the menu if you press the tab key. Here: https://github.com/negomi/react-burger-menu/blob/main/src/menuFactory.js#L287

If this is intentional, can we please at least get an opt out for this behavior since using tab is a very common way people navigate with keys. We have at least 3 projects that have broken because of this change.

PR where change was introduced: https://github.com/negomi/react-burger-menu/pull/409

**Comment by negomi** [comment]
Hi @sacummings91,

This was added intentionally to follow accessibility standards, but I agree the tab behavior specifically feels a bit jarring and unexpected. I'm happy to remove it.

I just pushed `2.9.1` which includes the fix.

Thanks for reporting!

**Comment by sacummings91** [comment]
@negomi I totally understand. Appreciate the quick resolution!
