### ISSUE TITLE
I would like to see a chunk of the menu when its closed.

### ISSUE THREAD

**Issue by neolectron** [negomi/react-burger-menu#427]
Hi,

I think with the current implementation it's not possible right now,
I have a working example of the expected look and behavior of what I'm talking about :
<https://dynamic-frame.ch/>

**Comment by negomi** [comment]
Hi @neolectron,

There isn't anything built in, but it's possible by adding the always visible part as one of the menu items, and styling it with absolute positioning.

Here is a demo of that with the menu open (I have just used an empty div but you can put whatever you like in it):

<img width="1440" alt="Screen Shot 2020-12-09 at 6 14 55 PM" src="https://user-images.githubusercontent.com/3727684/101712677-e7730d80-3a4a-11eb-9303-253b9e0caacb.png">

And closed:

<img width="1440" alt="Screen Shot 2020-12-09 at 6 15 07 PM" src="https://user-images.githubusercontent.com/3727684/101712869-551f3980-3a4b-11eb-8e7e-28170683af4f.png">

**Comment by neolectron** [comment]
great thanks, I guess its solved :)

**Comment by neolectron** [comment]
Great, I guess its solved :)
