### ISSUE TITLE
itemListElement does not exist in the TS definitions

### ISSUE THREAD

**Issue by mehmetnyarar** [negomi/react-burger-menu#429]
"react-burger-menu": "^3.0.2",
"@types/react-burger-menu": "^2.6.2",

**Comment by negomi** [comment]
Hey @mehmetnyarar, thanks for reporting this.

The type definitions are actually maintained separately over here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-burger-menu
