### ISSUE TITLE
Allow for font icon

### ISSUE THREAD

**Issue by franciscop** [negomi/react-burger-menu#43]
For instance, we want to use [Ionicons](http://ionicons.com/), so it would be great if react-burger-menu supported them. [Example usage](https://jsfiddle.net/franciscop/9qbd3293/) for ionicons:

```html
<span class="ion-android-arrow-back"></span>
```

This [could be similar to accepting an image for the close button](https://github.com/negomi/react-burger-menu/issues/40):

```jsx
<Menu customCloseFont="ion-android-arrow-back">
```

So then, if it's set, those classes are added to a simple `<span>` or `<i>`. This would make it also compatible with other fonts like [Bootstrap's font-awesome](http://getbootstrap.com/components/):

```jsx
<Menu customCloseFont="glyphicon glyphicon-remove">
```

Or [fontello](http://fontello.com/):

```jsx
<Menu customCloseFont="icon-close">
```

**Comment by negomi** [comment]
I like this idea. I wonder if having a more general prop for custom icons would be better, so you could just pass a string of HTML to use either an image or icon font, for example. I'll work on this when I get a chance.

**Comment by negomi** [comment]
This is now possible, from v1.6.0 (see https://github.com/negomi/react-burger-menu#custom-icons).
