### ISSUE TITLE
Bubble animation not working properly.

### ISSUE THREAD

**Issue by Regnar110** [negomi/react-burger-menu#430]
Hi everyone!
I have a question about bubble animation. I have a problem with this. I mean that there is lack of this bubbling effect in the first phase of the animation. I can't find any clues for this kind of problem. I would also like to mention that there is a similar problem with other animations like ScaleRotate. The first phase of the animation is missing. Can anyone help me with this? These animations look very good and I care about the whole animation.
Thank You :)!

**Comment by negomi** [comment]
Hi @Regnar110,

Is the problem only happening in your project, or can you reproduce it in the [demo page](http://negomi.github.io/react-burger-menu/) as well?

And which browser are you using?
