### ISSUE TITLE
Sticky elements unstick when opening a Push menu

### ISSUE THREAD

**Issue by beamercola** [negomi/react-burger-menu#435]
Having a hard time tracking it down.  Have you seen this before?

**Comment by negomi** [comment]
Hey @beamercola,

I think you might be having the same problem as this: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-have-a-fixed-header-but-its-scrolling-with-the-rest-of-the-page-when-i-open-the-menu

**Comment by beamercola** [comment]
Ah, I see.  Bummer, as a lot of my main content is sticky.  Thanks!
