### ISSUE TITLE
Multi-level menu?

### ISSUE THREAD

**Issue by QuanDev2** [negomi/react-burger-menu#436]
Hi.
Thanks for the library. It's very nice and easy to use.
However, I can't find a way to implement a 2-level sliding menu.
I have a main menu, and if user clicks on a menu item, I want another menu to slide in on top of the main menu.
Can you show me how to do that?
Thanks again.

**Comment by negomi** [comment]
Hi @QuanDev2, I'm not sure if this is exactly what you mean, but this question about submenus might be relevant: https://github.com/negomi/react-burger-menu/issues/397
