### ISSUE TITLE
How to remove the margin blue color when i click a specifc item 

### ISSUE THREAD

**Issue by danieltadresu** [negomi/react-burger-menu#444]
When i click a specific item inside of the Menu, appears a blue margin color, could i prevent this? how to remove this style?

Thanks a lot

**Comment by negomi** [comment]
Hey @danieltadresu,

Is it actually a margin or just an outline added when the element is focused?

I think this might be what you're describing: https://github.com/negomi/react-burger-menu/issues/309

If so, you can disable/restyle it using the [outline property](https://developer.mozilla.org/en-US/docs/Web/CSS/outline), but it's not recommended to remove it completely for accessibility reasons.
