### ISSUE TITLE
Customize position of menu

### ISSUE THREAD

**Issue by carterfa** [negomi/react-burger-menu#445]
The current burger menu opens up from the right or left but I would like the option for it to open from the bottom or top.  Any chance of getting this feature added or should I just try a work-around using the pre-existing styles?

**Comment by negomi** [comment]
Hi @carterfa,

No plans to add top/bottom functionality at this point.

If you can come up with a workaround just using styles, that's probably your best option.

There was an attempt a few years ago to add the functionality, but it wasn't fully working so the PR unfortunately never got merged: https://github.com/negomi/react-burger-menu/pull/198
