### ISSUE TITLE
Consider to combine the burger and close icons for even more mobile friendly UX

### ISSUE THREAD

**Issue by JPuzzled** [negomi/react-burger-menu#450]
First of all, thanks for the great work you've put in this project. The project came to my attention just recently. It is a nice feature that speeds up development for responsive web apps. 

Since most users are right-handed I'd like the burger icon on the bottom right because of the increasing mobile usage. That's easy using the provided CSS classes. The "right" attribute on the component takes care of showing the menu on the right.

Closing the menu can be achieved by clicking the close icon or anywhere outside the menu. I'd like to use the burger icon to close the menu as well. I think this will improve the UX on mobile devices for most (read: right-handed) users.

Example of combined burger/close button: https://codesandbox.io/s/lpo41x20kq

I can choose to:
- change the CSS for the close icon to look the same and appear at the same location as the burger menu,
- [hide the close icon](customCrossIcon), create a new close icon component and [handle the open state](https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop) myself,
- something great I did not think of.

What would you advise?

**Comment by JPuzzled** [comment]
Never mind. I somehow overlooked the paragraph about custom icons. This is just great. Thanks again. :)

**Comment by negomi** [comment]
Beat me to it 😄

Glad you found the custom icons!
