### ISSUE TITLE
No pageWrapId/outerContainerId supplied

### ISSUE THREAD

**Issue by krispyk84** [negomi/react-burger-menu#46]
Hi,

Not sure why this is happening but I keep getting a console warning "No pageWrapId supplied" and "No outerContainerId supplied", thus I cannot use the 'push' animation or any of the animations that require those definitions. Any idea why this might be happening?

Here's where I define them:

`<div id="outer-container">
        <Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } />
        <main id="page-wrap">`

Thanks!

**Comment by negomi** [comment]
Hi @krispyk84, that looks correct, assuming all the elements have closing tags etc. as well.

It's hard to say what's causing the error without a little more context. Are you able to push an example of the broken code somewhere I could look at it?

**Comment by krispyk84** [comment]
I fixed the bug. It was a child element structure thing. Thanks for the great menu!

**Comment by negomi** [comment]
Yay, glad to hear it!
