### ISSUE TITLE
Issues installing react-burger-menu with React 18

### ISSUE THREAD

**Issue by YinChuRijnaard** [negomi/react-burger-menu#464]
Don't know if the newly released version of React is the cause, but I have issues installing react-burger-menu. 

![Screenshot 2022-04-02 at 18 04 52](https://user-images.githubusercontent.com/65867865/161389296-be4f81fe-b9a7-406a-be83-05e4bf6c1cc1.png)

**Comment by winstonpurnomo** [comment]
Also having this issue.

**Comment by SpencerDedrick** [comment]
Same. Anyone find a solution?

**Comment by anandbaraik** [comment]
I'm facing same problem but didn't find any solution yet. if anyone found out. please let me know as well.

**Erorr i'm getting:**

-unable to resolve dependency tree, while resolving: react-portfolio@0.1.0
-npm ERR! Found: react@18.0.0

**Comment by YinChuRijnaard** [comment]
Haven't tried it again since I opened this issue. Will try again and share my thoughts.

**Comment by hari20493** [comment]
I have found a workaround for this,
Download the repo and edit the package.json file 
```
 "peerDependencies": {
    "react": ">=0.14.0 <18.2.0",
    "react-dom": ">=0.14.0 <18.2.0"
  },
```

then run 
`npm pack`

this will return a .tgz file in the directory, copy this to your project directory and edit your projects package.json file 

inside dependencies add
`"react-burger-menu": "file:/<your-directory>/react-burger-menu-3.0.6.tgz"`

now run npm install in your project and it will work.

**Comment by g11baldwin** [comment]
With npm 8.3.x and later the recommended workaround is to use overrides in the package.json. I used this (right after the dependencies {} ).  My early tests are working, but I didn't inspect in depth.  See this stackoverflow for details https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

  "overrides": {
    "react-burger-menu": {
      "react": ">=0.14.0 <19.0.0",
      "react-dom": ">=0.14.0 <19.0.0"
    }
  },

**Comment by g11baldwin** [comment]
And @negomi thank you for this package!

**Comment by negomi** [comment]
Hi folks, I have removed the upper React version limit in peer dependencies. It sounds like this should fix the issue.

**Comment by YinChuRijnaard** [comment]
Thank you! ✨
