### ISSUE TITLE
Dropdown Menu inside burger Menu options

### ISSUE THREAD

**Issue by santhoshkm2021** [negomi/react-burger-menu#466]
Hi , Is there any way to build a dropdown menu or a submenu inside a basic react-burger-menu. can you please help me out

**Comment by negomi** [comment]
Hi @santhoshkm2021, react-burger menu is really just a sidebar container, so you can put anything you want in it.

If you were looking for a package that supports multilevel nested menus out of the box, it looks like there are a few others that support it, e.g. https://www.npmjs.com/package/react-sidenav

Or this one, which you might be able to use inside react-burger-menu: https://github.com/gholme4/react-nested-menu

Good luck!
