### ISSUE TITLE
Error when i try with react project 

### ISSUE THREAD

**Issue by codescooper** [negomi/react-burger-menu#469]
Hello, thanks for this wonderful package, 
this is an error that i get when i launch npm to install in a react project , can you help me fix it ? 

`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'react-burger-menu@2.9.2',
0 verbose cli   '--save'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 11ms
6 timing config:load:builtin Completed in 11ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\project\path\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\lenovo\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\lenovo\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 23ms
19 timing npm:load:configload Completed in 23ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 4ms
22 timing npm:load:display Completed in 5ms
23 verbose logfile C:\my\computer\path\_logs\2022-05-23T12_13_08_453Z-debug-0.log
24 timing npm:load:logFile Completed in 8ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 37ms
28 timing arborist:ctor Completed in 1ms
29 silly logfile start cleaning logs, removing 3 files
30 timing idealTree:init Completed in 1740ms
31 timing idealTree:userRequests Completed in 5ms
32 silly idealTree buildDeps
33 silly fetch manifest react-burger-menu@2.9.2
34 silly logfile error removing log file C:/Users/lenovo/AppData/Local/npm-cache/_logs/2022-05-20T12_00_42_720Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\my\computer\path\_logs\2022-05-20T12_00_42_720Z-debug-0.log'] {
34 silly logfile   errno: -4048,
34 silly logfile   code: 'EPERM',
34 silly logfile   syscall: 'lstat',
34 silly logfile   path: 'C:\\Computer\\path\\AppData\\Local\\npm-cache\\_logs\\2022-05-20T12_00_42_720Z-debug-0.log'
34 silly logfile }
35 timing arborist:ctor Completed in 0ms
36 http fetch GET 200 https://registry.npmjs.org/react-burger-menu 3004ms (cache miss)
37 silly fetch manifest react@^18.1.0
38 http fetch GET 200 https://registry.npmjs.org/react 1446ms (cache updated)
39 silly fetch manifest react@>=0.14.0 <17.0.0
40 timing idealTree Completed in 6232ms
41 timing command:install Completed in 6247ms
42 verbose stack Error: unable to resolve dependency tree
42 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1399:25)
42 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1365:34)
42 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:951:11)
42 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:215:7)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:152:5)
42 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:157:5)
42 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:66:5)
43 verbose cwd C:\project\path
44 verbose Windows_NT 10.0.19042
45 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-burger-menu@2.9.2" "--save"
46 verbose node v16.14.2
47 verbose npm  v8.5.0
48 error code ERESOLVE
49 error ERESOLVE unable to resolve dependency tree
50 error
51 error While resolving: [1mproject[22m@[1m0.1.0[22m
51 error Found: [1mreact[22m@[1m18.1.0[22m[2m[22m
51 error [2mnode_modules/react[22m
51 error   [1mreact[22m@"[1m^18.1.0[22m" from the root project
51 error
51 error Could not resolve dependency:
51 error [35mpeer[39m [1mreact[22m@"[1m>=0.14.0 <17.0.0[22m" from [1mreact-burger-menu[22m@[1m2.9.2[22m[2m[22m
51 error [2mnode_modules/react-burger-menu[22m
51 error   [1mreact-burger-menu[22m@"[1m2.9.2[22m" from the root project
51 error
51 error Fix the upstream dependency conflict, or retry
51 error this command with --force, or --legacy-peer-deps
51 error to accept an incorrect (and potentially broken) dependency resolution.
51 error
51 error See C:\Users\lenovo\AppData\Local\npm-cache\eresolve-report.txt for a full report.
52 verbose exit 1
53 timing npm Completed in 6732ms
54 verbose unfinished npm timer reify 1653307988918
55 verbose unfinished npm timer reify:loadTrees 1653307988931
56 verbose unfinished npm timer idealTree:buildDeps 1653307990678
57 verbose unfinished npm timer idealTree:#root 1653307990679
58 verbose code 1
59 error A complete log of this run can be found in:
59 error     C:\my\computer\path\_logs\2022-05-23T12_13_08_453Z-debug-0.log
`

**Comment by negomi** [comment]
Hi @codescooper, it looks like you are using `react-burger-menu@2.9.2` which is not compatible with React 18. Can you try with the latest version?
