### ISSUE TITLE
icons only closed Enhancement

### ISSUE THREAD

**Issue by msimonc** [negomi/react-burger-menu#47]
Hi Imogen,

It would be nice if there was an option to "close" the (left) menu in such a way that the icons still show and are clickable.  I.e. it doesn't completely close / hide.

Thanks! Mark

**Comment by negomi** [comment]
I think someone asked for exactly this a while ago: https://github.com/negomi/react-burger-menu/issues/11

I'm not sure about merging it officially yet but I'll leave this here as an enhancement :)

**Comment by msimonc** [comment]
The navbar-extension looks good and is a good step in the right direction,

But I'd visualized the original left menu not fully hiding but remaining open enough to keep the icons showing.  Of course a hamburger would be added at top to fully open the menu.  

You might consider optionally replacing the X with a hamburger so that it stays in the same place both for opened and closed.

**Comment by negomi** [comment]
Ah, I see what you mean!

That could be useful, but would be very dependent on what you put in the sidebar, i.e. whether you're actually using icons. It'd also take more thinking to make it work with the cross and burger icon, as well as some of the more complex animations.

I think the specific nature of this means I'm probably not going to add it as a main feature for now, but I'll definitely bear it in mind for the future - thanks so much for the idea!
