### ISSUE TITLE
Horizontal placement options

### ISSUE THREAD

**Issue by jiku** [negomi/react-burger-menu#48]
What about adding horizontal placement? Not sure anyone needs that except me but have something going [here](http://github.com/jiku/react-burger-menu) (amongst other stuff) if you want to check it out. WIP. See issues. :)

**Comment by negomi** [comment]
Hey @jiku, nice! I love how it's working for Slide :)

I think the complexity of making this work for all the animations means I probably won't add it as a new feature of the main component, but if anyone asks about this functionality, I'll be sure to mention your fork!

**Comment by jiku** [comment]
Thanks! Yeah it's beyond me atm. :) Maybe I can backtrack after I'm done with my project and have some more experience with React, to do a full PR.
