### ISSUE TITLE
integration in dash-extensions

### ISSUE THREAD

**Issue by effatee** [negomi/react-burger-menu#484]
Hi,
Am I wrong in assuming that the react-burger-menu has been removed from dash-extensions ?
I am looking to use it in a plotly dash application, and have read [here](https://github.com/thedirtyfew/dash-extensions/issues/42) it could be imported from dash-extensions... This does not appear to be the case in the current version.

Would you have any suggestion about the shortest path allowing to use the react-burger-menu in a plotly dash application ?

Many thanks

**Comment by negomi** [comment]
Hey @effatee, I'm not familiar with dash-extensions so I have no idea I'm afraid. You might have more luck asking there directly.
