### ISSUE TITLE
Changing the `display` of `bm-item` in css does not reflect back

### ISSUE THREAD

**Issue by jmanacup** [negomi/react-burger-menu#487]
For some reason, changing the `display` of `bm-item` does not reflect back. It is still always `display: block`. Can anyone double check to see if this is only happening in my end?

_Originally posted by @jmanacup in https://github.com/negomi/react-burger-menu/issues/249#issuecomment-1472725214_

EDIT: I needed to add `!important` after changing the code to make it work. Is that how it is supposed to be?

**Comment by negomi** [comment]
Hi @jmanacup, if you're using CSS then yes, you would have to use `!important`. If passing styles as a JS object then it wouldn't be necessary.
