### ISSUE TITLE
defaultProps deprecation warning

### ISSUE THREAD

**Issue by stuartmemo** [negomi/react-burger-menu#488]
Using the `<Menu />` component results in the following warning:

`Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead`.

Example code:

```
import Menu from 'react-burger-menu/lib/menus/slide';

const MyMenu = () => {
    return <Menu right>...</Menu>
};
```

**Comment by jay-guro** [comment]
Hi, is this possible to implement? Seems like there isn't really anything we can do to mitigate on our end. Thanks in advanced!

**Comment by sahand-sn** [comment]
same error

**Comment by Nikolay-Tymoshchuk** [comment]
Will you make some update for fix this issue?

**Comment by tuxd** [comment]
How is this completed when nothing has changed?
