### ISSUE TITLE
React 15 - remove peerDependencies

### ISSUE THREAD

**Issue by bkniffler** [negomi/react-burger-menu#49]
Hey, would you mind removing peerDependencies so we can choose the appropriate react version ourselves? Many libraries turned their backs to peerDependencies now.

**Comment by negomi** [comment]
Hey @bkniffler! Yeah, I've just released v1.5.7 which no longer includes `peerDependencies`.

I started using them from React 0.14.x to warn people using React 0.13.x that this component wouldn't be compatible, but with the v15 release candidate and imminent switch to major versioning, I agree it makes sense to remove them at this point.

**Comment by vramana** [comment]
@negomi Can you please move react@0.14 and react-dom@0.14 to devDependencies??

In my project, I am switched to react v15. whenever I install a package, npm installs react 0.14 under react-burger-menu and a few other projects that declared react@0.14 as dependency. So, my webpack builds ends up with multiple copies of react. I found this https://github.com/npm/npm/issues/1341 after searching a bit. I don't know if it can be called a npm's bug.

**Comment by negomi** [comment]
Hi @vramana! I've now updated React to v15 so this should solve your problem.
