### ISSUE TITLE
Clicking on menu item does not close the menu

### ISSUE THREAD

**Issue by robrobac** [negomi/react-burger-menu#492]
I didn't find anything in the documentation, I may missed it.
When menu is open and user clicks on the navigation item, the menu should close, how to achieve that?

**Comment by guidra-rev** [comment]
@pinkpigeonltd How do you close the menu programmatically ?

**Comment by pinkpigeonltd** [comment]
The inbuilt toggleMenu function does that. The menu provides a context (here, ctx), so ctx.toggleMenu() is the function you need to call to close the menu from anywhere that the context is provided. (Make sure to wrap any part of your app that needs this context, in the context provider. Also ensure that you then import the context. Then you can call the function to close the menu)
