### ISSUE TITLE
Error loading Snapsvg using Webpack.

### ISSUE THREAD

**Issue by sylphdesign** [negomi/react-burger-menu#5]
there seems to be some issue with webpack and snapsvg. The error reads `Cannot read property 'on' of undefined`. I also followed this issue thread for solution: https://github.com/adobe-webplatform/Snap.svg/issues/341

However, I still am not able to get it to work. Any possible solution to replace `var Snap = require( "imports-loader?this=>window,fix=>module.exports=0!snapsvg/dist/snap.svg.js" );`

**Comment by negomi** [comment]
This issue is now fixed: https://github.com/negomi/react-burger-menu/commit/1b4a99906601c04d13c8ae27f13e77eaa1cc559a

**Comment by harryworld** [comment]
@negomi it actually goes to the catch path which says `Cannot find module` in my case. Does this change really work?

**Comment by negomi** [comment]
It has so far. Have you added `imports-loader` to your devDependencies?

**Comment by harryworld** [comment]
Yes, and I'm using your latest branch. I tried in another project and was able to make it work. I guess snap.svg is loaded by another loader (which was my case)

**Comment by negomi** [comment]
Ah, yeah that would break it. I'm not sure how to deal with that scenario. I don't like the `imports-loader` hack that's in place right now, but I don't know of a better solution without losing the Snap.svg dependency.
