### ISSUE TITLE
Space between url inputbox and page

### ISSUE THREAD

**Issue by samuelprokop** [negomi/react-burger-menu#506]
I have a weird blank space between browsers url inputbox and 'beginning' of my page. Has anyone met with that issue before/ knows how to solve it? I tried multiple browsers, and also when i try to inspect elements, it does nothing when i hover over that blank space. Its like my entire page containers is moved downwards, however i didnt have that issue when i was not using this menu, so i dont think that there is bug in my code, maybe i imported it incorrectly or stg. ( please help fellow react nerd, im getting desperate and my client mad:( )
<img width="1425" alt="Screenshot 2024-02-12 at 20 50 54" src="https://github.com/negomi/react-burger-menu/assets/156447089/ccf87a0b-211f-42c6-833c-6ef1a2e2e09c">

**Comment by samuelprokop** [comment]
thanks @sk0le for idea, i also needed to put it inside div and make height at 100

**Comment by wstenzel** [comment]
Can you send a photo of the code you used to fix this issue? I ran into it and can't figure out how to fix it.
