### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by coodeex** [negomi/react-burger-menu#507]
Are there plans to update the package to use _JavaScript default parameters_ instead of _defaultProps_?

**Comment by tkoolhoven2** [comment]
Have the same issue

**Comment by verhulstd** [comment]
same...

**Comment by sm3sher** [comment]
Considering that this repo seems unmaintained I would either switch to a more popular library or write my own little sidebar burger menu component.

**Comment by cgstaber** [comment]
same

**Comment by yilkur** [comment]
We are also receiving this warning.

**Comment by gitlep1** [comment]
Yea I receive the same warning. I love this package so would be a shame to have to use something different all because the owner doesn't update this.

**Comment by jhwang09** [comment]
+1

**Comment by rtconner** [comment]
Is this project maintained anymore? What is an alternative?

**Comment by saikrishnabanda5** [comment]
Same issue
![image](https://github.com/user-attachments/assets/49a96286-a359-4b18-a582-fb3e7f7ba1df)
