### ISSUE TITLE
Server Side Rendering Support on v1.6

### ISSUE THREAD

**Issue by adrianha** [negomi/react-burger-menu#52]
Hello,
I am facing issue for server side rendering using react-burger-menu version 1.6.
Here's the warning:
`warning.js?0260:45 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ition:opacity 0.3s, transform 0s 0.3s;" 
 (server) ition:opacity 0.3s, -ms-transform 0s 0.3`
@negomi

**Comment by adrianha** [comment]
@negomi

**Comment by adrianha** [comment]
any thought about this @negomi ?

**Comment by negomi** [comment]
Hi @adrianha, sorry for the late response! This sounds like something isn't working with Radium, which is responsible for applying prefixes to the menu styles. I'll look into it sometime in the next couple of days.

**Comment by thomasmodeneis** [comment]
I've ran into the same problem here :|

**Comment by negomi** [comment]
I've tried to reproduce this and can't seem to get the same error. What version of Radium is installed in your `node_modules`?

**Comment by negomi** [comment]
Ok, tried a slightly different setup and I managed to get the error.

I've just pushed a release (v1.8.1) which fixes it. Please let me know if it's still a problem :)

**Comment by Shadowman4205** [comment]
@negomi 
I am getting same error 

> warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) ition:opacity 0.3s, transform 0s 0.3s;" 
>  (server) ition:opacity 0.3s, -ms-transform 0s 0.3

I am using react isomorphic app. I have "react-burger-menu": "^1.10.14", any solution?

**Comment by Shadowman4205** [comment]
@negomi ok installed last version and its working
