### ISSUE TITLE
Unable to close menu after clicking on link

### ISSUE THREAD

**Issue by srsjake** [negomi/react-burger-menu#56]
I'm using the menu within a "body" component that spans my whole page. I've added the menu as follows and I'm using react router.

```
var Example = React.createClass({
  showSettings: function(event) {
    event.preventDefault();
  },
  render: function() {
    return (
      <Menu right>
        <RadiumLink className="menu-item" to="/">Home</RadiumLink>
        <RadiumLink className="menu-item" to="/about">About</RadiumLink>
        <RadiumLink className="menu-item" to="/contact">Portfolio</RadiumLink>
        <RadiumLink className="menu-item" to="/contact">Contact</RadiumLink>
      </Menu>
    );
  }
}); 
```

and this is its parent

```
render: function() {
        return (
                                <div className="border" ref="frame">
            			<Example />				
				</div>
        );
```

If I click on a link, it loads the page just fine however, the menu remains open and I have to either use the close button or click outside the menu to close it. How can I get it to auto-close?

Thank you

**Comment by negomi** [comment]
Hey @srsjake,

You'll have to handle the open state of the menu manually in this case (see https://github.com/negomi/react-burger-menu#open-state).

Hope that helps!

**Comment by srsjake** [comment]
Heya @negomi,

Thanks for the response, forgive me but I'm new to React. Using the open state, I can check whether the state is open but how can I actually close the menu when an item is clicked?

My initial thought was to add an onClick handler to each menu item but even then, I don't know how to call the toggleMenu method defined in menuFactory.js.

**Comment by negomi** [comment]
Ah, no worries :)

You've got the right idea with the onClick handler for each item. Basically, `isOpen` is a boolean that lets you tell the menu whether to render as open or closed.

So you keep track of the menu state externally, then use that to determine the value of the `isOpen` prop.

Something like this:

```javascript
var Example = React.createClass({
  handleMenuClick: function(event) {
    event.preventDefault();
    // Using the parent component's state to keep track of the menu
    this.setState({menuOpen: false});
  },
  render: function() {
    return (
      <Menu isOpen={ this.state.menuOpen }>
        <RadiumLink onClick={ this.handleMenuClick } className="menu-item" to="/">Home</RadiumLink>
      </Menu>
    );
  }
});
```

You can ignore the toggleMenu method etc - the component handles its own internals based on the props passed to it.

**Comment by srsjake** [comment]
That doesn't seem to work. I intialized menuOpen in getInitialState to get it to run without errors and it changes on initial load depending on what I set it to. However, actually clicking on a link doesn't close the menu. Also, using onClick on each link seems to prevent the router from accessing the routes too.

There's some additional behavior which might give you some useful information. If I set menuOpen to `true` in getInitialState, the menu will close when I click on any of the links BUT only once. If I open the menu via burger again, clicking a link won't close it. The routes aren't navigated to in this scenario either.

**Comment by negomi** [comment]
It's going to be difficult to give you the exact code you need without more information.

Do you have a repo I can pull down somewhere to see if I can give you a more complete example?

**Comment by srsjake** [comment]
The site I'm working on is over here: https://github.com/srsjake/portfolio-v2

You should just need to run npm install and then npm start to fire up the browsersync development server. The entry point is in `src/app.js` and each route basically has its own folder with a .js and .scss file. The menu is along with other shared components in the `components` directory.

Apologies if the code is a little messy. I'm in the middle of working on it. And a huge thank you for taking the time to help me.

**Comment by negomi** [comment]
Great, thanks. I'm pretty busy today but I'll take a look as soon as I can

**Comment by negomi** [comment]
Ok, so there was actually a bug in the component preventing this from working. It is fixed in v1.8.2.

In your case, I think you only ever want to render the menu as closed. This will ensure it closes after you've clicked an item and navigated to one of your routes.

So, upgrade to 1.8.2, ignore all the stuff about handling state externally, and this (much simpler) example should do what you want:

``` javascript
var Example = React.createClass({
  render: function() {
    return (
      <Menu right isOpen={ false }>
        <RadiumLink className="menu-item" to="/">Home</RadiumLink>
        <RadiumLink className="menu-item" to="/about">About</RadiumLink>
        <RadiumLink className="menu-item" to="/portfolio">Portfolio</RadiumLink>
        <RadiumLink className="menu-item" to="/contact">Contact</RadiumLink>
      </Menu>
    );
  }
});
```

**Comment by srsjake** [comment]
That did it, thanks!

**Comment by giladbr** [comment]
I was also able to achieve that clicking an item will close the menu simply by using `isOpen={false}` ! Thank you!

**Comment by manosim** [comment]
I have exactly the same issue with @giladbr (I'm also using redux) and I'm on version `1.10.4`. I've set `isOpen={ false }` but when I click on a link the menu does not close. Any ideas?

```javascript
``

**Comment by flipflopapp** [comment]
@manosim I am facing the same issue - did you manage to fix it somehow?

**Comment by pauljeffreys** [comment]
@manosim - I grabbed the latest version of these files and had the same non closing issue, but adding the isOpen={false} fixed it for me so not clicking on a menu item closes the menu again. Going by what is mentioned previously, it sounds like the bug doing this was fixed and you might have an older file version of things?

I grabbed mine yesterday.

**Comment by wintermute42** [comment]
I seem to have the same issue, using "react-burger-menu": "^2.1.9" together with "redux-burger-menu": "^0.2.2". Adding isOpen={ false } to the Menu doesn't fix it in my case, I cannot get the Menu to close when the user clicks on an item within. Does anyone else use this solution in combination with  "redux-burger-menu"?

**Comment by GabrielDierks** [comment]
hey guys, i simply just added the state into the constructor and its working fine :)

this.state = {
      currentMenu: 'slide',
      side: 'right',
      **isOpen:false**
    };
