### ISSUE TITLE
v1.8.2 animation not work properly

### ISSUE THREAD

**Issue by SeqviriouM** [negomi/react-burger-menu#59]
v1.8.2: elastic animation not work properly in Chromium for me.

**Comment by SeqviriouM** [comment]
Sorry for the carelessness. Haven't noticed this line:

> Elastic and Bubble are not currently supported with Webpack builds due to their Snap.svg dependency.

Have switched on version 1.7.1

**Comment by negomi** [comment]
Yeah, the Snap.svg dependency is the problem there. Glad you saw the warning :)
