### ISSUE TITLE
Closing menu from the body?

### ISSUE THREAD

**Issue by pertrai1** [negomi/react-burger-menu#61]
How would I go about having the menu close when I click outside of the menu? I am in need of having to close the menu when clicking on the body. I have a header class that I return the header with the jsx markdown html menu wrapped inside of the <Menu>. Only problem is that I don't have access to the body from this component from what I know of with my work in React.

Any help would be great.

Thank you,

Rob

**Comment by negomi** [comment]
Hi @pertrai1, I assume you're using the menu the `noOverlay` option? Enabling the overlay is the easiest way to make sure the menu closes when a user clicks outside of it.

If you need to use it without the overlay, you can add an `onClick` handler the body, and then use that handler to trigger a re-render of the menu with the [`isOpen`](https://github.com/negomi/react-burger-menu#open-state) prop set to false. I don't know how you're managing state, and that will determine exactly how you do this, but hopefully that's enough to get you started.

**Comment by pertrai1** [comment]
Awesome,  thank you
