### ISSUE TITLE
Menu not scrollable?

### ISSUE THREAD

**Issue by jwamsterdam** [negomi/react-burger-menu#62]
Hi, I tested the menu on an iPhone 5 landscape mode, but I experience that the menu is not scrollable.. Should I fix that myself within the menu, eg add a container with scrollbar, or can this be fixed by the source you provide?  Thank you!

**Comment by negomi** [comment]
Hey @jwamsterdam, you just need to add `overflow-y: scroll;` to the `.bm-menu` element if you want scrolling.

It's not there by default as it's not necessarily needed for every use case, and it would make scroll bars show all the time by default in some browsers, which would look weird if there were only 5 items in the menu :)

Hope that helps!

**Comment by gHashTag** [comment]
What style do I add to this task if I use javascript styles?
https://github.com/negomi/react-burger-menu#javascript

**Comment by negomi** [comment]
@gHashTag the classnames for the JS styles are the same, just camelcased, so you would do this:

```js
const styles = {
  bmMenu: {
    overflowY: 'scroll'
  }
};
```
