### ISSUE TITLE
Change in 1.8.2 causes calls to onStateChange even if state has not changed

### ISSUE THREAD

**Issue by travellingprog** [negomi/react-burger-menu#63]
This change in 1.8.2: https://github.com/negomi/react-burger-menu/compare/v1.8.1...v1.8.2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

... will cause `this.toggleMenu()` to be called whether or not `isOpen` has changed. Within toggleMenu, `onStateChange()` is always called: https://github.com/negomi/react-burger-menu/blob/9737db22668b7c876bd7f622aa158d1acbe6dd12/src/menuFactory.js#L34 .

In our application, we had assumed that this callback would only be triggered when the state changed, and unfortunately this ended up causing an infinite loop :/

I could possible put together a PR with some improvements around this, although I'm confused by which branch I should be branching from ... your remote master branch still states the version as 1.8.1.

**Comment by negomi** [comment]
Hi @travellingprog, oh yes, I see :/

The `isOpen` logic needs rethinking because everything so far that's worked for one use case/combination turns out to be buggy for another. I don't think it's ever been quite correct. I just haven't had the time recently to sit down and look at it properly.

If you'd like to submit a PR, that would be great. Sorry about the old version - I'd forgotten to push the latest tag. It's updated now.

**Comment by travellingprog** [comment]
Thanks for updating master!

Yeah, I gathered from reading #58 that you made the change in 1.8.2 to address another issue. I might put some time in the next few days to look at this, would you be able to provide a list of bugs around `isOpen`, or a list of use cases you want to address?

**Comment by negomi** [comment]
So I just found a couple of hours to look through the history at all the ways it's been broken, and wrote some more comprehensive tests covering each case.

The logic change to make them all pass was pretty simple (checking for the isOpen prop being defined, and then checking for either a prop or state difference).

I haven't merged it yet, but the diff is here if you feel like taking a look: https://github.com/negomi/react-burger-menu/compare/fix/isOpen-logic?expand=1

Thanks for your help!

**Comment by travellingprog** [comment]
Wow, thanks for taking the time to do that! Those are way better tests than anything I would've put together.

I think that `propDiff` (https://github.com/negomi/react-burger-menu/compare/fix/isOpen-logic?expand=1#diff-747cb230178c9213608520022a644c5eR189) will cause an issue. I believe you should skip that check and only need your condition around the toggleMenu call to be `if (typeof nextProps.isOpen !== 'undefined' && (nextProps.isOpen !== this.state.isOpen)`.

Here's the scenario I'm thinking might fail, and I'll see if I can put together a test for it:

1. ParentComponent renders Menu with `isOpen` set to true.
1. This results in Menu's `isOpen` state also being true.
1. User clicks on its internal CrossIcon to close the menu, which triggers toggleMenu.
1. This results in Menu's `isOpen` state to be false, **although Menu's this.props.isOpen is still set to true**.
1. ParentComponent gets the update with the onStateChange callback, changes its own state, and re-renders accordingly, **with Menu's isOpen attribute set to false**.
1. Menu's `componentWillReceiveProps()` is triggered, and because `nextProps.isOpen !== this.props.isOpen`, then `toggleMenu()` is going to get called again.

**Comment by negomi** [comment]
Yeah, that looks like another case! I'll update the diff as soon as I can.

**Comment by negomi** [comment]
Just pushed v1.8.3, which includes your suggested change, and a (now passing) test which fails with the logic I had before.

So that's all the cases I know of covered and documented in tests for now!

Thanks again for your help with this :)
