### ISSUE TITLE
Usage with typescript

### ISSUE THREAD

**Issue by nahushf** [negomi/react-burger-menu#65]
Has a Typings definition been written for this? I can't seem to find one

**Comment by negomi** [comment]
Hi @nahushfcc, I don't know of anyone using this with TypeScript yet so no, there isn't one currently.

If you feel like submitting a PR it would be very welcome :)

**Comment by viveke** [comment]
I was also looking for a typing definition for this one.

**Comment by mattnedrich** [comment]
@viveke me too

**Comment by radziksh** [comment]
@nahushf @negomi @mattnedrich @viveke Can you test this? I wrote a definition for this environment https://github.com/wmonk/create-react-app-typescript
Standard es6 modules supported by webpack.

**Comment by negomi** [comment]
Thanks so much @radziksh!

I don't use TypeScript myself, so I would love to get some other people's opinion on this :)

**Comment by djskinner** [comment]
I'm using https://www.npmjs.com/package/@types/react-burger-menu with good results.

The only issue is that I want to set a zIndex on bmBurgerButton styles. I don't think its properly supported so I have to disable typings for the Styles which is a little unfortunate.

**Comment by Nikolsi** [comment]
Unfortunately, probably the typings are outdated. There are no such methods like disableCloseOnEsc maybe some others
