### ISSUE TITLE
Latest react: Error in Firefox

### ISSUE THREAD

**Issue by jwamsterdam** [negomi/react-burger-menu#66]
Hi, 

I use the following code for setup of Burger Menu in react:

    var Menu = require('react-burger-menu').slide;

or 

    import { slide as Menu } from 'react-burger-menu';

And in my render view:

    render() {
        return (
            <Menu >
                <a id="home" className="menu-item" href="" onClick={this.changePage}>
            </Menu>
        );
    }

I am using ES6 notation for export default class Burgermenu extends React.Component

In chrome all works as expected, but in FireFox I get the following error:

    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

Which makes the complete page unable to load..

Any ideas?

**Comment by negomi** [comment]
Hi @jwamsterdam,

In the example above, your `<a>` is missing its closing tag, which could be causing problems (assuming that's also the case in your code).

Other than that, I can't think of anything immediately obvious. I tried running a test project to replicate your situation, and (after fixing the closing tag) didn't get an error in Firefox (version 47).

What version of React/Firefox are you using?

**Comment by jwamsterdam** [comment]
I did make some issue on my side, but I do face the following, which is basically exaclty the same as this issue: https://github.com/negomi/react-burger-menu/issues/44

Whenever I try to insert React Bootstrap <Checkbox> elements, I get the error:
    TypeError: CSS2Properties doesn't have an indexed property setter.

Only way to fix that, is to include Radium and use the following notation: 
    {<RadiumCheckbox checked={this.props.settings.stops.onestop} onChange={this.changeStops('onestop')}>1 stop</RadiumCheckbox>}

Then the error in the console dissapears, but the strange thing is that during onload, the onchange event gets fired, and the onchange event is not called when clicking on the element.

Any ideas to help me out here?

much appreciated!

**Comment by jwamsterdam** [comment]
Its fixed, needed to use onChange={this.changeStops.bind(this, 'onestop')}

**Comment by bougattab** [comment]
Hi @negomi ,

I got the same error running this code (and the page won't reload), i have firefox (version 49) this my code: 

import React from 'react'
import { slide as Menu } from 'react-burger-menu'
import { Link } from 'react-router'
import { FormattedMessage } from 'react-intl'

let menuStyles = {
  bmBurgerButton: {
    position: 'relative',
    width: '30px',
    height: '30px',
  },
  bmBurgerBars: {
    background: '#005388',
  },
  bmCrossButton: {
    height: '24px',
    width: '24px',
  },
  bmCross: {
    background: '#005388',
    cursor: 'pointer',
  },
  bmMenu: {
    background: 'white',
    padding: '2.5em 1.5em 0',
    fontSize: '1.15em',
  },
  bmMorphShape: {
    fill: '#373a47',
  },
  bmItemList: {
    display: 'flex',
    flexDirection: 'column',
    lineHeight: '200%',
    color: '#005388',
    fontWeight: '500',
    padding: '0.8em',
  },
  bmOverlay: {
    backgroundColor: '#ffffff',
  },
}

class BurgerMenu extends React.Component {
  static propTypes = {
  }
  render () {
    return (
      <Menu styles={ menuStyles }
        width={ 300 }
        right noOverlay >
        <Link to='/missions-expertise'>
          <FormattedMessage
            id='navigationBar.link.expertise'
            description='Expertise missions link'
            defaultMessage="MISSIONS D'EXPERTISE"
          />
        </Link>
        <Link to='/missions-packagees'>
          <FormattedMessage
            id='navigationBar.link.packaged'
            description='Packaged missions link'
            defaultMessage='MISSIONS PACKAGEES'
          />
        </Link>
        <Link to='/missions-specifiques'>
          <FormattedMessage
            id='navigationBar.link.specific'
            description='Specific link'
            defaultMessage='MISSIONS SPECIFIQUES'
          />
        </Link>
      </Menu>
    )
  }
}

export default BurgerMenu

and the error is:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

can you see the problem ?

Thnx,

**Comment by RobertoIDL** [comment]
Same here

**Comment by negomi** [comment]
Hi @RobertoIDL, can you paste your code?
