### ISSUE TITLE
Cannot get escape key to close menu when using isOpen prop

### ISSUE THREAD

**Issue by jreancsu** [negomi/react-burger-menu#67]
I'm using a separate button to toggle the menu using the `isOpen` prop.  I have the `isOpen` prop `connect()`'ed to a boolean value in my Redux store.   The menu opens and closes as expected, except for when pressing the `escape` key. 

I believe the problem is here:
```
listenForClose: function listenForClose(e) {
      e = e || window.event;

      if (this.state.isOpen && (e.key === 'Escape' || e.keyCode === 27)) {
        this.toggleMenu();
      }
    },
```

`this.state.isOpen` is `false` when I hit the escape key.  Does anyone have an example of using the `escape` key to toggle the menu successfully when using the `isOpen` prop, or is there a bug here?

**Comment by negomi** [comment]
Hi @jreancsu. If you've rendered the menu with `isOpen` set to `true`, then `this.state.isOpen` should also be `true`, so the Escape key should work as expected.

If you have an example of your code somewhere then I can take a look to see what's happening.

**Comment by jreancsu** [comment]
This is code for work, so I'll have to transform it into a "not the droids you're looking for version" haha.  I'll get that to you as soon as I can.  I'll try and push up an example on Github so you can pull it down and study it.

**Comment by negomi** [comment]
This has had no response for a while, so I'm going to close it for now - feel free to let me know if it's still an issue!

**Comment by Duskfall** [comment]
I have one sidebar with isOpen attribute as a state boolean flag of a parent controller, and when I press escape, it only updates the internal state of the component. Cant we get a callback method when pressing escape?

**Comment by negomi** [comment]
Sounds like [`onStateChange`](https://github.com/negomi/react-burger-menu#state-change) is what you're looking for?

**Comment by Duskfall** [comment]
Yes this would be a workaround and this is how I am doing it now, but I think it should take the isOpen from props not having an isOpen state itself. Thank you anyway!
