### ISSUE TITLE
react, react-dom should be peer dependencies

### ISSUE THREAD

**Issue by miracle2k** [negomi/react-burger-menu#68]
``react-burger-menu`` should never be pulling in a custom version of react just for itself. I believe that in those cases peer dependencies should be used.

This seems to be the common approach taken by other libraries.

**Comment by negomi** [comment]
It used to include those modules as `peerDependencies`, and then I moved away from them around the time React moved from 0.14.x to 15.x, as there is [debate around their intended use](https://github.com/npm/npm/issues/5080#issuecomment-40545599).

As new React versions still frequently introduce breaking changes, if I decide to move back to using `peerDependencies`, I need to figure out what a sensible semver range would be (as I believe react-burger-menu still works with some React 0.14.x versions as well as 15), or alternatively go with some other way of communicating supported versions.

**Comment by miracle2k** [comment]
Thanks for the link. But it seems to suggest that the alternative, were peer dependencies to be removed from npm, would be to not reference react in package.json at all, and make it a documentation issue. That's ok in my mind.

My problem is that if react is a regular dependency, it might be installed twice, which will never work out.

I think if you were to move the dependency to a peerDependency with the semver range as-is, this would be an improvement, since if the user's installed react version doesn't match, they will get a warning, as opposed to a setup that will break during run because of a duplicate react.

**Comment by negomi** [comment]
Added to peerDependencies in v1.9.1.
