### ISSUE TITLE
Text-indenting button text

### ISSUE THREAD

**Issue by hedgehog34** [negomi/react-burger-menu#69]
Hello - great project,

When I select text around hamburger button, it reveals hidden text, which isn't ideal.
 
Is there a way of removing `<button>` element's text ("Open Menu" inside of `<div class=bm-burger-button>`) using `text-indent: -9999px` technique, instead of masking it with `color: transparent`, for example by passing it with a `style` object?

Even adding a class to this element would be enough to provide a CSS hook. I think it would be a good way to avoid over-qualifying selector ie: `.bm-burger-button > button { text-indent: -9999px }`

**Comment by negomi** [comment]
Hi @hedgehog34,

Sure, I'd be happy to move to the `text-indent` approach in the main project actually - I think it's probably a better solution than making the text transparent.

Will add it to the next release!

**Comment by hedgehog34** [comment]
Hi @negomi - thanks. 
Just forked the project, maybe I could contribute to it when I get familiar.

Are you open to extending the project in regards of how content behave on sidebar toggle? What I am looking for is something more responsive like `Menu.squeeze`, which would simply downsize the `width` of everything inside`<main id="page-wrap">` element.

Also, this would be allowed to happen only on screens large enough for this to make sense, but we could have some sort of "fallback" behaviour for mobiles.

**Comment by hedgehog34** [comment]
I addressed this bug in this PR (along with other things) - #71

**Comment by negomi** [comment]
Hi @hedgehog34,

Thanks for your PR - I like what you've done with the squeeze effect. I'm still deciding whether to add it to the main package, but in the mean time, I've fixed this issue in v1.9.1.
