### ISSUE TITLE
How to use with require js?

### ISSUE THREAD

**Issue by tampham47** [negomi/react-burger-menu#7]

**Comment by negomi** [comment]
I don't have an example of using this with RequireJS, but I guess it will depend on your setup. What's not working? What have you tried?

**Comment by negomi** [comment]
Closing as no response for a while. Happy to re-open if this is an issue with the component.

**Comment by tampham47** [comment]
I can use it right now. You do very nice, thanks. ^^

**Comment by negomi** [comment]
Great, glad to hear it :)
