### ISSUE TITLE
Multiple menus in same page

### ISSUE THREAD

**Issue by mbeaudru** [negomi/react-burger-menu#73]
I would like to use two burger menus, one right and the other left. 

But it seems to be a problem because the style is defined through classes like .bm-burger-button, so my two menus have their burger buttons superimposed and I can't add custom classes to differentiate one from another.

Any thought on this ?

**Comment by hedgehog34** [comment]
The way I get over this hurdle is:
I set 2 different external files with 2 specific sets of style rules:
```
import styles from './common/burger-menu-styles';
import detailsStyles from './common/details-panel-styles';
```

And then when I use 2 different menus I simply pass them in as2  separate objects via `props`:
```
<Menu1 styles={styles} ... />
<Menu2 styles={detailsStyles} ... />
```

This should give you control over each class rules.

**Comment by negomi** [comment]
Hi @mbeaudru, yep, you'll have to pass the styles for each menu as a JS object, as suggested above. Hope that helps :)

**Comment by mbeaudru** [comment]
Thank's for the workaround, a bit tricky but easy to implement :+1:
