### ISSUE TITLE
Default icons (burger and cross) cannot be removed entirely

### ISSUE THREAD

**Issue by hedgehog34** [negomi/react-burger-menu#79]
It seems that using either `customBurgerIcon={false}` or `customCrossIcon={false}` doesn't do anything. In order of removing those two from UI, custom styles object need to be modified ie.
```
var styles = {
  bmBurgerButton: {
   ...
   display: 'none'
  },
}
```

**Comment by negomi** [comment]
This was a bug, fixed in v1.9.8. Thanks :)
