### ISSUE TITLE
document is not defined when rendering server side

### ISSUE THREAD

**Issue by krisfields** [negomi/react-burger-menu#8]
I'm getting a document is not defined error, which I think is happening because of the server side rendering.

**Comment by negomi** [comment]
Hey @krisfields, I think this is because some of the component's dependencies reference a DOM, which means trying to render server-side currently throws errors. I'm looking at potential ways to solve this, as it would be nice to support server-side rendering.

**Comment by nicholasdickey** [comment]
Would also be interested in server-side rendering. Thanks!

**Comment by CalebEverett** [comment]
I'd also be interested in server side rendering - thank you!

**Comment by svnlto** [comment]
I guess we're relying on this one to be fixed https://github.com/facebook/react/issues/3620

**Comment by negomi** [comment]
As of [v1.3.0](https://github.com/negomi/react-burger-menu/releases/tag/v1.3.0), server-side rendering should work :smiley:
