### ISSUE TITLE
I think the documentation about "IsOpen" should be changed

### ISSUE THREAD

**Issue by giladbr** [negomi/react-burger-menu#80]
My goal was to get the menu to close on click of any of its items.
After spending a few hours with the `isOpen` prop, I realized that all I needed to do was to set `isOpen={false}`.
I now realize that setting `isOpen={false}` means that by default, the menu is rendered as hidden, and on clicking an item the menu will close, probably because the click causes a re-render, using the default setting.
I was under the impression that `isOpen` refers to the menu state - `false` when the menu's closed and `true` when the menu's open. The current documentation states that:

_You can control whether the sidebar is open or closed with the isOpen prop. This is useful if you need to close the menu after a user clicks on an item in it, for example, or if you want to open the menu from some other button in addition to the standard burger icon. The default value is false._

But it doesn't explain HOW to implement the "close on click" behaviour (which is a pretty common demand, I'd assume), nor the role of the `isOpen` prop, which is a little unintuitive in my opinion.

Apart from that I got everything working - thank you very much for this component!

**Comment by negomi** [comment]
Hey @giladbr, thanks for the feedback - I'm sorry you had a confusing time with this.

I wonder if an examples section for common patterns (like the close on click behaviour you describe) could be useful here. I tried to keep the documentation for each prop short and specific, so people could skim through it all without getting lost in the details. However, I totally agree some things could use a little more explanation, and I would love to make things easier for people to grasp.

I'll put a note on this and think about the best way to make it better! 💭

**Comment by 2easy** [comment]
+1

**Comment by AdamGustavsson** [comment]
+1

**Comment by negomi** [comment]
I have now expanded the documentation to hopefully better explain how to use this prop.

Thanks for your suggestion!
