### ISSUE TITLE
Build size using Webpack (React)

### ISSUE THREAD

**Issue by timarney** [negomi/react-burger-menu#83]
I noticed my build sized jumped quite a bit after importing this package (roughly 175 KB).

Looks like the current built min version for the package is  18 KB (react-burger-menu.min.js).

From what I see this is because at least in part Snap.svg gets included in the bundle regardless of what menu effect gets used when using Webpack (i.e. using only push).  

Can you confirm / any thoughts on getting around this?

**Comment by negomi** [comment]
Hi @timarney, I'm not super familiar with Webpack so I don't have a solution off the top of my head.

This issue has been raised before, and I restructured the code so it would no longer pull in Snap.svg for menu effects that didn't use it (see https://github.com/negomi/react-burger-menu/pull/74 for reference).

As to why it's still getting included in your build, I'm afraid I'm not sure. @MikeKlemarewski, it sounded like you got this working - do you have any suggestions?

**Comment by timarney** [comment]
Okay thanks @negomi for the ref to #74 

I'll put together a standalone repo next week with webpack just the menu to confirm.

**Comment by timarney** [comment]
Here's a link to the intial test repo -  157 KB with React split out into a seperate vendor folder
https://github.com/timarney/react-burger-menu-webpack-test

I'll do some more testing and let you know what I figure out.

**Comment by timarney** [comment]
Doing a direct import seems to work the best (using es2015): 

```import Menu from 'react-burger-menu/lib/menus/push'```

That drops the bundle size down to 74 KB

I ran this tool as per #74

https://github.com/robertknight/webpack-bundle-size-analyzer

On my test repo - here's part of the report

```
radium: 62.26 KB (7.55%)
inline-style-prefixer: 37.73 KB (4.58%)
inline-style-prefix-all: 17.99 KB (2.18%)
react-burger-menu: 16.2 KB (1.96%)
bowser: 15.71 KB (1.90%)
Note: webpack-bundle-size-analyzer reports sizes before minification. 
```
So given the dependencies involved 74 KB seems to be the lowest I can get.  Much better than where I started.

**Comment by negomi** [comment]
Cool, glad you managed to find a workaround.

I'd be surprised if there wasn't something you could do with Webpack config to avoid bundling unused dependencies - I'll let you know if I come across anything!

**Comment by timarney** [comment]
Webpack 2 will have tree-shaking (removal of unused exports) when it comes out.

**Comment by deser** [comment]
Hi Guys, is it possible to make Radium dependency optional? 
If somebody passes via props `radium={true}` then it would return `return Radium(React.createClass({`. Otherwise it would return just `React.createClass({`
