### ISSUE TITLE
common.js  ????

### ISSUE THREAD

**Issue by brugon2016** [negomi/react-burger-menu#86]
Hi

How do you get the common.js file ?
I know how to do bundle.js (browserifiy) but what is the content of common.js ?

Thanks for the help

**Comment by negomi** [comment]
Hi @brugon2016, not sure what you mean.

Do you mean the common.js file generated when you run this project locally? That's the bundle of vendor dependencies used for the demo page at http://negomi.github.io/react-burger-menu/.

What are you trying to do?

**Comment by brugon2016** [comment]
Hi thanks for replying. It's fine now. I thought the common.js was a file missing in the project. :)
Everything works fine now.

Cheers
