### ISSUE TITLE
angular 2 port?

### ISSUE THREAD

**Issue by guykatz** [negomi/react-burger-menu#9]
this is by far the most good looking side nav I have ever seen.
would live to get it working over angular 2 when its out...
did you ever think of porting this to multiple frameworks? will it be hard to do?

**Comment by negomi** [comment]
It's a great idea! I'm not sure if I'll have time to write an Angular 2 port personally, but I'll bear it in mind. 

The component is really just an element with two states, with different styles applied for each state. So the implementation details will differ, but it should be possible to port to most frameworks.

**Comment by danieleteti** [comment]
+1
