### ISSUE TITLE
Menu opens whenever I click any link anywhere.

### ISSUE THREAD

**Issue by kvnvelasco** [negomi/react-burger-menu#91]
So,

I've checked the logs, nothing is being dispatched. Something is happening that I don't understand.

I've wrapped every link imaginable in radium, to no avail.

**Comment by kvnvelasco** [comment]
I am an idiot.

**Comment by adamduren** [comment]
@kvnvelasco Can you please share what the solution was? I am seeing this happen when I click anything on the page.

**Comment by negomi** [comment]
Posting this here for others running into this issue: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-imported-the-menu-but-the-burger-icon-isnt-showing-and-the-menu-opens-when-i-click-anywhere
