### ISSUE TITLE
customBurgerIcon overwrites class of the supplied element

### ISSUE THREAD

**Issue by 2easy** [negomi/react-burger-menu#95]
I want to use Font Awesome icon but the elements class is overwritten, my workaround:

`<Menu styles={styles} customBurgerIcon={ <span><i className='fa fa-cog fa-spin' /></span> }/>`

I think 'bm-icon' should be appended if the supplied React Element has it's own class.

**Comment by negomi** [comment]
Hi @2easy, this is happening because `customBurgerIcon` is only really expecting an image.

I am happy to make it more flexible to allow font icons too though.

**Comment by 2easy** [comment]
Thanks! According to documentation any React Element should be allowed. If you don't have time I can make PR.

**Comment by negomi** [comment]
Yep, that's correct, it's just a use case I wasn't considering initially :)

If you feel like making a PR that would be great! Otherwise I will get round to this when I have time (not sure exactly when that will be though).

**Comment by TimMeade** [comment]
Any update on this?  We were actually hoping to use a styled Button....

**Comment by Devendra-Lad** [comment]
Can we replace button with Name button

**Comment by Mael-P** [comment]
To have Font Awesome icon, do this:
<Menu burgerButtonClassName={ "fa fa-user-circle fa-2x" } customBurgerIcon={ <img src="" /> }>
It work even for CrossButton.

**Comment by semisse** [comment]
This functionality would be awesome for those who would like to have a little more flexibility styling the burger spans. Anyway I could help?

**Comment by omasback** [comment]
why is the class even being overwritten? The overwriting class `.bm-icon` isnt even being used

**Comment by negomi** [comment]
Fixed in v2.6.9
