### ISSUE TITLE
isOpen true error can't find page-wrap and outer-container

### ISSUE THREAD

**Issue by stahlmanDesign** [negomi/react-burger-menu#98]
I'm getting these errors when I set isOpen to true so the menu starts in an open state:

```
menuFactory.js:91 Element with ID 'page-wrap' not found
menuFactory.js:91 Element with ID 'outer-container' not found
```

It ends up working, but I want to get rid of the errors. I've tried rearranging my divs, even setting placeholder divs with those IDs in index.html but it always throws the errors. Does not throw them is isOpen={false}

``` js
  render() {
    if (!this.state.ready ) return <div></div>
    return (
      <div>
        <div id="outer-container">
          <Menu
            noOverlay
            isOpen={true}
            width={80}
            pageWrapId={"page-wrap"}
            outerContainerId={"outer-container"}
            >
            <RadiumLink className="menu-item" to="/">
              <MenuItem
                title={this.provider.state.loggedInMemberDetails.member.firstName}
                image={this.provider.state.loggedInMemberDetails.member.avatarUrl || avatarPlaceholder }/>
            </RadiumLink>
          </Menu>

          <main id="page-wrap" style={{ 'paddingTop': '4em' }}>

            {/* NOTE all content except menu bar rendered in div below, using react-router */}
            <div className="container app-pages">
              {this.props.children}
            </div>
            <NavigationBar
              lang={this.provider.state.lang}
              handleLangChange={this.handleLangChange.bind(this)}/>
          </main>
        </div>
      </div>
    )
  }
```

**Comment by negomi** [comment]
Hi @stahlmanDesign, ah yes, I see this error too.

My initial thought was that `getElementById` must be getting called before the elements existed in the document. But if I log the document just before the `getElementById` call, those elements are in it, so I'm not entirely sure why the error is being thrown.

I'll look into it - thanks for reporting.

**Comment by stahlmanDesign** [comment]
Related to this, if I start with isOpen true, if I close, anything I click will reopen it.

**Comment by keiver** [comment]
I was getting this bug, solved it by changing the state to open on ```componentDidMount()```.

**Comment by negomi** [comment]
Thanks @keiver - makes sense that this would solve the problem. I've added your solution to the docs: https://github.com/negomi/react-burger-menu#open-state 👍
